function out = model(stageCount,enablePeriod,selectedCycle,brokenCascade)
%MODEL Simulate bounded edge-triggered registers with enable and reset.
%   Each enabled register captures its pre-edge input. Stage 1 captures D;
%   later stages capture the previous stage's pre-edge value. Reset is
%   synchronous and has priority over enable. The deliberately broken mode
%   instead cascades newly updated values through all stages on one edge.

if nargin < 1
    stageCount = 1;
end
if nargin < 2
    enablePeriod = 1;
end
if nargin < 3
    selectedCycle = 6;
end
if nargin < 4
    brokenCascade = false;
end

validateIntegerScalar(stageCount,1,4,'P03:InvalidStageCount','stageCount');
validateIntegerScalar(enablePeriod,1,4, ...
    'P03:InvalidEnablePeriod','enablePeriod');
validateIntegerScalar(selectedCycle,1,16, ...
    'P03:InvalidSelectedCycle','selectedCycle');
validateBooleanScalar(brokenCascade);
brokenCascade = logical(brokenCascade);

cycle = (1:16).';
inputData = [9 2 13 5 14 7 1 12 3 10 6 15 4 11 8 1].';
reset = cycle == 1;
captureEnable = reset | (cycle >= 2 & mod(cycle-2,enablePeriod) == 0);
cycleCount = numel(cycle);
resetValue = 0;
wordWidthBits = 4;

stateBefore = zeros(cycleCount,stageCount);
stateAfter = zeros(cycleCount,stageCount);
validBefore = false(cycleCount,stageCount);
validAfter = false(cycleCount,stageCount);
referenceStateAfter = zeros(cycleCount,stageCount);
referenceValidAfter = false(cycleCount,stageCount);

previousState = resetValue*ones(1,stageCount);
previousValid = false(1,stageCount);
previousReferenceState = previousState;
previousReferenceValid = previousValid;

for cycleIndex = 1:cycleCount
    stateBefore(cycleIndex,:) = previousState;
    validBefore(cycleIndex,:) = previousValid;
    nextState = previousState;
    nextValid = previousValid;
    correctNextState = previousReferenceState;
    correctNextValid = previousReferenceValid;

    if reset(cycleIndex)
        nextState(:) = resetValue;
        nextValid(:) = false;
        correctNextState(:) = resetValue;
        correctNextValid(:) = false;
    elseif captureEnable(cycleIndex)
        nextState(1) = inputData(cycleIndex);
        nextValid(1) = true;
        correctNextState(1) = inputData(cycleIndex);
        correctNextValid(1) = true;
        for stageIndex = 2:stageCount
            correctNextState(stageIndex) = ...
                previousReferenceState(stageIndex-1);
            correctNextValid(stageIndex) = ...
                previousReferenceValid(stageIndex-1);
            if brokenCascade
                nextState(stageIndex) = nextState(stageIndex-1);
                nextValid(stageIndex) = nextValid(stageIndex-1);
            else
                nextState(stageIndex) = previousState(stageIndex-1);
                nextValid(stageIndex) = previousValid(stageIndex-1);
            end
        end
    end

    stateAfter(cycleIndex,:) = nextState;
    validAfter(cycleIndex,:) = nextValid;
    referenceStateAfter(cycleIndex,:) = correctNextState;
    referenceValidAfter(cycleIndex,:) = correctNextValid;
    previousState = nextState;
    previousValid = nextValid;
    previousReferenceState = correctNextState;
    previousReferenceValid = correctNextValid;
end

output = stateAfter(:,end);
outputValid = validAfter(:,end);
referenceOutput = referenceStateAfter(:,end);
referenceOutputValid = referenceValidAfter(:,end);
valueMismatch = outputValid & referenceOutputValid & ...
    output ~= referenceOutput;
mismatchMask = outputValid ~= referenceOutputValid | valueMismatch;
earlyValidMask = outputValid & ~referenceOutputValid;
acceptedInput = captureEnable & ~reset;
firstValidCycle = find(outputValid,1,'first');
firstMismatchCycle = find(mismatchMask,1,'first');

if reset(selectedCycle)
    selectedAction = 'reset';
elseif captureEnable(selectedCycle)
    selectedAction = 'capture/shift';
else
    selectedAction = 'hold';
end

stageLabels = arrayfun(@(stageIndex) sprintf('Q%d',stageIndex), ...
    1:stageCount,'UniformOutput',false);
out = struct( ...
    'stageCount',stageCount, ...
    'enablePeriod',enablePeriod, ...
    'brokenCascade',brokenCascade, ...
    'cycle',cycle, ...
    'cycleCount',cycleCount, ...
    'wordWidthBits',wordWidthBits, ...
    'resetValue',resetValue, ...
    'inputData',inputData, ...
    'reset',reset, ...
    'captureEnable',captureEnable, ...
    'acceptedInput',acceptedInput, ...
    'activeEdgeCount',cumsum(acceptedInput), ...
    'stateBefore',stateBefore, ...
    'stateAfter',stateAfter, ...
    'validBefore',validBefore, ...
    'validAfter',validAfter, ...
    'referenceStateAfter',referenceStateAfter, ...
    'referenceValidAfter',referenceValidAfter, ...
    'output',output, ...
    'outputValid',outputValid, ...
    'referenceOutput',referenceOutput, ...
    'referenceOutputValid',referenceOutputValid, ...
    'mismatchMask',mismatchMask, ...
    'mismatchCycles',cycle(mismatchMask), ...
    'mismatchCount',sum(mismatchMask), ...
    'earlyValidMask',earlyValidMask, ...
    'earlyValidCount',sum(earlyValidMask), ...
    'captureCount',sum(acceptedInput), ...
    'holdCount',sum(~reset & ~captureEnable), ...
    'resetCount',sum(reset), ...
    'firstValidCycle',firstValidCycle, ...
    'firstMismatchCycle',firstMismatchCycle, ...
    'additionalActiveEdgeDelay',stageCount-1, ...
    'dataStorageBitCount',wordWidthBits*stageCount, ...
    'stageLabels',{stageLabels}, ...
    'selectedCycle',selectedCycle, ...
    'selectedInput',inputData(selectedCycle), ...
    'selectedReset',reset(selectedCycle), ...
    'selectedEnable',captureEnable(selectedCycle), ...
    'selectedAction',selectedAction, ...
    'selectedStateBefore',stateBefore(selectedCycle,:), ...
    'selectedStateAfter',stateAfter(selectedCycle,:), ...
    'selectedValidAfter',validAfter(selectedCycle,:), ...
    'selectedOutput',output(selectedCycle), ...
    'selectedOutputValid',outputValid(selectedCycle), ...
    'selectedReferenceOutput',referenceOutput(selectedCycle), ...
    'selectedMismatch',mismatchMask(selectedCycle), ...
    'equationText',['Reset has priority; enabled registers capture ' ...
        'pre-edge inputs simultaneously; otherwise they hold.']);
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
        ~isnan(value) && ~isinf(value) && value == fix(value) && ...
        value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P03:InvalidBrokenCascade', ...
        'brokenCascade must be a logical scalar or numeric 0 or 1.');
end
end
