function run_checks
%RUN_CHECKS Execute independent P03 register-state and boundary checks.
clear model;

%% Baseline trace, reset priority, and capture behavior
expectedInput = [9 2 13 5 14 7 1 12 3 10 6 15 4 11 8 1].';
expectedOutput = [0 2 13 5 14 7 1 12 3 10 6 15 4 11 8 1].';
baseline = model(1,1,6,false);
assert(isequal(baseline.inputData,expectedInput) && ...
    isequal(baseline.output,expectedOutput), ...
    'P03:BaselineTrace','The deterministic one-register trace is incorrect.');
assert(baseline.reset(1) && baseline.captureEnable(1) && ...
    baseline.output(1) == 0 && baseline.inputData(1) == 9, ...
    'P03:ResetPriority','Reset must load zero even when enable is HIGH.');
assert(isequal(baseline.output(2:end),baseline.inputData(2:end)), ...
    'P03:EnabledCapture','An enabled one-stage register must capture D.');
assert(~baseline.outputValid(1) && all(baseline.outputValid(2:end)), ...
    'P03:BaselineValidity','Reset state is invalid; every later capture is valid.');
assert(baseline.captureCount == 15 && baseline.holdCount == 0 && ...
    baseline.firstValidCycle == 2, ...
    'P03:BaselineMetrics','Baseline edge metrics are incorrect.');

%% Hold behavior and simultaneous pre-edge transfer
periodThree = model(1,3,6,false);
heldEdges = ~periodThree.reset & ~periodThree.captureEnable;
assert(all(heldEdges == logical([0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1]).'), ...
    'P03:EnableSchedule','Period-three enable schedule changed.');
assert(isequal(periodThree.stateAfter(heldEdges,:), ...
    periodThree.stateBefore(heldEdges,:)), ...
    'P03:HoldInvariant','A disabled register must preserve its prior state.');
capturedEdges = periodThree.acceptedInput;
assert(isequal(periodThree.output(capturedEdges), ...
    periodThree.inputData(capturedEdges)), ...
    'P03:CaptureInvariant','Enabled one-stage captures must equal D.');

deep = model(4,1,6,false);
enabledEdges = deep.acceptedInput;
assert(isequal(deep.stateAfter(enabledEdges,2:end), ...
    deep.stateBefore(enabledEdges,1:end-1)), ...
    'P03:SimultaneousTransfer', ...
    'Each later stage must capture the previous stage pre-edge value.');
assert(all(deep.stateAfter(1,:) == 0) && ...
    all(~deep.validAfter(1,:)), ...
    'P03:ResetAllStages','Reset must clear value and validity in every stage.');

sparseDeep = model(3,3,8,false);
disabledDeepEdges = ~sparseDeep.reset & ~sparseDeep.captureEnable;
assert(isequal(sparseDeep.stateAfter(disabledDeepEdges,:), ...
        sparseDeep.stateBefore(disabledDeepEdges,:)) && ...
    isequal(sparseDeep.validAfter(disabledDeepEdges,:), ...
        sparseDeep.validBefore(disabledDeepEdges,:)), ...
    'P03:DeepHoldInvariant', ...
    'A disabled edge must hold every stage and every validity bit.');
assert(~any(sparseDeep.outputValid(1:7)) && ...
    sparseDeep.outputValid(8) && sparseDeep.output(8) == 2 && ...
    sparseDeep.firstValidCycle == 8 && ...
    sparseDeep.activeEdgeCount(8) == 3, ...
    'P03:EnabledEdgeLatency', ...
    'A three-stage token may advance only on three enabled edges.');

%% Sweep 1 limits - depth changes enabled-edge delay only
stageCounts = 1:4;
firstValidCycles = zeros(size(stageCounts));
additionalDelays = zeros(size(stageCounts));
storageBits = zeros(size(stageCounts));
for sweepIndex = 1:numel(stageCounts)
    stageCount = stageCounts(sweepIndex);
    current = model(stageCount,1,6,false);
    expectedDepthOutput = [zeros(stageCount,1); ...
        expectedInput(2:17-stageCount)];
    expectedValidity = [false(stageCount,1); true(16-stageCount,1)];
    assert(isequal(current.output,expectedDepthOutput) && ...
        isequal(current.outputValid,expectedValidity), ...
        'P03:DepthTrace','Depth %d produced the wrong delayed trace.',stageCount);
    assert(isequal(current.captureEnable,baseline.captureEnable) && ...
        current.captureCount == baseline.captureCount, ...
        'P03:DepthIsolation','Depth must not change the enable schedule.');
    firstValidCycles(sweepIndex) = current.firstValidCycle;
    additionalDelays(sweepIndex) = current.additionalActiveEdgeDelay;
    storageBits(sweepIndex) = current.dataStorageBitCount;
end
assert(isequal(firstValidCycles,[2 3 4 5]) && ...
    isequal(additionalDelays,[0 1 2 3]), ...
    'P03:DepthSweep','Depth sweep latency limits changed.');
assert(isequal(storageBits,[4 8 12 16]), ...
    'P03:StorageBound','Logical storage must remain 4 bits per stage.');

%% Sweep 2 limits - enable cadence changes captures and holds only
enablePeriods = 1:4;
expectedCaptures = [15 8 5 4];
expectedHolds = [0 7 10 11];
for sweepIndex = 1:numel(enablePeriods)
    current = model(1,enablePeriods(sweepIndex),6,false);
    assert(current.stageCount == 1 && current.dataStorageBitCount == 4, ...
        'P03:EnableIsolation','Enable sweep must keep one 4-bit register.');
    assert(current.captureCount == expectedCaptures(sweepIndex) && ...
        current.holdCount == expectedHolds(sweepIndex), ...
        'P03:EnableSweep','Enable capture/hold counts changed.');
    assert(current.captureCount + current.holdCount == 15, ...
        'P03:EdgeAccounting','Every non-reset edge must capture or hold.');
end
periodFour = model(1,4,6,false);
expectedPeriodFour = [0 2 2 2 2 7 7 7 7 10 10 10 10 11 11 11].';
assert(isequal(periodFour.output,expectedPeriodFour), ...
    'P03:EnableLimitTrace','Period-four hold trace is incorrect.');

%% Deliberately broken cascade and recognizable early-output symptom
healthyThree = model(3,1,6,false);
brokenThree = model(3,1,6,true);
assert(isequal(healthyThree.stateAfter(4,:),[5 13 2]), ...
    'P03:HealthyStageHistory','Healthy stages lost their prior-state ordering.');
assert(isequal(brokenThree.stateAfter(4,:),[5 5 5]), ...
    'P03:BrokenCascade','Broken stages must reuse the new value on one edge.');
assert(isequal(brokenThree.mismatchCycles,(2:16).') && ...
    brokenThree.mismatchCount == 15, ...
    'P03:BrokenMismatch','Broken output must differ on cycles 2 through 16.');
assert(isequal(find(brokenThree.earlyValidMask),(2:3).') && ...
    brokenThree.earlyValidCount == 2, ...
    'P03:EarlyOutput','Broken three-stage output must become valid two cycles early.');
assert(isequal(brokenThree.referenceOutput,healthyThree.output) && ...
    isequal(brokenThree.referenceOutputValid,healthyThree.outputValid), ...
    'P03:BrokenReference','Broken mode must retain the healthy reference trace.');
singleBroken = model(1,1,6,true);
assert(singleBroken.mismatchCount == 0 && singleBroken.earlyValidCount == 0, ...
    'P03:SingleStageLimit','A one-stage cascade has no later stage to corrupt.');

%% Malformed inputs, fixed resource bounds, recovery, and call isolation
assertRejects(@() model(0,1,6,false),'P03:InvalidStageCount');
assertRejects(@() model(5,1,6,false),'P03:InvalidStageCount');
assertRejects(@() model(2.5,1,6,false),'P03:InvalidStageCount');
assertRejects(@() model([1 2],1,6,false),'P03:InvalidStageCount');
assertRejects(@() model(NaN,1,6,false),'P03:InvalidStageCount');
assertRejects(@() model(1+1i,1,6,false),'P03:InvalidStageCount');
assertRejects(@() model(1,0,6,false),'P03:InvalidEnablePeriod');
assertRejects(@() model(1,5,6,false),'P03:InvalidEnablePeriod');
assertRejects(@() model(1,2.5,6,false),'P03:InvalidEnablePeriod');
assertRejects(@() model(1,[1 2],6,false),'P03:InvalidEnablePeriod');
assertRejects(@() model(1,NaN,6,false),'P03:InvalidEnablePeriod');
assertRejects(@() model(1,Inf,6,false),'P03:InvalidEnablePeriod');
assertRejects(@() model(1,1+1i,6,false),'P03:InvalidEnablePeriod');
assertRejects(@() model(1,1,0,false),'P03:InvalidSelectedCycle');
assertRejects(@() model(1,1,17,false),'P03:InvalidSelectedCycle');
assertRejects(@() model(1,1,2.5,false),'P03:InvalidSelectedCycle');
assertRejects(@() model(1,1,[1 2],false),'P03:InvalidSelectedCycle');
assertRejects(@() model(1,1,NaN,false),'P03:InvalidSelectedCycle');
assertRejects(@() model(1,1,Inf,false),'P03:InvalidSelectedCycle');
assertRejects(@() model(1,1,1+1i,false),'P03:InvalidSelectedCycle');
assertRejects(@() model(1,1,6,2),'P03:InvalidBrokenCascade');
assertRejects(@() model(1,1,6,NaN),'P03:InvalidBrokenCascade');
assertRejects(@() model(1,1,6,1+1i),'P03:InvalidBrokenCascade');
assertRejects(@() model(1,1,6,[false true]), ...
    'P03:InvalidBrokenCascade');
for stageCount = 1:4
    for enablePeriod = 1:4
        current = model(stageCount,enablePeriod,16,false);
        assert(isequal(size(current.stateAfter),[16 stageCount]) && ...
            isequal(size(current.validAfter),[16 stageCount]), ...
            'P03:ResourceBound','State allocation exceeded 16-by-stageCount.');
        assert(all(current.stateAfter(:) >= 0 & ...
            current.stateAfter(:) <= 15) && current.mismatchCount == 0, ...
            'P03:BoundedHealthyState','Healthy state must remain a 4-bit code.');
    end
end
baselineAfterFailure = model(1,1,6,false);
differentConfiguration = model(4,4,16,true); %#ok<NASGU>
baselineAfterOtherCall = model(1,1,6,false);
assert(isequaln(baseline,baselineAfterFailure) && ...
    isequaln(baseline,baselineAfterOtherCall), ...
    'P03:DeterminismRecovery', ...
    'Valid output must recover unchanged after failures and other calls.');

disp('P03 checks passed: state, depth, enable, limits, fault, validation, and recovery.');
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P03:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
