function out = model(sourceGapCycles,readyStallCycles,brokenAdvanceWithoutReady)
%MODEL Simulate a bounded valid/ready source and consumer handshake.
%   Signals and payload are observed immediately before each rising edge.
%   A transfer occurs only when valid and ready are both high at that edge.
%   The healthy producer holds valid, payload, and token identity while
%   stalled. The broken producer advances after an offer even without ready,
%   deliberately dropping payload tokens.

if nargin < 1
    sourceGapCycles = 1;
end
if nargin < 2
    readyStallCycles = 3;
end
if nargin < 3
    brokenAdvanceWithoutReady = false;
end

validateIntegerScalar(sourceGapCycles,0,3, ...
    'P09:InvalidSourceGapCycles','sourceGapCycles');
validateIntegerScalar(readyStallCycles,0,6, ...
    'P09:InvalidReadyStallCycles','readyStallCycles');
validateBooleanScalar(brokenAdvanceWithoutReady);
sourceGapCycles = double(sourceGapCycles);
readyStallCycles = double(readyStallCycles);
brokenAdvanceWithoutReady = logical(brokenAdvanceWithoutReady);

payloadAccumulatorBits = 12;
payloadModulus = 2^payloadAccumulatorBits;
payloadTuningWord = 411;
tokenCount = 8;
recordCycleCount = 35;
readyStallStartCycle = 5;
cycle = (1:recordCycleCount).';
tokenOrdinal = (0:tokenCount-1).';
tokenCodes = mod(tokenOrdinal*payloadTuningWord,payloadModulus);

ready = true(recordCycleCount,1);
if readyStallCycles > 0
    readyStallEndCycle = readyStallStartCycle+readyStallCycles-1;
    ready(readyStallStartCycle:readyStallEndCycle) = false;
else
    readyStallEndCycle = readyStallStartCycle-1;
end

reference = simulatePath(tokenCodes,sourceGapCycles,ready,false);
applied = simulatePath(tokenCodes,sourceGapCycles,ready, ...
    brokenAdvanceWithoutReady);

out = struct( ...
    'sourceGapCycles',sourceGapCycles, ...
    'readyStallCycles',readyStallCycles, ...
    'brokenAdvanceWithoutReady',brokenAdvanceWithoutReady, ...
    'payloadAccumulatorBits',payloadAccumulatorBits, ...
    'payloadModulus',payloadModulus, ...
    'payloadTuningWord',payloadTuningWord, ...
    'tokenCount',tokenCount, ...
    'recordCycleCount',recordCycleCount, ...
    'readyStallStartCycle',readyStallStartCycle, ...
    'readyStallEndCycle',readyStallEndCycle, ...
    'cycle',cycle, ...
    'tokenOrdinal',tokenOrdinal, ...
    'tokenCodes',tokenCodes, ...
    'ready',ready, ...
    'readyLowCycleCount',sum(~ready), ...
    'reference',reference, ...
    'applied',applied, ...
    'faultActive',brokenAdvanceWithoutReady && any(applied.dropEvent), ...
    'maxRecordCycles',recordCycleCount, ...
    'maxTokenCount',tokenCount, ...
    'modeledPayloadHoldBits',payloadAccumulatorBits, ...
    'equationText','transfer[n] = valid[n] && ready[n]', ...
    'holdRuleText',['if valid[n] && ~ready[n], then valid and data ' ...
        'remain stable for cycle n+1']);
end

function path = simulatePath(tokenCodes,sourceGapCycles,ready,brokenMode)
recordCycleCount = numel(ready);
tokenCount = numel(tokenCodes);
valid = false(recordCycleCount,1);
dataCode = NaN(recordCycleCount,1);
offeredTokenIndex = zeros(recordCycleCount,1);
transfer = false(recordCycleCount,1);
acceptedDataCodeByCycle = NaN(recordCycleCount,1);
acceptedTokenIndexByCycle = zeros(recordCycleCount,1);
dropEvent = false(recordCycleCount,1);
firstOfferCycle = NaN(tokenCount,1);
transferCycle = NaN(tokenCount,1);

currentTokenIndex = 1;
currentDataCode = tokenCodes(currentTokenIndex);
currentValid = true;
gapRemaining = 0;
sourceExhausted = false;

for cycleIndex = 1:recordCycleCount
    valid(cycleIndex) = currentValid;
    if currentValid
        dataCode(cycleIndex) = currentDataCode;
        offeredTokenIndex(cycleIndex) = currentTokenIndex;
        if isnan(firstOfferCycle(currentTokenIndex))
            firstOfferCycle(currentTokenIndex) = cycleIndex;
        end
    end

    transfer(cycleIndex) = currentValid && ready(cycleIndex);
    if transfer(cycleIndex)
        acceptedDataCodeByCycle(cycleIndex) = currentDataCode;
        acceptedTokenIndexByCycle(cycleIndex) = currentTokenIndex;
        transferCycle(currentTokenIndex) = cycleIndex;
        [currentTokenIndex,currentDataCode,currentValid,gapRemaining, ...
            sourceExhausted] = advanceToken(currentTokenIndex,tokenCodes, ...
            sourceGapCycles);
    elseif currentValid && ~ready(cycleIndex) && brokenMode
        dropEvent(cycleIndex) = true;
        [currentTokenIndex,currentDataCode,currentValid,gapRemaining, ...
            sourceExhausted] = advanceToken(currentTokenIndex,tokenCodes, ...
            sourceGapCycles);
    elseif ~currentValid && ~sourceExhausted
        if gapRemaining > 1
            gapRemaining = gapRemaining-1;
        elseif gapRemaining == 1
            gapRemaining = 0;
            currentValid = true;
        end
    end
end

holdViolation = false(recordCycleCount,1);
for cycleIndex = 2:recordCycleCount
    if valid(cycleIndex-1) && ~ready(cycleIndex-1)
        holdViolation(cycleIndex) = ~valid(cycleIndex) || ...
            offeredTokenIndex(cycleIndex) ~= ...
                offeredTokenIndex(cycleIndex-1) || ...
            dataCode(cycleIndex) ~= dataCode(cycleIndex-1);
    end
end

acceptedTokenIndices = acceptedTokenIndexByCycle(transfer);
acceptedDataCodes = acceptedDataCodeByCycle(transfer);
acceptedTokenCount = numel(acceptedTokenIndices);
lostTokenMask = true(tokenCount,1);
if ~isempty(acceptedTokenIndices)
    lostTokenMask(unique(acceptedTokenIndices)) = false;
end
lostTokenCount = sum(lostTokenMask);
duplicateTokenCount = acceptedTokenCount- ...
    numel(unique(acceptedTokenIndices));
outOfOrderCount = sum(diff(acceptedTokenIndices) <= 0);
completed = acceptedTokenCount == tokenCount && lostTokenCount == 0;
if completed
    completionCycle = find(transfer,1,'last');
    activeWindowCycleCount = completionCycle;
else
    completionCycle = NaN;
    activeWindowCycleCount = recordCycleCount;
end
activeWindowMask = (1:recordCycleCount).' <= activeWindowCycleCount;
waitCycles = transferCycle-firstOfferCycle;
observedWaitCycles = waitCycles(~isnan(waitCycles));
if isempty(observedWaitCycles)
    maximumWaitCycles = NaN;
    meanWaitCycles = NaN;
else
    maximumWaitCycles = max(observedWaitCycles);
    meanWaitCycles = mean(observedWaitCycles);
end

stalledValid = valid & ~ready;
readyWithoutValid = ~valid & ready;
neitherAsserted = ~valid & ~ready;
path = struct( ...
    'brokenMode',logical(brokenMode), ...
    'valid',valid, ...
    'dataCode',dataCode, ...
    'offeredTokenIndex',offeredTokenIndex, ...
    'ready',ready, ...
    'transfer',transfer, ...
    'stalledValid',stalledValid, ...
    'readyWithoutValid',readyWithoutValid, ...
    'neitherAsserted',neitherAsserted, ...
    'acceptedDataCodeByCycle',acceptedDataCodeByCycle, ...
    'acceptedTokenIndexByCycle',acceptedTokenIndexByCycle, ...
    'acceptedTokenIndices',acceptedTokenIndices, ...
    'acceptedDataCodes',acceptedDataCodes, ...
    'firstOfferCycle',firstOfferCycle, ...
    'transferCycle',transferCycle, ...
    'waitCycles',waitCycles, ...
    'dropEvent',dropEvent, ...
    'holdViolation',holdViolation, ...
    'acceptedTokenCount',acceptedTokenCount, ...
    'lostTokenMask',lostTokenMask, ...
    'lostTokenCount',lostTokenCount, ...
    'duplicateTokenCount',duplicateTokenCount, ...
    'outOfOrderCount',outOfOrderCount, ...
    'completed',completed, ...
    'completionCycle',completionCycle, ...
    'activeWindowCycleCount',activeWindowCycleCount, ...
    'activeWindowTransferRate',acceptedTokenCount/activeWindowCycleCount, ...
    'activeTransferCount',sum(transfer(activeWindowMask)), ...
    'activeStallCycleCount',sum(stalledValid(activeWindowMask)), ...
    'activeSourceBubbleCycleCount',sum(~valid(activeWindowMask)), ...
    'transferCount',sum(transfer), ...
    'stallCycleCount',sum(stalledValid), ...
    'readyWithoutValidCycleCount',sum(readyWithoutValid), ...
    'neitherAssertedCycleCount',sum(neitherAsserted), ...
    'dropCount',sum(dropEvent), ...
    'holdViolationCount',sum(holdViolation), ...
    'maximumWaitCycles',maximumWaitCycles, ...
    'meanWaitCycles',meanWaitCycles, ...
    'sourceExhausted',sourceExhausted, ...
    'traceCycleCount',recordCycleCount, ...
    'traceTokenCapacity',tokenCount);
end

function [nextTokenIndex,nextDataCode,nextValid,nextGapRemaining, ...
        sourceExhausted] = advanceToken(currentTokenIndex,tokenCodes, ...
        sourceGapCycles)
tokenCount = numel(tokenCodes);
if currentTokenIndex < tokenCount
    nextTokenIndex = currentTokenIndex+1;
    nextDataCode = tokenCodes(nextTokenIndex);
    if sourceGapCycles == 0
        nextValid = true;
        nextGapRemaining = 0;
    else
        nextValid = false;
        nextGapRemaining = sourceGapCycles;
    end
    sourceExhausted = false;
else
    nextTokenIndex = currentTokenIndex;
    nextDataCode = tokenCodes(currentTokenIndex);
    nextValid = false;
    nextGapRemaining = 0;
    sourceExhausted = true;
end
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && ~isnan(value) && ~isinf(value) && ...
        value == fix(value) && value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P09:InvalidBrokenAdvanceWithoutReady', ...
        'brokenAdvanceWithoutReady must be logical or numeric 0 or 1.');
end
end
