function run_checks
%RUN_CHECKS Verify valid/ready transfer, hold, bounds, and fault behavior.
clear model;

%% Exact baseline signals, payloads, waits, and active-window metrics
baseline = model(1,3,false);
expectedReady = true(35,1);
expectedReady(5:7) = false;
expectedValid = false(35,1);
expectedValid([1 3 5 6 7 8 10 12 14 16 18]) = true;
expectedTransfer = false(35,1);
expectedTransfer([1 3 8 10 12 14 16 18]) = true;
expectedDataCode = NaN(35,1);
expectedDataCode(1) = 0;
expectedDataCode(3) = 411;
expectedDataCode(5:8) = 822;
expectedDataCode(10) = 1233;
expectedDataCode(12) = 1644;
expectedDataCode(14) = 2055;
expectedDataCode(16) = 2466;
expectedDataCode(18) = 2877;
expectedTokenCodes = [0 411 822 1233 1644 2055 2466 2877].';
assert(baseline.sourceGapCycles == 1 && ...
    baseline.readyStallCycles == 3 && ...
    ~baseline.brokenAdvanceWithoutReady && ...
    baseline.recordCycleCount == 35 && baseline.tokenCount == 8 && ...
    isequal(baseline.cycle,(1:35).') && ...
    isequal(baseline.ready,expectedReady) && ...
    isequal(baseline.tokenCodes,expectedTokenCodes), ...
    'P09:BaselineShape', ...
    'Baseline inputs, ready schedule, payload list, or record shape changed.');
assert(isequal(baseline.reference.valid,expectedValid) && ...
    isequal(baseline.applied.valid,expectedValid) && ...
    isequal(baseline.reference.transfer,expectedTransfer) && ...
    isequal(baseline.applied.transfer,expectedTransfer) && ...
    isequaln(baseline.reference.dataCode,expectedDataCode) && ...
    isequaln(baseline.applied.dataCode,expectedDataCode), ...
    'P09:BaselineSignals', ...
    'Baseline valid, data, ready, or transfer trace changed.');
assert(isequal(baseline.applied.acceptedTokenIndices,(1:8).') && ...
    isequal(baseline.applied.acceptedDataCodes,expectedTokenCodes) && ...
    isequal(baseline.applied.firstOfferCycle, ...
        [1 3 5 10 12 14 16 18].') && ...
    isequal(baseline.applied.transferCycle, ...
        [1 3 8 10 12 14 16 18].') && ...
    isequal(baseline.applied.waitCycles,[0 0 3 0 0 0 0 0].'), ...
    'P09:BaselineTokenAccounting', ...
    'Baseline token order, offer cycles, transfer cycles, or waits changed.');
assert(baseline.applied.completed && ...
    baseline.applied.completionCycle == 18 && ...
    baseline.applied.activeWindowCycleCount == 18 && ...
    baseline.applied.activeTransferCount == 8 && ...
    baseline.applied.activeStallCycleCount == 3 && ...
    baseline.applied.activeSourceBubbleCycleCount == 7 && ...
    baseline.applied.activeWindowTransferRate == 8/18 && ...
    baseline.applied.maximumWaitCycles == 3 && ...
    baseline.applied.meanWaitCycles == 3/8 && ...
    baseline.applied.lostTokenCount == 0 && ...
    baseline.applied.duplicateTokenCount == 0 && ...
    baseline.applied.outOfOrderCount == 0 && ...
    baseline.applied.dropCount == 0 && ...
    baseline.applied.holdViolationCount == 0, ...
    'P09:BaselineMetrics', ...
    'Baseline completion, rate, wait, or integrity metric changed.');

%% Accepted numeric classes normalize to the same deterministic result
typedBaseline = model(uint8(1),uint8(3),uint8(0));
assert(isequaln(typedBaseline,baseline), ...
    'P09:NumericClassNormalization', ...
    'Accepted integer classes must normalize to the double/logical result.');

%% Transfer truth table and the stalled-successor hold obligation
truthCases = model(2,3,false);
assert(any(truthCases.applied.neitherAsserted) && ...
    any(truthCases.applied.readyWithoutValid) && ...
    any(truthCases.applied.stalledValid) && ...
    any(truthCases.applied.transfer), ...
    'P09:TruthTableCoverage', ...
    'One bounded trace must expose all four valid/ready combinations.');
for cycleIndex = 1:truthCases.recordCycleCount
    valid = truthCases.applied.valid(cycleIndex);
    ready = truthCases.ready(cycleIndex);
    categories = [truthCases.applied.neitherAsserted(cycleIndex), ...
        truthCases.applied.readyWithoutValid(cycleIndex), ...
        truthCases.applied.stalledValid(cycleIndex), ...
        truthCases.applied.transfer(cycleIndex)];
    assert(truthCases.applied.transfer(cycleIndex) == (valid && ready) && ...
        sum(categories) == 1, ...
        'P09:TransferTruthTable', ...
        'Exactly one handshake category must apply on every cycle.');
end
for cycleIndex = 2:truthCases.recordCycleCount
    if truthCases.applied.valid(cycleIndex-1) && ...
            ~truthCases.ready(cycleIndex-1)
        assert(truthCases.applied.valid(cycleIndex) && ...
            truthCases.applied.offeredTokenIndex(cycleIndex) == ...
                truthCases.applied.offeredTokenIndex(cycleIndex-1) && ...
            truthCases.applied.dataCode(cycleIndex) == ...
                truthCases.applied.dataCode(cycleIndex-1), ...
            'P09:HealthyHoldRule', ...
            'A healthy stalled offer must remain valid with stable data.');
    end
end
assert(all(~truthCases.applied.holdViolation), ...
    'P09:HealthyHoldDetector', ...
    'The healthy trace must contain no hold-rule violation.');

%% Sweep 1 - source gaps with readiness and payloads held fixed
sourceGapSweep = 0:3;
expectedGapCompletion = [8 15 22 29];
expectedGapBubbles = [0 7 14 21];
for sweepIndex = 1:numel(sourceGapSweep)
    sourceGapCycles = sourceGapSweep(sweepIndex);
    current = model(sourceGapCycles,0,false);
    assert(all(current.ready) && current.readyLowCycleCount == 0 && ...
        current.applied.completionCycle == ...
            expectedGapCompletion(sweepIndex) && ...
        current.applied.activeSourceBubbleCycleCount == ...
            expectedGapBubbles(sweepIndex) && ...
        current.applied.activeStallCycleCount == 0 && ...
        current.applied.activeWindowTransferRate == ...
            8/expectedGapCompletion(sweepIndex), ...
        'P09:SourceGapSweep', ...
        'Source-gap completion and bubble counts must follow 8+7*g.');
    assert(isequal(current.applied.acceptedTokenIndices,(1:8).') && ...
        isequal(current.applied.acceptedDataCodes,expectedTokenCodes) && ...
        current.applied.transferCount == 8 && ...
        current.applied.lostTokenCount == 0 && ...
        current.applied.holdViolationCount == 0 && ...
        current.recordCycleCount == 35, ...
        'P09:SourceGapSweepIsolation', ...
        'Source gaps must not change ready, payloads, order, or allocation.');
end

%% Sweep 2 - ready-low duration with continuous valid supply
readyStallSweep = 0:6;
for sweepIndex = 1:numel(readyStallSweep)
    readyStallCycles = readyStallSweep(sweepIndex);
    current = model(0,readyStallCycles,false);
    expectedReady = true(35,1);
    if readyStallCycles > 0
        expectedReady(5:4+readyStallCycles) = false;
    end
    assert(isequal(current.ready,expectedReady) && ...
        current.applied.completionCycle == 8+readyStallCycles && ...
        current.applied.activeStallCycleCount == readyStallCycles && ...
        current.applied.maximumWaitCycles == readyStallCycles && ...
        current.applied.activeSourceBubbleCycleCount == 0 && ...
        current.applied.activeWindowTransferRate == ...
            8/(8+readyStallCycles), ...
        'P09:ReadyStallSweep', ...
        'Ready-low duration must add one stall, wait, and completion cycle.');
    assert(isequal(current.applied.acceptedTokenIndices,(1:8).') && ...
        isequal(current.applied.acceptedDataCodes,expectedTokenCodes) && ...
        current.applied.transferCount == 8 && ...
        current.applied.lostTokenCount == 0 && ...
        current.applied.holdViolationCount == 0 && ...
        current.sourceGapCycles == 0, ...
        'P09:ReadyStallSweepIsolation', ...
        'Ready stalls must not change continuous source payloads or order.');
end

%% Combined controls - ready-low time matters only when valid overlaps it
readyLowDuringBubbles = model(2,2,false);
assert(isequal(find(readyLowDuringBubbles.applied.transfer), ...
        [1 4 7 10 13 16 19 22].') && ...
    all(readyLowDuringBubbles.applied.neitherAsserted(5:6)) && ...
    readyLowDuringBubbles.applied.activeStallCycleCount == 0 && ...
    readyLowDuringBubbles.applied.maximumWaitCycles == 0 && ...
    readyLowDuringBubbles.applied.completionCycle == 22 && ...
    readyLowDuringBubbles.applied.activeSourceBubbleCycleCount == 14, ...
    'P09:ReadyLowDuringSourceBubbles', ...
    ['Ready deassertion wholly inside source bubbles must not delay or ' ...
    'consume a token.']);
partialReadyOverlap = model(2,3,false);
assert(isequal(find(partialReadyOverlap.applied.transfer), ...
        [1 4 8 11 14 17 20 23].') && ...
    all(partialReadyOverlap.applied.neitherAsserted(5:6)) && ...
    partialReadyOverlap.applied.stalledValid(7) && ...
    partialReadyOverlap.applied.dataCode(7) == 822 && ...
    isequal(partialReadyOverlap.applied.waitCycles, ...
        [0 0 1 0 0 0 0 0].') && ...
    partialReadyOverlap.applied.activeStallCycleCount == 1 && ...
    partialReadyOverlap.applied.maximumWaitCycles == 1 && ...
    partialReadyOverlap.applied.completionCycle == 23 && ...
    partialReadyOverlap.applied.activeSourceBubbleCycleCount == 14 && ...
    isequal(partialReadyOverlap.applied.acceptedDataCodes, ...
        expectedTokenCodes), ...
    'P09:PartialReadySourceOverlap', ...
    ['Only the ready-low cycle that overlaps a valid offer may delay the ' ...
    'ordered token sequence.']);

%% Always-ready, longest-stall, sparse-source, and final-edge limits
alwaysReady = model(0,0,false);
assert(isequal(find(alwaysReady.applied.transfer),(1:8).') && ...
    all(alwaysReady.applied.valid(1:8)) && all(alwaysReady.ready) && ...
    alwaysReady.applied.completionCycle == 8 && ...
    alwaysReady.applied.activeWindowTransferRate == 1 && ...
    alwaysReady.applied.maximumWaitCycles == 0, ...
    'P09:AlwaysReadyLimit', ...
    'Continuous valid and ready must transfer one token on every edge.');
longestStall = model(0,6,false);
assert(isequal(find(longestStall.applied.transfer), ...
        [1 2 3 4 11 12 13 14].') && ...
    all(longestStall.applied.dataCode(5:11) == 1644) && ...
    longestStall.applied.completionCycle == 14 && ...
    longestStall.applied.maximumWaitCycles == 6, ...
    'P09:LongestStallLimit', ...
    'The longest ready stall must hold token 1644 through ready return.');
sparseSource = model(3,0,false);
assert(isequal(find(sparseSource.applied.transfer), ...
        [1 5 9 13 17 21 25 29].') && ...
    sparseSource.applied.readyWithoutValidCycleCount == 27 && ...
    sparseSource.applied.activeSourceBubbleCycleCount == 21 && ...
    sparseSource.applied.completionCycle == 29, ...
    'P09:SparseSourceLimit', ...
    'Early ready must not transfer in source bubbles.');
maximumBound = model(3,6,false);
assert(maximumBound.applied.completed && ...
    maximumBound.applied.completionCycle == 35 && ...
    maximumBound.applied.transfer(end) && ...
    maximumBound.applied.acceptedTokenIndexByCycle(end) == 8 && ...
    isequal(maximumBound.applied.acceptedDataCodes,expectedTokenCodes), ...
    'P09:FinalRecordEdgeLimit', ...
    'The maximum healthy controls must complete exactly at cycle 35.');

%% Deliberately broken advance-without-ready and exact loss symptom
healthy = model(0,3,false);
broken = model(0,3,true);
assert(isequal(find(healthy.reference.transfer), ...
        [1 2 3 4 8 9 10 11].') && ...
    isequal(healthy.reference.acceptedTokenIndices,(1:8).') && ...
    healthy.reference.completionCycle == 11 && ...
    healthy.reference.holdViolationCount == 0, ...
    'P09:BrokenReference', ...
    'Healthy reference must accept all tokens around the ready stall.');
assert(broken.brokenAdvanceWithoutReady && broken.faultActive && ...
    isequal(find(broken.applied.transfer),[1 2 3 4 8].') && ...
    isequal(broken.applied.acceptedTokenIndices,[1 2 3 4 8].') && ...
    isequal(broken.applied.acceptedDataCodes, ...
        expectedTokenCodes([1 2 3 4 8])) && ...
    isequal(find(broken.applied.dropEvent),[5 6 7].') && ...
    isequal(find(broken.applied.holdViolation),[6 7 8].') && ...
    isequal(find(broken.applied.lostTokenMask),[5 6 7].') && ...
    broken.applied.dropCount == 3 && ...
    broken.applied.holdViolationCount == 3 && ...
    broken.applied.lostTokenCount == 3 && ...
    broken.applied.duplicateTokenCount == 0 && ...
    broken.applied.outOfOrderCount == 0 && ...
    ~broken.applied.completed && isnan(broken.applied.completionCycle), ...
    'P09:BrokenAdvanceLoss', ...
    'Advancing without ready must drop tokens 5-7 and violate each hold.');
assert(isequaln(broken.reference,healthy.reference) && ...
    isequaln(broken.reference,healthy.applied), ...
    'P09:BrokenReferenceIsolation', ...
    'Broken mode must preserve the complete healthy reference path.');

%% Inert fault with no stalled-valid cycle and deterministic recovery
inertHealthy = model(0,0,false);
inertBroken = model(0,0,true);
assert(~inertBroken.faultActive && inertBroken.applied.dropCount == 0 && ...
    inertBroken.applied.holdViolationCount == 0 && ...
    isequal(inertBroken.applied.valid,inertHealthy.applied.valid) && ...
    isequaln(inertBroken.applied.dataCode,inertHealthy.applied.dataCode) && ...
    isequal(inertBroken.applied.transfer,inertHealthy.applied.transfer) && ...
    isequal(inertBroken.applied.acceptedDataCodes, ...
        inertHealthy.applied.acceptedDataCodes), ...
    'P09:BrokenInertLimit', ...
    'The fault must be inert when every valid offer is immediately ready.');

%% Complete bounded healthy/fault grid and fixed resource contract
for sourceGapCycles = 0:3
    for readyStallCycles = 0:6
        healthyGrid = model(sourceGapCycles,readyStallCycles,false);
        brokenGrid = model(sourceGapCycles,readyStallCycles,true);
        assert(healthyGrid.applied.completed && ...
            healthyGrid.applied.completionCycle <= 35 && ...
            isequal(healthyGrid.applied.acceptedTokenIndices,(1:8).') && ...
            isequal(healthyGrid.applied.acceptedDataCodes,expectedTokenCodes) && ...
            healthyGrid.applied.dropCount == 0 && ...
            healthyGrid.applied.holdViolationCount == 0, ...
            'P09:HealthyGrid', ...
            'Every bounded healthy control pair must deliver all tokens.');
        assert(isequaln(brokenGrid.reference,healthyGrid.reference) && ...
            isequaln(brokenGrid.reference,healthyGrid.applied) && ...
            isequal(brokenGrid.applied.transfer, ...
                brokenGrid.applied.valid & brokenGrid.ready) && ...
            brokenGrid.applied.acceptedTokenCount+ ...
                brokenGrid.applied.lostTokenCount == 8 && ...
            brokenGrid.applied.dropCount == ...
                brokenGrid.applied.lostTokenCount && ...
            brokenGrid.applied.duplicateTokenCount == 0 && ...
            brokenGrid.applied.outOfOrderCount == 0, ...
            'P09:BrokenGrid', ...
            'Broken grid must preserve reference and bounded token accounting.');
        assert(numel(healthyGrid.cycle) == 35 && ...
            numel(healthyGrid.ready) == 35 && ...
            numel(healthyGrid.applied.valid) == 35 && ...
            numel(healthyGrid.applied.dataCode) == 35 && ...
            numel(healthyGrid.applied.transfer) == 35 && ...
            numel(healthyGrid.applied.holdViolation) == 35 && ...
            numel(healthyGrid.tokenCodes) == 8 && ...
            numel(healthyGrid.applied.firstOfferCycle) == 8 && ...
            numel(healthyGrid.applied.transferCycle) == 8 && ...
            healthyGrid.maxRecordCycles == 35 && ...
            healthyGrid.maxTokenCount == 8 && ...
            healthyGrid.modeledPayloadHoldBits == 12 && ...
            healthyGrid.applied.traceCycleCount == 35 && ...
            healthyGrid.applied.traceTokenCapacity == 8, ...
            'P09:ResourceBound', ...
            'The fixed cycle, token, and modeled payload bounds changed.');
    end
end

%% Malformed inputs and post-failure/call-isolation recovery
assertRejects(@() model(-1,3,false),'P09:InvalidSourceGapCycles');
assertRejects(@() model(4,3,false),'P09:InvalidSourceGapCycles');
assertRejects(@() model(1.5,3,false),'P09:InvalidSourceGapCycles');
assertRejects(@() model([1 2],3,false),'P09:InvalidSourceGapCycles');
assertRejects(@() model(NaN,3,false),'P09:InvalidSourceGapCycles');
assertRejects(@() model(Inf,3,false),'P09:InvalidSourceGapCycles');
assertRejects(@() model(1+1i,3,false),'P09:InvalidSourceGapCycles');
assertRejects(@() model(true,3,false),'P09:InvalidSourceGapCycles');
assertRejects(@() model(1,-1,false),'P09:InvalidReadyStallCycles');
assertRejects(@() model(1,7,false),'P09:InvalidReadyStallCycles');
assertRejects(@() model(1,3.5,false),'P09:InvalidReadyStallCycles');
assertRejects(@() model(1,[3 4],false),'P09:InvalidReadyStallCycles');
assertRejects(@() model(1,NaN,false),'P09:InvalidReadyStallCycles');
assertRejects(@() model(1,Inf,false),'P09:InvalidReadyStallCycles');
assertRejects(@() model(1,3+1i,false),'P09:InvalidReadyStallCycles');
assertRejects(@() model(1,true,false),'P09:InvalidReadyStallCycles');
assertRejects(@() model(1,3,2), ...
    'P09:InvalidBrokenAdvanceWithoutReady');
assertRejects(@() model(1,3,0.5), ...
    'P09:InvalidBrokenAdvanceWithoutReady');
assertRejects(@() model(1,3,[false true]), ...
    'P09:InvalidBrokenAdvanceWithoutReady');
assertRejects(@() model(1,3,NaN), ...
    'P09:InvalidBrokenAdvanceWithoutReady');
assertRejects(@() model(1,3,Inf), ...
    'P09:InvalidBrokenAdvanceWithoutReady');
assertRejects(@() model(1,3,1+1i), ...
    'P09:InvalidBrokenAdvanceWithoutReady');
baselineAfterFailures = model(1,3,false);
maximumHealthyCall = model(3,6,false); %#ok<NASGU>
brokenCall = model(0,3,true); %#ok<NASGU>
baselineAfterOtherCalls = model(1,3,false);
assert(isequaln(baseline,baselineAfterFailures) && ...
    isequaln(baseline,baselineAfterOtherCalls), ...
    'P09:DeterminismRecovery', ...
    'Valid baseline output must recover after failures and unrelated calls.');

disp(['P09 checks passed: transfer truth table, stable holds, source and ' ...
    'ready sweeps, broken loss, validation, isolation, bounds, and recovery.']);
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P09:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
