function out = model(fractionBits,integerBits,selectedSample,brokenWrap)
%MODEL Quantize a deterministic vector with transparent signed fixed point.
%   integerBits excludes the sign bit. The healthy contract rounds to the
%   nearest code with ties away from zero, then saturates overflow. The
%   deliberately broken mode discards high-order overflow information and
%   wraps the rounded code into the available two's-complement code range.

if nargin < 1
    fractionBits = 3;
end
if nargin < 2
    integerBits = 2;
end
if nargin < 3
    selectedSample = 16;
end
if nargin < 4
    brokenWrap = false;
end

validateIntegerScalar(fractionBits,0,8, ...
    'P05:InvalidFractionBits','fractionBits');
validateIntegerScalar(integerBits,0,4, ...
    'P05:InvalidIntegerBits','integerBits');
validateIntegerScalar(selectedSample,1,25, ...
    'P05:InvalidSelectedSample','selectedSample');
validateBooleanScalar(brokenWrap);
fractionBits = double(fractionBits);
integerBits = double(integerBits);
selectedSample = double(selectedSample);
brokenWrap = logical(brokenWrap);

sampleIndex = (1:25).';
inputSignal = [-2.9 -2.1 -1.9375 -1.81 -1.49 -1.26 -1.00 ...
    -0.76 -0.51 -0.31 -0.1875 -0.0625 0 0.0625 0.1875 ...
    0.31 0.51 0.76 1.00 1.26 1.49 1.81 1.9375 2.1 2.9].';
sampleCount = numel(inputSignal);

signBits = 1;
wordLength = signBits + integerBits + fractionBits;
lsb = 2.^(-fractionBits);
halfLsb = lsb/2;
minCode = -2.^(wordLength-1);
maxCode = 2.^(wordLength-1)-1;
modeledCodeCount = 2.^wordLength;
rangeMinimum = minCode*lsb;
rangeMaximum = maxCode*lsb;

scaledInput = inputSignal/lsb;
roundedCode = sign(scaledInput).*floor(abs(scaledInput)+0.5);
referenceCode = min(max(roundedCode,minCode),maxCode);
wrappedCode = mod(roundedCode-minCode,modeledCodeCount)+minCode;
if brokenWrap
    quantizedCode = wrappedCode;
    overflowPolicy = 'broken wrap after discarding high-order bits';
else
    quantizedCode = referenceCode;
    overflowPolicy = 'saturate to the nearest endpoint';
end

quantizedSignal = quantizedCode*lsb;
referenceSignal = referenceCode*lsb;
quantizationError = quantizedSignal-inputSignal;
referenceError = referenceSignal-inputSignal;
overflowMask = roundedCode < minCode | roundedCode > maxCode;
inRangeMask = ~overflowMask;
mismatchMask = quantizedCode ~= referenceCode;
directionReversalMask = mismatchMask & quantizedSignal.*inputSignal < 0;

inRangeErrors = referenceError(inRangeMask);
rmsInRangeError = sqrt(mean(inRangeErrors.^2));
maxInRangeAbsError = max(abs(inRangeErrors));
overallRmsError = sqrt(mean(quantizationError.^2));
referenceOverallRmsError = sqrt(mean(referenceError.^2));

out = struct( ...
    'fractionBits',fractionBits, ...
    'integerBits',integerBits, ...
    'signBits',signBits, ...
    'wordLength',wordLength, ...
    'lsb',lsb, ...
    'halfLsb',halfLsb, ...
    'minCode',minCode, ...
    'maxCode',maxCode, ...
    'modeledCodeCount',modeledCodeCount, ...
    'rangeMinimum',rangeMinimum, ...
    'rangeMaximum',rangeMaximum, ...
    'sampleIndex',sampleIndex, ...
    'sampleCount',sampleCount, ...
    'inputSignal',inputSignal, ...
    'scaledInput',scaledInput, ...
    'roundedCode',roundedCode, ...
    'referenceCode',referenceCode, ...
    'wrappedCode',wrappedCode, ...
    'quantizedCode',quantizedCode, ...
    'referenceSignal',referenceSignal, ...
    'quantizedSignal',quantizedSignal, ...
    'referenceError',referenceError, ...
    'quantizationError',quantizationError, ...
    'overflowMask',overflowMask, ...
    'inRangeMask',inRangeMask, ...
    'overflowCount',sum(overflowMask), ...
    'lowOverflowCount',sum(roundedCode < minCode), ...
    'highOverflowCount',sum(roundedCode > maxCode), ...
    'mismatchMask',mismatchMask, ...
    'mismatchSamples',sampleIndex(mismatchMask), ...
    'mismatchCount',sum(mismatchMask), ...
    'directionReversalMask',directionReversalMask, ...
    'directionReversalCount',sum(directionReversalMask), ...
    'rmsInRangeError',rmsInRangeError, ...
    'maxInRangeAbsError',maxInRangeAbsError, ...
    'overallRmsError',overallRmsError, ...
    'referenceOverallRmsError',referenceOverallRmsError, ...
    'brokenWrap',brokenWrap, ...
    'overflowPolicy',overflowPolicy, ...
    'roundingPolicy','nearest code; exact half-LSB ties away from zero', ...
    'selectedSample',selectedSample, ...
    'selectedInput',inputSignal(selectedSample), ...
    'selectedScaledInput',scaledInput(selectedSample), ...
    'selectedRoundedCode',roundedCode(selectedSample), ...
    'selectedReferenceCode',referenceCode(selectedSample), ...
    'selectedCode',quantizedCode(selectedSample), ...
    'selectedReferenceOutput',referenceSignal(selectedSample), ...
    'selectedOutput',quantizedSignal(selectedSample), ...
    'selectedReferenceError',referenceError(selectedSample), ...
    'selectedError',quantizationError(selectedSample), ...
    'selectedOverflow',overflowMask(selectedSample), ...
    'selectedMismatch',mismatchMask(selectedSample), ...
    'equationText',['Delta = 2^{-F}; code = round(x/Delta); ' ...
        'xhat = Delta * clamp(code, codeMin, codeMax).']);
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
        ~isnan(value) && ~isinf(value) && value == fix(value) && ...
        value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P05:InvalidBrokenWrap', ...
        'brokenWrap must be a logical scalar or numeric 0 or 1.');
end
end
