function run_checks
%RUN_CHECKS Execute independent P05 fixed-point behavior and boundary checks.
clear model;

%% Baseline vector, code arithmetic, tie rule, and error bound
baseline = model(3,2,16,false);
expectedInput = [-2.9 -2.1 -1.9375 -1.81 -1.49 -1.26 -1.00 ...
    -0.76 -0.51 -0.31 -0.1875 -0.0625 0 0.0625 0.1875 ...
    0.31 0.51 0.76 1.00 1.26 1.49 1.81 1.9375 2.1 2.9].';
expectedRoundedCode = [-23 -17 -16 -14 -12 -10 -8 -6 -4 -2 ...
    -2 -1 0 1 2 2 4 6 8 10 12 14 16 17 23].';
expectedOutput = expectedRoundedCode/8;
assert(isequal(baseline.inputSignal,expectedInput) && ...
    isequal(baseline.sampleIndex,(1:25).'), ...
    'P05:BaselineVector','The deterministic input vector changed.');
assert(isequal(baseline.roundedCode,expectedRoundedCode) && ...
    isequal(baseline.quantizedCode,expectedRoundedCode) && ...
    isequal(baseline.quantizedSignal,expectedOutput), ...
    'P05:BaselineCodes','Baseline code arithmetic changed.');
assert(baseline.wordLength == 6 && baseline.lsb == 0.125 && ...
    baseline.halfLsb == 0.0625 && baseline.minCode == -32 && ...
    baseline.maxCode == 31 && baseline.modeledCodeCount == 64, ...
    'P05:BaselineFormat','Baseline bit weights or code bounds changed.');
assert(baseline.rangeMinimum == -4 && baseline.rangeMaximum == 3.875 && ...
    baseline.rangeMaximum == -baseline.rangeMinimum-baseline.lsb, ...
    'P05:EndpointAsymmetry', ...
    'Signed two''s-complement positive full scale must be one LSB lower.');
assert(baseline.roundedCode(12) == -1 && ...
    baseline.roundedCode(14) == 1 && ...
    baseline.quantizedSignal(12) == -0.125 && ...
    baseline.quantizedSignal(14) == 0.125, ...
    'P05:TiePolicy','Exact half-LSB ties must round away from zero.');
assert(baseline.overflowCount == 0 && baseline.mismatchCount == 0 && ...
    baseline.maxInRangeAbsError == baseline.halfLsb && ...
    all(abs(baseline.referenceError) <= baseline.halfLsb), ...
    'P05:HalfLsbBound', ...
    'Every overflow-free nearest-rounded error must stay within half an LSB.');
assert(baseline.selectedSample == 16 && baseline.selectedInput == 0.31 && ...
    baseline.selectedRoundedCode == 2 && baseline.selectedOutput == 0.25 && ...
    abs(baseline.selectedError+0.06) < 1e-12, ...
    'P05:SelectedBaseline','The selected baseline calculation changed.');
typedBaseline = model(uint8(3),int8(2),single(16),uint8(0));
assert(isequaln(typedBaseline,baseline), ...
    'P05:NumericClassNormalization', ...
    'Accepted numeric scalar classes must produce the double-input baseline.');

%% Sweep 1 limits - change only fractional bits
fractionalBitCounts = 0:8;
expectedLsbs = 2.^(-fractionalBitCounts);
expectedWordLengths = 3:11;
expectedMaxErrors = [0.49 0.24 0.10 0.0625 0.025 0.010 ...
    0.00625 0.0025 0.00171875];
observedLsbs = zeros(size(fractionalBitCounts));
observedWordLengths = zeros(size(fractionalBitCounts));
observedMaxErrors = zeros(size(fractionalBitCounts));
observedRmsErrors = zeros(size(fractionalBitCounts));
for sweepIndex = 1:numel(fractionalBitCounts)
    fractionBits = fractionalBitCounts(sweepIndex);
    current = model(fractionBits,2,13,false);
    assert(current.integerBits == 2 && ...
        current.rangeMinimum == -4 && current.overflowCount == 0 && ...
        isequal(current.inputSignal,expectedInput), ...
        'P05:PrecisionIsolation', ...
        'Fractional-bit sweep must keep integer allocation and input fixed.');
    assert(current.maxInRangeAbsError <= current.halfLsb+eps(current.halfLsb), ...
        'P05:PrecisionErrorBound', ...
        'Nearest-rounded in-range error exceeded half an LSB.');
    observedLsbs(sweepIndex) = current.lsb;
    observedWordLengths(sweepIndex) = current.wordLength;
    observedMaxErrors(sweepIndex) = current.maxInRangeAbsError;
    observedRmsErrors(sweepIndex) = current.rmsInRangeError;
end
assert(isequal(observedLsbs,expectedLsbs) && ...
    isequal(observedWordLengths,expectedWordLengths) && ...
    max(abs(observedMaxErrors-expectedMaxErrors)) < 1e-12 && ...
    all(diff(observedRmsErrors) < 0), ...
    'P05:PrecisionSweep', ...
    'Fractional-bit limits, word growth, or deterministic errors changed.');

%% Sweep 2 limits - change only integer-magnitude bits
integerBitCounts = 0:4;
expectedMinimums = -2.^integerBitCounts;
expectedMaximums = 2.^integerBitCounts-0.125;
expectedOverflowCounts = [13 5 0 0 0];
observedMinimums = zeros(size(integerBitCounts));
observedMaximums = zeros(size(integerBitCounts));
observedOverflowCounts = zeros(size(integerBitCounts));
for sweepIndex = 1:numel(integerBitCounts)
    integerBits = integerBitCounts(sweepIndex);
    current = model(3,integerBits,13,false);
    assert(current.fractionBits == 3 && current.lsb == 0.125 && ...
        isequal(current.inputSignal,expectedInput), ...
        'P05:RangeIsolation', ...
        'Integer-bit sweep must preserve fractional precision and input.');
    observedMinimums(sweepIndex) = current.rangeMinimum;
    observedMaximums(sweepIndex) = current.rangeMaximum;
    observedOverflowCounts(sweepIndex) = current.overflowCount;
    if integerBits >= 2
        assert(isequal(current.quantizedSignal,baseline.quantizedSignal), ...
            'P05:SufficientRangeLimit', ...
            'Extra unused integer range must not change quantized values.');
    end
end
assert(isequal(observedMinimums,expectedMinimums) && ...
    isequal(observedMaximums,expectedMaximums) && ...
    isequal(observedOverflowCounts,expectedOverflowCounts), ...
    'P05:RangeSweep','Integer-bit range or overload limits changed.');

%% Exhaustive healthy format grid and fixed resource bounds
for fractionBits = 0:8
    for integerBits = 0:4
        current = model(fractionBits,integerBits,25,false);
        expectedWordLength = 1+integerBits+fractionBits;
        expectedMinCode = -2.^(expectedWordLength-1);
        expectedMaxCode = 2.^(expectedWordLength-1)-1;
        assert(current.wordLength == expectedWordLength && ...
            current.modeledCodeCount == 2.^expectedWordLength && ...
            current.minCode == expectedMinCode && ...
            current.maxCode == expectedMaxCode && ...
            current.rangeMinimum == -2.^integerBits && ...
            current.rangeMaximum == 2.^integerBits-current.lsb, ...
            'P05:FormatGrid','Bit allocation no longer determines code bounds.');
        assert(isequal(size(current.inputSignal),[25 1]) && ...
            isequal(size(current.quantizedCode),[25 1]) && ...
            all(current.quantizedCode >= current.minCode) && ...
            all(current.quantizedCode <= current.maxCode) && ...
            all(current.quantizedCode == fix(current.quantizedCode)) && ...
            current.wordLength >= 1 && current.wordLength <= 13 && ...
            current.modeledCodeCount <= 8192, ...
            'P05:ResourceBound', ...
            'The fixed vector or bounded format allocation changed.');
        assert(current.mismatchCount == 0 && ...
            isequal(current.quantizedCode,current.referenceCode) && ...
            all(abs(current.referenceError(current.inRangeMask)) <= ...
                current.halfLsb+eps(current.halfLsb)), ...
            'P05:HealthyReference', ...
            'Healthy saturation must match its reference and in-range bound.');
    end
end

%% Deliberately broken wrap, recognizable symptom, and inert limit
healthyNarrow = model(3,1,25,false);
brokenNarrow = model(3,1,25,true);
expectedMismatchSamples = [1 2 23 24 25].';
expectedSaturatedOverloads = [-2 -2 1.875 1.875 1.875].';
expectedWrappedOverloads = [1.125 1.875 -2 -1.875 -1.125].';
assert(isequal(find(healthyNarrow.overflowMask),expectedMismatchSamples) && ...
    isequal(healthyNarrow.quantizedSignal(healthyNarrow.overflowMask), ...
        expectedSaturatedOverloads), ...
    'P05:SaturationLimits','Narrow-format saturation endpoints changed.');
assert(isequal(brokenNarrow.mismatchSamples,expectedMismatchSamples) && ...
    isequal(brokenNarrow.quantizedSignal(brokenNarrow.mismatchMask), ...
        expectedWrappedOverloads), ...
    'P05:BrokenWrap','Modulo wrap output changed at overloaded samples.');
assert(brokenNarrow.mismatchCount == 5 && ...
    brokenNarrow.directionReversalCount == 5 && ...
    all(brokenNarrow.mismatchMask <= brokenNarrow.overflowMask) && ...
    isequal(brokenNarrow.referenceSignal,healthyNarrow.quantizedSignal), ...
    'P05:BrokenSymptom', ...
    'Broken overflow must disagree only on five opposite-sign overloads.');
assert(isequal(brokenNarrow.quantizedSignal(~brokenNarrow.overflowMask), ...
    healthyNarrow.quantizedSignal(~healthyNarrow.overflowMask)), ...
    'P05:BrokenIsolation', ...
    'Wrap must leave every non-overflowing sample unchanged.');
brokenWide = model(3,2,16,true);
assert(brokenWide.overflowCount == 0 && brokenWide.mismatchCount == 0 && ...
    isequal(brokenWide.quantizedSignal,baseline.quantizedSignal), ...
    'P05:BrokenInertLimit', ...
    'Wrap and saturation must agree when every rounded code fits.');
for fractionBits = 0:8
    for integerBits = 0:4
        current = model(fractionBits,integerBits,13,true);
        assert(all(~current.mismatchMask | current.overflowMask) && ...
            all(current.quantizedCode >= current.minCode) && ...
            all(current.quantizedCode <= current.maxCode), ...
            'P05:WrappedGrid', ...
            'Wrapped mismatches must be overloaded and remain legal codes.');
    end
end

%% Malformed inputs, selected-view isolation, and deterministic recovery
assertRejects(@() model(-1,2,16,false),'P05:InvalidFractionBits');
assertRejects(@() model(9,2,16,false),'P05:InvalidFractionBits');
assertRejects(@() model(2.5,2,16,false),'P05:InvalidFractionBits');
assertRejects(@() model([2 3],2,16,false),'P05:InvalidFractionBits');
assertRejects(@() model(NaN,2,16,false),'P05:InvalidFractionBits');
assertRejects(@() model(Inf,2,16,false),'P05:InvalidFractionBits');
assertRejects(@() model(1+1i,2,16,false),'P05:InvalidFractionBits');
assertRejects(@() model(true,2,16,false),'P05:InvalidFractionBits');
assertRejects(@() model(3,-1,16,false),'P05:InvalidIntegerBits');
assertRejects(@() model(3,5,16,false),'P05:InvalidIntegerBits');
assertRejects(@() model(3,1.5,16,false),'P05:InvalidIntegerBits');
assertRejects(@() model(3,[1 2],16,false),'P05:InvalidIntegerBits');
assertRejects(@() model(3,NaN,16,false),'P05:InvalidIntegerBits');
assertRejects(@() model(3,Inf,16,false),'P05:InvalidIntegerBits');
assertRejects(@() model(3,1+1i,16,false),'P05:InvalidIntegerBits');
assertRejects(@() model(3,true,16,false),'P05:InvalidIntegerBits');
assertRejects(@() model(3,2,0,false),'P05:InvalidSelectedSample');
assertRejects(@() model(3,2,26,false),'P05:InvalidSelectedSample');
assertRejects(@() model(3,2,2.5,false),'P05:InvalidSelectedSample');
assertRejects(@() model(3,2,[2 3],false),'P05:InvalidSelectedSample');
assertRejects(@() model(3,2,NaN,false),'P05:InvalidSelectedSample');
assertRejects(@() model(3,2,Inf,false),'P05:InvalidSelectedSample');
assertRejects(@() model(3,2,1+1i,false),'P05:InvalidSelectedSample');
assertRejects(@() model(3,2,true,false),'P05:InvalidSelectedSample');
assertRejects(@() model(3,2,16,2),'P05:InvalidBrokenWrap');
assertRejects(@() model(3,2,16,0.5),'P05:InvalidBrokenWrap');
assertRejects(@() model(3,2,16,[false true]), ...
    'P05:InvalidBrokenWrap');
assertRejects(@() model(3,2,16,NaN),'P05:InvalidBrokenWrap');
assertRejects(@() model(3,2,16,Inf),'P05:InvalidBrokenWrap');
assertRejects(@() model(3,2,16,1+1i),'P05:InvalidBrokenWrap');

selectedFirst = model(3,2,1,false);
selectedLast = model(3,2,25,false);
assert(isequal(selectedFirst.inputSignal,selectedLast.inputSignal) && ...
    isequal(selectedFirst.roundedCode,selectedLast.roundedCode) && ...
    isequal(selectedFirst.quantizedSignal,selectedLast.quantizedSignal) && ...
    isequal(selectedFirst.quantizationError,selectedLast.quantizationError), ...
    'P05:SelectedViewIsolation', ...
    'Selecting a sample must not alter the deterministic calculation.');
baselineAfterFailure = model(3,2,16,false);
differentConfiguration = model(8,0,1,true); %#ok<NASGU>
baselineAfterOtherCall = model(3,2,16,false);
assert(isequaln(baseline,baselineAfterFailure) && ...
    isequaln(baseline,baselineAfterOtherCall), ...
    'P05:DeterminismRecovery', ...
    'Valid output must recover unchanged after failures and other calls.');

disp('P05 checks passed: codes, precision, range, overflow, validation, and recovery.');
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P05:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
