function interactive
%INTERACTIVE Explore FIFO backpressure and one broken producer rule.
clear model;
modelFcn = @model;
figureName = 'P10 Backpressure Without Loss Explorer';
delete(findall(groot,'Type','figure','Name',figureName));

fig = uifigure('Name',figureName,'Position',[70 70 1240 790]);
gridLayout = uigridlayout(fig,[4 4]);
gridLayout.RowHeight = {82,'1x',126,166};
gridLayout.ColumnWidth = {'1x','1x','1x','1x'};

instruction = uilabel(gridLayout,'WordWrap','on', ...
    'Text',['Read the depth-three, five-stall baseline first. Change FIFO ' ...
    'depth or consumer ready-low duration independently. Upstream enqueue ' ...
    'and downstream dequeue each require valid && ready on the same edge.']);
instruction.Layout.Row = 1;
instruction.Layout.Column = [1 4];

handshakeAxes = uiaxes(gridLayout);
handshakeAxes.Layout.Row = 2;
handshakeAxes.Layout.Column = [1 2];
occupancyAxes = uiaxes(gridLayout);
occupancyAxes.Layout.Row = 2;
occupancyAxes.Layout.Column = [3 4];

depthPanel = uipanel(gridLayout,'Title','Lever 1: FIFO depth');
depthPanel.Layout.Row = 3;
depthPanel.Layout.Column = 1;
depthGrid = uigridlayout(depthPanel,[2 1]);
depthGrid.RowHeight = {56,'1x'};
uilabel(depthGrid,'WordWrap','on', ...
    'Text','Stored-token capacity before ready propagates low.');
depthSpinner = uispinner(depthGrid,'Limits',[1 6], ...
    'RoundFractionalValues','on','Step',1,'Value',3, ...
    'Tooltip','Modeled FIFO capacity in tokens.');

stallPanel = uipanel(gridLayout,'Title','Lever 2: consumer stall');
stallPanel.Layout.Row = 3;
stallPanel.Layout.Column = 2;
stallGrid = uigridlayout(stallPanel,[2 1]);
stallGrid.RowHeight = {56,'1x'};
uilabel(stallGrid,'WordWrap','on', ...
    'Text','Consumer deasserts ready beginning at fixed cycle 5.');
stallSpinner = uispinner(stallGrid,'Limits',[0 8], ...
    'RoundFractionalValues','on','Step',1,'Value',5, ...
    'Tooltip','Consecutive downstream ready-low clock cycles.');

cyclePanel = uipanel(gridLayout,'Title','Observation cycle');
cyclePanel.Layout.Row = 3;
cyclePanel.Layout.Column = 3;
cycleGrid = uigridlayout(cyclePanel,[2 1]);
cycleGrid.RowHeight = {56,'1x'};
uilabel(cycleGrid,'WordWrap','on', ...
    'Text','Highlights one pre-edge handshake and post-edge occupancy.');
cycleSpinner = uispinner(cycleGrid,'Limits',[1 24], ...
    'RoundFractionalValues','on','Step',1,'Value',7, ...
    'Tooltip','Clock cycle to inspect in both linked views.');

faultPanel = uipanel(gridLayout,'Title','Deliberately broken case');
faultPanel.Layout.Row = 3;
faultPanel.Layout.Column = 4;
faultGrid = uigridlayout(faultPanel,[2 1]);
faultGrid.RowHeight = {60,'1x'};
uilabel(faultGrid,'WordWrap','on', ...
    'Text',['Enabled only when the healthy FIFO actually pauses the ' ...
    'source; otherwise ignoring backpressure is behaviorally inert.']);
faultCheckbox = uicheckbox(faultGrid, ...
    'Text','Advance source while ready is low','Value',false, ...
    'Tooltip','Violates the source hold obligation from P09.');

summary = uilabel(gridLayout,'WordWrap','on');
summary.Layout.Row = 4;
summary.Layout.Column = [1 4];

depthSpinner.ValueChangedFcn = @(~,~) updatePlots();
stallSpinner.ValueChangedFcn = @(~,~) updatePlots();
cycleSpinner.ValueChangedFcn = @(~,~) updatePlots();
faultCheckbox.ValueChangedFcn = @(~,~) updatePlots();
updatePlots();

    function updatePlots
        fifoDepth = round(depthSpinner.Value);
        consumerStallCycles = round(stallSpinner.Value);
        selectedCycle = round(cycleSpinner.Value);
        healthyProbe = modelFcn(fifoDepth,consumerStallCycles,false);
        if healthyProbe.reference.sourceStallCycleCount == 0
            faultCheckbox.Value = false;
            faultCheckbox.Enable = 'off';
        else
            faultCheckbox.Enable = 'on';
        end
        brokenMode = faultCheckbox.Value;
        out = modelFcn(fifoDepth,consumerStallCycles,brokenMode);

        cla(handshakeAxes);
        stairs(handshakeAxes,out.cycle, ...
            double(out.applied.sourceReady), ...
            'LineWidth',1.25,'DisplayName','source ready');
        hold(handshakeAxes,'on');
        stairs(handshakeAxes,out.cycle, ...
            2+double(out.applied.enqueue), ...
            'LineWidth',1.25,'DisplayName','enqueue');
        stairs(handshakeAxes,out.cycle, ...
            4+double(out.consumerReady), ...
            'LineWidth',1.25,'DisplayName','consumer ready');
        stairs(handshakeAxes,out.cycle, ...
            6+double(out.applied.dequeue), ...
            'LineWidth',1.25,'DisplayName','dequeue');
        xline(handshakeAxes,selectedCycle,':','Selected cycle', ...
            'LabelVerticalAlignment','bottom');
        hold(handshakeAxes,'off');
        grid(handshakeAxes,'on');
        xlabel(handshakeAxes,'Clock cycle [cycles]');
        ylabel(handshakeAxes, ...
            'Ready and transfer signals [binary, vertically offset]');
        title(handshakeAxes,'Upstream and downstream handshakes');
        handshakeAxes.YTick = [0.5 2.5 4.5 6.5];
        handshakeAxes.YTickLabel = ...
            {'source ready','enqueue','consumer ready','dequeue'};
        handshakeAxes.YLim = [-0.2 7.2];
        handshakeAxes.XLim = [1 out.recordCycleCount];

        cla(occupancyAxes);
        stairs(occupancyAxes,out.cycle, ...
            out.reference.occupancyAfter, ...
            'LineWidth',1.25,'DisplayName','healthy occupancy');
        hold(occupancyAxes,'on');
        stairs(occupancyAxes,out.cycle,out.applied.occupancyAfter,'--', ...
            'LineWidth',1.25,'DisplayName','applied occupancy');
        yline(occupancyAxes,out.fifoDepth,':','FIFO depth', ...
            'LabelVerticalAlignment','bottom');
        scatter(occupancyAxes,selectedCycle, ...
            out.applied.occupancyAfter(selectedCycle),48,'filled', ...
            'DisplayName','selected after-edge occupancy');
        xline(occupancyAxes,selectedCycle,':','Selected cycle', ...
            'LabelVerticalAlignment','bottom');
        hold(occupancyAxes,'off');
        grid(occupancyAxes,'on');
        xlabel(occupancyAxes,'Clock cycle [cycles]');
        ylabel(occupancyAxes,'Stored payloads after edge [tokens]');
        title(occupancyAxes,'FIFO conservation and capacity');
        occupancyAxes.XLim = [1 out.recordCycleCount];
        occupancyAxes.YLim = [0 out.maximumFifoDepth+1];
        legend(occupancyAxes,'Location','best');

        if out.applied.sourceValid(selectedCycle)
            sourcePayload = sprintf('token %d / code %g', ...
                out.applied.sourceTokenIndex(selectedCycle), ...
                out.applied.sourceDataCode(selectedCycle));
        else
            sourcePayload = 'none (source valid is low)';
        end
        if out.faultActive
            health = ['BROKEN: source advancement discarded at least one ' ...
                'token that the full FIFO did not accept'];
        elseif brokenMode
            health = ['inert fault selection: this schedule never presents ' ...
                'an advancing source on a ready-low edge'];
        else
            health = ['healthy: every source change follows enqueue and ' ...
                'every delivered token follows dequeue'];
        end
        summary.Text = sprintf([ ...
            'Cycle %d: source valid/ready/enqueue=%d/%d/%d, consumer ' ...
            'ready/output valid/dequeue=%d/%d/%d, occupancy before/after=' ...
            '%d/%d tokens, source offer=%s. Depth=%d tokens; consumer ' ...
            'ready low=%d cycles. Healthy completion/source stalls/peak=' ...
            '%g cycles/%d cycles/%d tokens; applied delivered/lost/drops/' ...
            'source-hold violations=%d/%d/%d/%d tokens or events. %s. ' ...
            'The 24-cycle trace, 12 payload labels, and six-slot maximum ' ...
            'are teaching-model bounds, not synthesized storage, achieved ' ...
            'timing, or measured throughput. %s.'], ...
            selectedCycle,out.applied.sourceValid(selectedCycle), ...
            out.applied.sourceReady(selectedCycle), ...
            out.applied.enqueue(selectedCycle), ...
            out.consumerReady(selectedCycle), ...
            out.applied.outputValid(selectedCycle), ...
            out.applied.dequeue(selectedCycle), ...
            out.applied.occupancyBefore(selectedCycle), ...
            out.applied.occupancyAfter(selectedCycle),sourcePayload, ...
            out.fifoDepth,out.consumerStallCycles, ...
            out.reference.completionCycle, ...
            out.reference.sourceStallCycleCount, ...
            out.reference.peakOccupancyTokens, ...
            out.applied.dequeuedTokenCount,out.applied.lostTokenCount, ...
            out.applied.dropCount, ...
            out.applied.sourceHoldViolationCount,health, ...
            out.occupancyEquationText);
        drawnow;
    end
end
