function out = model(fifoDepth,consumerStallCycles,brokenIgnoreBackpressure)
%MODEL Simulate bounded FIFO backpressure between one producer and consumer.
%   Signals are sampled immediately before each rising edge. The FIFO is
%   registered rather than fall-through: an input token stored on one edge
%   can first appear at the output on the next edge. A healthy producer holds
%   its offered token until the FIFO asserts ready and accepts it.

if nargin < 1
    fifoDepth = 3;
end
if nargin < 2
    consumerStallCycles = 5;
end
if nargin < 3
    brokenIgnoreBackpressure = false;
end

validateIntegerScalar(fifoDepth,1,6, ...
    'P10:InvalidFifoDepth','fifoDepth');
validateIntegerScalar(consumerStallCycles,0,8, ...
    'P10:InvalidConsumerStallCycles','consumerStallCycles');
validateBooleanScalar(brokenIgnoreBackpressure);
fifoDepth = double(fifoDepth);
consumerStallCycles = double(consumerStallCycles);
brokenIgnoreBackpressure = logical(brokenIgnoreBackpressure);

payloadAccumulatorBits = 12;
payloadModulus = 2^payloadAccumulatorBits;
payloadTuningWord = 411;
tokenCount = 12;
recordCycleCount = 24;
maximumFifoDepth = 6;
consumerStallStartCycle = 5;
cycle = (1:recordCycleCount).';
tokenOrdinal = (0:tokenCount-1).';
tokenCodes = mod(tokenOrdinal*payloadTuningWord,payloadModulus);

consumerReady = true(recordCycleCount,1);
if consumerStallCycles > 0
    consumerStallEndCycle = ...
        consumerStallStartCycle+consumerStallCycles-1;
    consumerReady(consumerStallStartCycle:consumerStallEndCycle) = false;
else
    consumerStallEndCycle = consumerStallStartCycle-1;
end

reference = simulatePath(tokenCodes,fifoDepth,consumerReady,false, ...
    maximumFifoDepth);
applied = simulatePath(tokenCodes,fifoDepth,consumerReady, ...
    brokenIgnoreBackpressure,maximumFifoDepth);

out = struct( ...
    'fifoDepth',fifoDepth, ...
    'consumerStallCycles',consumerStallCycles, ...
    'brokenIgnoreBackpressure',brokenIgnoreBackpressure, ...
    'payloadAccumulatorBits',payloadAccumulatorBits, ...
    'payloadModulus',payloadModulus, ...
    'payloadTuningWord',payloadTuningWord, ...
    'tokenCount',tokenCount, ...
    'recordCycleCount',recordCycleCount, ...
    'maximumFifoDepth',maximumFifoDepth, ...
    'consumerStallStartCycle',consumerStallStartCycle, ...
    'consumerStallEndCycle',consumerStallEndCycle, ...
    'cycle',cycle, ...
    'tokenOrdinal',tokenOrdinal, ...
    'tokenCodes',tokenCodes, ...
    'consumerReady',consumerReady, ...
    'reference',reference, ...
    'applied',applied, ...
    'faultActive',brokenIgnoreBackpressure && any(applied.dropAttempt), ...
    'maxRecordCycles',recordCycleCount, ...
    'maxTokenCount',tokenCount, ...
    'maxFifoStorageSlots',maximumFifoDepth, ...
    'modeledPayloadBits',payloadAccumulatorBits, ...
    'inputEquationText', ...
        'enqueue[n] = sourceValid[n] && sourceReady[n]', ...
    'outputEquationText', ...
        'dequeue[n] = outputValid[n] && consumerReady[n]', ...
    'readyEquationText', ...
        'sourceReady[n] = (q[n] < D) || dequeue[n]', ...
    'occupancyEquationText', ...
        'q[n+1] = q[n] + enqueue[n] - dequeue[n]', ...
    'holdRuleText', ...
        ['if valid[n] && ~ready[n], valid and payload stay stable ' ...
        'until an accepting edge']);
end

function path = simulatePath(tokenCodes,fifoDepth,consumerReady, ...
        brokenMode,maximumFifoDepth)
recordCycleCount = numel(consumerReady);
tokenCount = numel(tokenCodes);

occupancyBefore = zeros(recordCycleCount,1);
occupancyAfter = zeros(recordCycleCount,1);
sourceValid = false(recordCycleCount,1);
sourceReady = false(recordCycleCount,1);
sourceDataCode = NaN(recordCycleCount,1);
sourceTokenIndex = zeros(recordCycleCount,1);
enqueue = false(recordCycleCount,1);
sourceAdvance = false(recordCycleCount,1);
sourcePaused = false(recordCycleCount,1);
dropAttempt = false(recordCycleCount,1);
outputValid = false(recordCycleCount,1);
outputDataCode = NaN(recordCycleCount,1);
outputTokenIndex = zeros(recordCycleCount,1);
dequeue = false(recordCycleCount,1);
dequeuedDataCodeByCycle = NaN(recordCycleCount,1);
dequeuedTokenIndexByCycle = zeros(recordCycleCount,1);
enqueueCycle = NaN(tokenCount,1);
dequeueCycle = NaN(tokenCount,1);
firstOfferCycle = NaN(tokenCount,1);

queueTokenIndices = zeros(maximumFifoDepth,1);
queueCount = 0;
currentSourceTokenIndex = 1;

for cycleIndex = 1:recordCycleCount
    occupancyBefore(cycleIndex) = queueCount;
    outputValid(cycleIndex) = queueCount > 0;
    if outputValid(cycleIndex)
        outputTokenIndex(cycleIndex) = queueTokenIndices(1);
        outputDataCode(cycleIndex) = ...
            tokenCodes(outputTokenIndex(cycleIndex));
    end
    dequeue(cycleIndex) = outputValid(cycleIndex) && ...
        consumerReady(cycleIndex);

    sourceValid(cycleIndex) = currentSourceTokenIndex <= tokenCount;
    if sourceValid(cycleIndex)
        sourceTokenIndex(cycleIndex) = currentSourceTokenIndex;
        sourceDataCode(cycleIndex) = tokenCodes(currentSourceTokenIndex);
        if isnan(firstOfferCycle(currentSourceTokenIndex))
            firstOfferCycle(currentSourceTokenIndex) = cycleIndex;
        end
    end
    sourceReady(cycleIndex) = queueCount < fifoDepth || ...
        dequeue(cycleIndex);
    enqueue(cycleIndex) = sourceValid(cycleIndex) && ...
        sourceReady(cycleIndex);
    sourcePaused(cycleIndex) = sourceValid(cycleIndex) && ...
        ~sourceReady(cycleIndex);
    dropAttempt(cycleIndex) = sourcePaused(cycleIndex) && brokenMode;

    if dequeue(cycleIndex)
        dequeuedTokenIndex = queueTokenIndices(1);
        dequeuedTokenIndexByCycle(cycleIndex) = dequeuedTokenIndex;
        dequeuedDataCodeByCycle(cycleIndex) = ...
            tokenCodes(dequeuedTokenIndex);
        dequeueCycle(dequeuedTokenIndex) = cycleIndex;
        if queueCount > 1
            queueTokenIndices(1:queueCount-1) = ...
                queueTokenIndices(2:queueCount);
        end
        queueTokenIndices(queueCount) = 0;
        queueCount = queueCount-1;
    end

    if enqueue(cycleIndex)
        queueCount = queueCount+1;
        queueTokenIndices(queueCount) = currentSourceTokenIndex;
        enqueueCycle(currentSourceTokenIndex) = cycleIndex;
    end

    sourceAdvance(cycleIndex) = enqueue(cycleIndex) || ...
        (brokenMode && sourceValid(cycleIndex));
    if sourceAdvance(cycleIndex)
        currentSourceTokenIndex = currentSourceTokenIndex+1;
    end
    occupancyAfter(cycleIndex) = queueCount;
end

sourceHoldViolation = false(recordCycleCount,1);
outputHoldViolation = false(recordCycleCount,1);
for cycleIndex = 2:recordCycleCount
    if sourceValid(cycleIndex-1) && ~sourceReady(cycleIndex-1)
        sourceHoldViolation(cycleIndex) = ...
            ~sourceValid(cycleIndex) || ...
            sourceTokenIndex(cycleIndex) ~= ...
                sourceTokenIndex(cycleIndex-1) || ...
            sourceDataCode(cycleIndex) ~= sourceDataCode(cycleIndex-1);
    end
    if outputValid(cycleIndex-1) && ~consumerReady(cycleIndex-1)
        outputHoldViolation(cycleIndex) = ...
            ~outputValid(cycleIndex) || ...
            outputTokenIndex(cycleIndex) ~= ...
                outputTokenIndex(cycleIndex-1) || ...
            outputDataCode(cycleIndex) ~= outputDataCode(cycleIndex-1);
    end
end

enqueuedTokenIndices = sourceTokenIndex(enqueue);
enqueuedDataCodes = sourceDataCode(enqueue);
dequeuedTokenIndices = dequeuedTokenIndexByCycle(dequeue);
dequeuedDataCodes = dequeuedDataCodeByCycle(dequeue);
lostTokenMask = true(tokenCount,1);
if ~isempty(dequeuedTokenIndices)
    lostTokenMask(unique(dequeuedTokenIndices)) = false;
end
lostTokenCount = sum(lostTokenMask);
duplicateTokenCount = numel(dequeuedTokenIndices)- ...
    numel(unique(dequeuedTokenIndices));
outOfOrderCount = sum(diff(dequeuedTokenIndices) <= 0);
completed = numel(dequeuedTokenIndices) == tokenCount && ...
    lostTokenCount == 0 && occupancyAfter(end) == 0;
if completed
    completionCycle = find(dequeue,1,'last');
else
    completionCycle = NaN;
end
if any(dequeue)
    drainCycle = find(dequeue,1,'last');
else
    drainCycle = NaN;
end

sourceWaitCycles = enqueueCycle-firstOfferCycle;
observedSourceWaits = sourceWaitCycles(~isnan(sourceWaitCycles));
fifoResidenceCycles = dequeueCycle-enqueueCycle;
observedResidence = fifoResidenceCycles(~isnan(fifoResidenceCycles));
if isempty(observedSourceWaits)
    maximumSourceWaitCycles = NaN;
else
    maximumSourceWaitCycles = max(observedSourceWaits);
end
if isempty(observedResidence)
    maximumFifoResidenceCycles = NaN;
    minimumFifoResidenceCycles = NaN;
else
    maximumFifoResidenceCycles = max(observedResidence);
    minimumFifoResidenceCycles = min(observedResidence);
end

fullReplacement = occupancyBefore == fifoDepth & enqueue & dequeue;
recurrenceResidual = occupancyAfter-occupancyBefore- ...
    double(enqueue)+double(dequeue);
finalConservationResidual = sum(enqueue)-sum(dequeue)- ...
    occupancyAfter(end);
if completed
    activeWindowCycleCount = completionCycle;
else
    activeWindowCycleCount = recordCycleCount;
end

path = struct( ...
    'brokenMode',logical(brokenMode), ...
    'occupancyBefore',occupancyBefore, ...
    'occupancyAfter',occupancyAfter, ...
    'sourceValid',sourceValid, ...
    'sourceReady',sourceReady, ...
    'sourceDataCode',sourceDataCode, ...
    'sourceTokenIndex',sourceTokenIndex, ...
    'enqueue',enqueue, ...
    'sourceAdvance',sourceAdvance, ...
    'sourcePaused',sourcePaused, ...
    'dropAttempt',dropAttempt, ...
    'sourceHoldViolation',sourceHoldViolation, ...
    'outputValid',outputValid, ...
    'consumerReady',consumerReady, ...
    'outputDataCode',outputDataCode, ...
    'outputTokenIndex',outputTokenIndex, ...
    'dequeue',dequeue, ...
    'dequeuedDataCodeByCycle',dequeuedDataCodeByCycle, ...
    'dequeuedTokenIndexByCycle',dequeuedTokenIndexByCycle, ...
    'outputHoldViolation',outputHoldViolation, ...
    'enqueuedTokenIndices',enqueuedTokenIndices, ...
    'enqueuedDataCodes',enqueuedDataCodes, ...
    'dequeuedTokenIndices',dequeuedTokenIndices, ...
    'dequeuedDataCodes',dequeuedDataCodes, ...
    'firstOfferCycle',firstOfferCycle, ...
    'enqueueCycle',enqueueCycle, ...
    'dequeueCycle',dequeueCycle, ...
    'sourceWaitCycles',sourceWaitCycles, ...
    'fifoResidenceCycles',fifoResidenceCycles, ...
    'lostTokenMask',lostTokenMask, ...
    'fullReplacement',fullReplacement, ...
    'recurrenceResidual',recurrenceResidual, ...
    'finalConservationResidual',finalConservationResidual, ...
    'enqueuedTokenCount',sum(enqueue), ...
    'dequeuedTokenCount',sum(dequeue), ...
    'sourceStallCycleCount',sum(sourcePaused), ...
    'dropCount',sum(dropAttempt), ...
    'sourceHoldViolationCount',sum(sourceHoldViolation), ...
    'outputHoldViolationCount',sum(outputHoldViolation), ...
    'lostTokenCount',lostTokenCount, ...
    'duplicateTokenCount',duplicateTokenCount, ...
    'outOfOrderCount',outOfOrderCount, ...
    'peakOccupancyTokens',max(occupancyAfter), ...
    'fullReplacementCount',sum(fullReplacement), ...
    'maximumSourceWaitCycles',maximumSourceWaitCycles, ...
    'maximumFifoResidenceCycles',maximumFifoResidenceCycles, ...
    'minimumFifoResidenceCycles',minimumFifoResidenceCycles, ...
    'completed',completed, ...
    'completionCycle',completionCycle, ...
    'drainCycle',drainCycle, ...
    'activeWindowCycleCount',activeWindowCycleCount, ...
    'activeWindowTransferRate',sum(dequeue)/activeWindowCycleCount, ...
    'sourceExhausted',currentSourceTokenIndex > tokenCount, ...
    'traceCycleCount',recordCycleCount, ...
    'traceTokenCapacity',tokenCount, ...
    'traceFifoCapacity',maximumFifoDepth);
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && ~isnan(value) && ~isinf(value) && ...
        value == fix(value) && value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P10:InvalidBrokenIgnoreBackpressure', ...
        'brokenIgnoreBackpressure must be logical or numeric 0 or 1.');
end
end
