function run_checks
%RUN_CHECKS Verify FIFO handshakes, conservation, limits, and fault behavior.
clear model;

%% Exact baseline handshakes, occupancy, order, and latency
baseline = model(3,5,false);
expectedTokenCodes = ...
    [0 411 822 1233 1644 2055 2466 2877 3288 3699 14 425].';
expectedConsumerReady = true(24,1);
expectedConsumerReady(5:9) = false;
expectedEnqueue = false(24,1);
expectedEnqueue([1:6 10:15]) = true;
expectedDequeue = false(24,1);
expectedDequeue([2:4 10:18]) = true;
expectedSourcePaused = false(24,1);
expectedSourcePaused(7:9) = true;
expectedOccupancyBefore = ...
    [0 1 1 1 1 2 3 3 3 3 3 3 3 3 3 3 2 1 zeros(1,6)].';
expectedOccupancyAfter = ...
    [1 1 1 1 2 3 3 3 3 3 3 3 3 3 3 2 1 zeros(1,7)].';
assert(baseline.fifoDepth == 3 && ...
    baseline.consumerStallCycles == 5 && ...
    ~baseline.brokenIgnoreBackpressure && ...
    baseline.tokenCount == 12 && baseline.recordCycleCount == 24 && ...
    isequal(baseline.cycle,(1:24).') && ...
    isequal(baseline.tokenCodes,expectedTokenCodes) && ...
    isequal(baseline.consumerReady,expectedConsumerReady), ...
    'P10:BaselineShape', ...
    'Baseline inputs, payloads, readiness, or record shape changed.');
assert(isequal(baseline.applied.enqueue,expectedEnqueue) && ...
    isequal(baseline.applied.dequeue,expectedDequeue) && ...
    isequal(baseline.applied.sourcePaused,expectedSourcePaused) && ...
    isequal(baseline.applied.occupancyBefore, ...
        expectedOccupancyBefore) && ...
    isequal(baseline.applied.occupancyAfter, ...
        expectedOccupancyAfter), ...
    'P10:BaselineSignals', ...
    'Baseline enqueue, dequeue, backpressure, or occupancy changed.');
assert(isequal(baseline.applied.enqueuedTokenIndices,(1:12).') && ...
    isequal(baseline.applied.dequeuedTokenIndices,(1:12).') && ...
    isequal(baseline.applied.enqueuedDataCodes,expectedTokenCodes) && ...
    isequal(baseline.applied.dequeuedDataCodes,expectedTokenCodes) && ...
    isequal(baseline.applied.enqueueCycle, ...
        [1 2 3 4 5 6 10 11 12 13 14 15].') && ...
    isequal(baseline.applied.dequeueCycle, ...
        [2 3 4 10 11 12 13 14 15 16 17 18].'), ...
    'P10:BaselineTokenAccounting', ...
    'Baseline token order or enqueue/dequeue cycle changed.');
assert(baseline.applied.completed && ...
    baseline.applied.completionCycle == 18 && ...
    baseline.applied.peakOccupancyTokens == 3 && ...
    baseline.applied.sourceStallCycleCount == 3 && ...
    baseline.applied.maximumSourceWaitCycles == 3 && ...
    baseline.applied.maximumFifoResidenceCycles == 6 && ...
    baseline.applied.minimumFifoResidenceCycles == 1 && ...
    baseline.applied.activeWindowTransferRate == 12/18 && ...
    baseline.applied.lostTokenCount == 0 && ...
    baseline.applied.duplicateTokenCount == 0 && ...
    baseline.applied.outOfOrderCount == 0, ...
    'P10:BaselineMetrics', ...
    'Baseline completion, occupancy, wait, residence, or integrity changed.');
assert(isequal(find(~baseline.applied.sourceReady),(7:9).') && ...
    all(baseline.applied.sourceValid(7:9)) && ...
    all(~baseline.applied.enqueue(7:9)) && ...
    all(baseline.applied.sourceTokenIndex(7:9) == 7), ...
    'P10:BaselineReadyPropagation', ...
    'Only the full-FIFO interval may backpressure the held source token.');

%% Accepted numeric classes normalize to the same deterministic result
typedBaseline = model(uint8(3),uint8(5),uint8(0));
assert(isequaln(typedBaseline,baseline), ...
    'P10:NumericClassNormalization', ...
    'Accepted integer classes must normalize to the double/logical result.');

%% Both handshakes, the occupancy recurrence, and both hold obligations
for cycleIndex = 1:baseline.recordCycleCount
    path = baseline.applied;
    assert(path.outputValid(cycleIndex) == ...
            (path.occupancyBefore(cycleIndex) > 0) && ...
        path.dequeue(cycleIndex) == ...
            (path.outputValid(cycleIndex) && ...
            baseline.consumerReady(cycleIndex)) && ...
        path.sourceReady(cycleIndex) == ...
            (path.occupancyBefore(cycleIndex) < baseline.fifoDepth || ...
            path.dequeue(cycleIndex)) && ...
        path.enqueue(cycleIndex) == ...
            (path.sourceValid(cycleIndex) && ...
            path.sourceReady(cycleIndex)), ...
        'P10:HandshakeEquations', ...
        'Input and output transfers must each require valid and ready.');
    assert(path.occupancyAfter(cycleIndex) == ...
            path.occupancyBefore(cycleIndex)+ ...
            path.enqueue(cycleIndex)-path.dequeue(cycleIndex) && ...
        path.occupancyBefore(cycleIndex) >= 0 && ...
        path.occupancyBefore(cycleIndex) <= baseline.fifoDepth && ...
        path.occupancyAfter(cycleIndex) >= 0 && ...
        path.occupancyAfter(cycleIndex) <= baseline.fifoDepth && ...
        path.recurrenceResidual(cycleIndex) == 0, ...
        'P10:OccupancyRecurrence', ...
        'FIFO occupancy must conserve enqueue minus dequeue within bounds.');
end
assert(all(~baseline.applied.sourceHoldViolation) && ...
    all(~baseline.applied.outputHoldViolation), ...
    'P10:HealthyHoldRules', ...
    'Both healthy stalled interfaces must retain valid and payload identity.');
assert(baseline.applied.finalConservationResidual == 0 && ...
    baseline.applied.enqueuedTokenCount == 12 && ...
    baseline.applied.dequeuedTokenCount == 12 && ...
    baseline.applied.occupancyAfter(end) == 0, ...
    'P10:HealthyConservation', ...
    'Enqueued tokens must equal dequeued tokens plus final occupancy.');

%% Registered FIFO and simultaneous full replacement limits
assert(baseline.applied.enqueueCycle(1) == 1 && ...
    baseline.applied.dequeueCycle(1) == 2 && ...
    baseline.applied.minimumFifoResidenceCycles == 1 && ...
    ~baseline.applied.outputValid(1), ...
    'P10:RegisteredNoFallThrough', ...
    'A token stored on cycle 1 may first leave on cycle 2.');
assert(isequal(find(baseline.applied.fullReplacement),(10:15).') && ...
    all(baseline.applied.occupancyBefore(10:15) == 3) && ...
    all(baseline.applied.occupancyAfter(10:15) == 3) && ...
    all(baseline.applied.enqueue(10:15)) && ...
    all(baseline.applied.dequeue(10:15)), ...
    'P10:FullReplacementLimit', ...
    'A full FIFO may dequeue and enqueue together without a bubble.');
assert(all(baseline.applied.outputTokenIndex(5:10) == 4) && ...
    all(baseline.applied.outputDataCode(5:10) == 1233) && ...
    all(baseline.applied.sourceTokenIndex(7:10) == 7) && ...
    all(baseline.applied.sourceDataCode(7:10) == 2466), ...
    'P10:StablePayloadLimits', ...
    'Both sides must hold the exact token owed through their stalls.');

%% Sweep 1 - consumer stall duration at fixed depth three
consumerStallSweep = 0:8;
expectedCompletion = 13:21;
expectedSourceStalls = [0 0 0 1 2 3 4 5 6];
expectedPeakOccupancy = [1 2 3 3 3 3 3 3 3];
for sweepIndex = 1:numel(consumerStallSweep)
    stallCycles = consumerStallSweep(sweepIndex);
    current = model(3,stallCycles,false);
    assert(current.applied.completionCycle == ...
            expectedCompletion(sweepIndex) && ...
        current.applied.sourceStallCycleCount == ...
            expectedSourceStalls(sweepIndex) && ...
        current.applied.peakOccupancyTokens == ...
            expectedPeakOccupancy(sweepIndex), ...
        'P10:ConsumerStallSweep', ...
        'Consumer stall must follow the exact completion/fill relation.');
    assert(current.fifoDepth == 3 && ...
        isequal(current.tokenCodes,expectedTokenCodes) && ...
        isequal(current.applied.dequeuedTokenIndices,(1:12).') && ...
        current.applied.dequeuedTokenCount == 12 && ...
        current.applied.lostTokenCount == 0 && ...
        current.applied.finalConservationResidual == 0 && ...
        current.recordCycleCount == 24, ...
        'P10:ConsumerStallSweepIsolation', ...
        'Stall sweep must preserve depth, payloads, order, and allocation.');
end

%% Sweep 2 - FIFO depth at fixed five-cycle consumer stall
fifoDepthSweep = 1:6;
expectedDepthStalls = [5 4 3 2 1 0];
for sweepIndex = 1:numel(fifoDepthSweep)
    fifoDepth = fifoDepthSweep(sweepIndex);
    current = model(fifoDepth,5,false);
    assert(current.applied.sourceStallCycleCount == ...
            expectedDepthStalls(sweepIndex) && ...
        current.applied.peakOccupancyTokens == fifoDepth && ...
        current.applied.completionCycle == 18, ...
        'P10:FifoDepthSweep', ...
        'Each added slot must absorb one more arrival before backpressure.');
    assert(current.consumerStallCycles == 5 && ...
        isequal(current.consumerReady,expectedConsumerReady) && ...
        isequal(current.tokenCodes,expectedTokenCodes) && ...
        isequal(current.applied.dequeuedTokenIndices,(1:12).') && ...
        current.applied.dequeuedTokenCount == 12 && ...
        current.applied.lostTokenCount == 0 && ...
        current.applied.finalConservationResidual == 0, ...
        'P10:FifoDepthSweepIsolation', ...
        'Depth sweep must preserve readiness, payloads, order, and delivery.');
end

%% Combined controls - capacity absorbs stalls only through its last free slot
capacityAbsorbs = model(4,3,false);
capacityAbsorbsFault = model(4,3,true);
assert(isempty(find(capacityAbsorbs.applied.sourcePaused,1)) && ...
    isequal(find(capacityAbsorbs.applied.enqueue),(1:12).') && ...
    isequal(find(capacityAbsorbs.applied.dequeue), ...
        [2 3 4 8 9 10 11 12 13 14 15 16].') && ...
    capacityAbsorbs.applied.peakOccupancyTokens == 4 && ...
    capacityAbsorbs.applied.completionCycle == 16 && ...
    ~capacityAbsorbsFault.faultActive && ...
    capacityAbsorbsFault.applied.brokenMode && ...
    ~capacityAbsorbs.applied.brokenMode && ...
    isequaln(rmfield(capacityAbsorbsFault.applied,'brokenMode'), ...
        rmfield(capacityAbsorbs.applied,'brokenMode')), ...
    'P10:CombinedCapacityAbsorbs', ...
    ['At depth four, three ready-low edges must fill the three free slots ' ...
    'without pausing the source or activating the ignored-ready fault.']);
backpressurePropagates = model(4,4,false);
assert(isequal(find(backpressurePropagates.applied.sourcePaused),8) && ...
    isequal(find(backpressurePropagates.applied.enqueue), ...
        [1 2 3 4 5 6 7 9 10 11 12 13].') && ...
    isequal(find(backpressurePropagates.applied.dequeue), ...
        [2 3 4 9 10 11 12 13 14 15 16 17].') && ...
    all(backpressurePropagates.applied.sourceTokenIndex(8:9) == 8) && ...
    backpressurePropagates.applied.maximumSourceWaitCycles == 1 && ...
    backpressurePropagates.applied.peakOccupancyTokens == 4 && ...
    backpressurePropagates.applied.completionCycle == 17 && ...
    isequal(backpressurePropagates.applied.dequeuedTokenIndices,(1:12).'), ...
    'P10:CombinedBackpressurePropagates', ...
    ['The fourth ready-low edge must exceed three free slots, pause token ' ...
    'eight once, and delay completion by exactly one cycle.']);
backpressurePropagatesFault = model(4,4,true);
assert(backpressurePropagatesFault.faultActive && ...
    isequaln(backpressurePropagatesFault.reference, ...
        backpressurePropagates.applied) && ...
    isequal(find(backpressurePropagatesFault.applied.dropAttempt),8) && ...
    isequal(find( ...
        backpressurePropagatesFault.applied.sourceHoldViolation),9) && ...
    isequal(find(backpressurePropagatesFault.applied.lostTokenMask),8) && ...
    isequal(backpressurePropagatesFault.applied.dequeuedTokenIndices, ...
        [1 2 3 4 5 6 7 9 10 11 12].') && ...
    backpressurePropagatesFault.applied.dropCount == 1 && ...
    max(backpressurePropagatesFault.applied.occupancyAfter) == 4 && ...
    ~backpressurePropagatesFault.applied.completed, ...
    'P10:CombinedFaultBoundary', ...
    ['One stall beyond the available capacity must activate the broken ' ...
    'producer and lose exactly the unaccepted eighth token.']);

%% Depth-one, no-stall, no-backpressure, and maximum-control limits
depthOneNoStall = model(1,0,false);
assert(isequal(find(depthOneNoStall.applied.enqueue),(1:12).') && ...
    isequal(find(depthOneNoStall.applied.dequeue),(2:13).') && ...
    depthOneNoStall.applied.peakOccupancyTokens == 1 && ...
    depthOneNoStall.applied.sourceStallCycleCount == 0 && ...
    depthOneNoStall.applied.completionCycle == 13, ...
    'P10:DepthOneNoStallLimit', ...
    'A depth-one registered FIFO must sustain one replacement per edge.');
depthOneLongestStall = model(1,8,false);
assert(isequal(find(depthOneLongestStall.applied.sourcePaused),(5:12).') && ...
    depthOneLongestStall.applied.sourceStallCycleCount == 8 && ...
    depthOneLongestStall.applied.peakOccupancyTokens == 1 && ...
    depthOneLongestStall.applied.completionCycle == 21 && ...
    depthOneLongestStall.applied.lostTokenCount == 0, ...
    'P10:DepthOneLongestStallLimit', ...
    'Depth one must hold one token and propagate the full longest stall.');
noBackpressure = model(6,5,false);
assert(noBackpressure.applied.sourceStallCycleCount == 0 && ...
    noBackpressure.applied.peakOccupancyTokens == 6 && ...
    noBackpressure.applied.completionCycle == 18 && ...
    isequal(noBackpressure.applied.dequeuedTokenIndices,(1:12).'), ...
    'P10:NoBackpressureLimit', ...
    'Six slots must absorb this five-cycle stall without pausing source.');
maximumControls = model(6,8,false);
assert(maximumControls.applied.completed && ...
    maximumControls.applied.peakOccupancyTokens == 6 && ...
    maximumControls.applied.sourceStallCycleCount == 3 && ...
    maximumControls.applied.completionCycle == 21 && ...
    maximumControls.applied.lostTokenCount == 0, ...
    'P10:MaximumControlLimit', ...
    'Maximum controls must still drain every token within the fixed record.');

%% Deliberately broken producer ignores propagated backpressure
healthy = model(3,5,false);
broken = model(3,5,true);
assert(broken.brokenIgnoreBackpressure && broken.faultActive && ...
    isequal(find(broken.applied.dropAttempt),[7 8 9].') && ...
    isequal(find(broken.applied.sourceHoldViolation),[8 9 10].') && ...
    isequal(find(broken.applied.lostTokenMask),[7 8 9].') && ...
    isequal(broken.applied.dequeuedTokenIndices, ...
        [1 2 3 4 5 6 10 11 12].') && ...
    isequal(broken.applied.dequeuedDataCodes, ...
        expectedTokenCodes([1:6 10:12])) && ...
    isequal(find(broken.applied.dequeue), ...
        [2 3 4 10 11 12 13 14 15].') && ...
    broken.applied.dropCount == 3 && ...
    broken.applied.lostTokenCount == 3 && ...
    broken.applied.sourceHoldViolationCount == 3 && ...
    broken.applied.outputHoldViolationCount == 0 && ...
    ~broken.applied.completed && isnan(broken.applied.completionCycle), ...
    'P10:BrokenIgnoredBackpressure', ...
    'Ignoring ready must lose token indices 7-9 with exact hold symptoms.');
assert(isequaln(broken.reference,healthy.reference) && ...
    isequaln(broken.reference,healthy.applied), ...
    'P10:BrokenReferenceIsolation', ...
    'Broken mode must preserve the complete healthy reference path.');
assert(max(broken.applied.occupancyAfter) <= broken.fifoDepth && ...
    all(broken.applied.recurrenceResidual == 0) && ...
    broken.applied.finalConservationResidual == 0 && ...
    broken.applied.occupancyAfter(end) == 0, ...
    'P10:BrokenStorageBound', ...
    'The source-side fault must not create an out-of-bounds FIFO write.');

%% Inert fault when the healthy path never backpressures the source
inertNoStall = model(3,0,true);
healthyNoStall = model(3,0,false);
inertDeep = model(6,5,true);
healthyDeep = model(6,5,false);
assert(~inertNoStall.faultActive && ...
    inertNoStall.applied.brokenMode && ...
    ~healthyNoStall.applied.brokenMode && ...
    isequaln(rmfield(inertNoStall.applied,'brokenMode'), ...
        rmfield(healthyNoStall.applied,'brokenMode')) && ...
    ~inertDeep.faultActive && ...
    inertDeep.applied.brokenMode && ...
    ~healthyDeep.applied.brokenMode && ...
    isequaln(rmfield(inertDeep.applied,'brokenMode'), ...
        rmfield(healthyDeep.applied,'brokenMode')), ...
    'P10:BrokenInertLimit', ...
    ['Ignoring ready must change only the selected-mode metadata when ready ' ...
    'never falls for a valid offer.']);

%% Complete bounded healthy/fault grid and fixed resource contract
for fifoDepth = 1:6
    for consumerStallCycles = 0:8
        healthyGrid = model(fifoDepth,consumerStallCycles,false);
        brokenGrid = model(fifoDepth,consumerStallCycles,true);
        assert(healthyGrid.applied.completed && ...
            healthyGrid.applied.completionCycle <= 21 && ...
            isequal(healthyGrid.applied.enqueuedTokenIndices,(1:12).') && ...
            isequal(healthyGrid.applied.dequeuedTokenIndices,(1:12).') && ...
            healthyGrid.applied.lostTokenCount == 0 && ...
            healthyGrid.applied.duplicateTokenCount == 0 && ...
            healthyGrid.applied.outOfOrderCount == 0 && ...
            all(healthyGrid.applied.recurrenceResidual == 0), ...
            'P10:HealthyGrid', ...
            'Every bounded healthy control pair must conserve all tokens.');
        assert(isequaln(brokenGrid.reference,healthyGrid.applied) && ...
            brokenGrid.applied.dequeuedTokenCount+ ...
                brokenGrid.applied.lostTokenCount == 12 && ...
            brokenGrid.applied.dropCount == ...
                brokenGrid.applied.lostTokenCount && ...
            brokenGrid.applied.duplicateTokenCount == 0 && ...
            brokenGrid.applied.outOfOrderCount == 0 && ...
            brokenGrid.applied.outputHoldViolationCount == 0 && ...
            all(brokenGrid.applied.recurrenceResidual == 0) && ...
            brokenGrid.applied.occupancyAfter(end) == 0, ...
            'P10:BrokenGrid', ...
            'Broken grid must preserve reference, order, and bounded storage.');
        assert(numel(healthyGrid.cycle) == 24 && ...
            numel(healthyGrid.consumerReady) == 24 && ...
            numel(healthyGrid.applied.occupancyBefore) == 24 && ...
            numel(healthyGrid.applied.sourceDataCode) == 24 && ...
            numel(healthyGrid.applied.outputDataCode) == 24 && ...
            numel(healthyGrid.tokenCodes) == 12 && ...
            healthyGrid.maxRecordCycles == 24 && ...
            healthyGrid.maxTokenCount == 12 && ...
            healthyGrid.maxFifoStorageSlots == 6 && ...
            healthyGrid.modeledPayloadBits == 12 && ...
            healthyGrid.applied.traceCycleCount == 24 && ...
            healthyGrid.applied.traceTokenCapacity == 12 && ...
            healthyGrid.applied.traceFifoCapacity == 6 && ...
            max(healthyGrid.applied.occupancyAfter) <= fifoDepth, ...
            'P10:ResourceBound', ...
            'Fixed trace, token, payload, and maximum FIFO bounds changed.');
    end
end

%% Malformed inputs and post-failure/call-isolation recovery
assertRejects(@() model(0,5,false),'P10:InvalidFifoDepth');
assertRejects(@() model(7,5,false),'P10:InvalidFifoDepth');
assertRejects(@() model(2.5,5,false),'P10:InvalidFifoDepth');
assertRejects(@() model([2 3],5,false),'P10:InvalidFifoDepth');
assertRejects(@() model(NaN,5,false),'P10:InvalidFifoDepth');
assertRejects(@() model(Inf,5,false),'P10:InvalidFifoDepth');
assertRejects(@() model(3+1i,5,false),'P10:InvalidFifoDepth');
assertRejects(@() model(true,5,false),'P10:InvalidFifoDepth');
assertRejects(@() model(3,-1,false), ...
    'P10:InvalidConsumerStallCycles');
assertRejects(@() model(3,9,false), ...
    'P10:InvalidConsumerStallCycles');
assertRejects(@() model(3,4.5,false), ...
    'P10:InvalidConsumerStallCycles');
assertRejects(@() model(3,[4 5],false), ...
    'P10:InvalidConsumerStallCycles');
assertRejects(@() model(3,NaN,false), ...
    'P10:InvalidConsumerStallCycles');
assertRejects(@() model(3,Inf,false), ...
    'P10:InvalidConsumerStallCycles');
assertRejects(@() model(3,5+1i,false), ...
    'P10:InvalidConsumerStallCycles');
assertRejects(@() model(3,true,false), ...
    'P10:InvalidConsumerStallCycles');
assertRejects(@() model(3,5,2), ...
    'P10:InvalidBrokenIgnoreBackpressure');
assertRejects(@() model(3,5,0.5), ...
    'P10:InvalidBrokenIgnoreBackpressure');
assertRejects(@() model(3,5,[false true]), ...
    'P10:InvalidBrokenIgnoreBackpressure');
assertRejects(@() model(3,5,NaN), ...
    'P10:InvalidBrokenIgnoreBackpressure');
assertRejects(@() model(3,5,Inf), ...
    'P10:InvalidBrokenIgnoreBackpressure');
assertRejects(@() model(3,5,1+1i), ...
    'P10:InvalidBrokenIgnoreBackpressure');
baselineAfterFailures = model(3,5,false);
maximumHealthyCall = model(6,8,false); %#ok<NASGU>
brokenCall = model(3,5,true); %#ok<NASGU>
baselineAfterOtherCalls = model(3,5,false);
assert(isequaln(baseline,baselineAfterFailures) && ...
    isequaln(baseline,baselineAfterOtherCalls), ...
    'P10:DeterminismRecovery', ...
    'Baseline must recover after failures and unrelated bounded calls.');

disp(['P10 checks passed: both handshakes, FIFO conservation, two ' ...
    'sweeps, broken loss, validation, isolation, bounds, and recovery.']);
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P10:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
