function out = model(pipelineStages,inputPeriod,selectedCycle,brokenValidAlignment)
%MODEL Move deterministic fixed-point products through a MAC pipeline.
%   Each operand uses W=4, one integer-magnitude bit (sign excluded), and
%   two fractional bits, so every raw product
%   code has four fractional bits. A healthy pipeline delays product data,
%   token identity, and valid together before the accumulator. The broken
%   mode bypasses the valid and token delay while product data still moves
%   through the requested registers.

if nargin < 1
    pipelineStages = 2;
end
if nargin < 2
    inputPeriod = 1;
end
if nargin < 3
    selectedCycle = 5;
end
if nargin < 4
    brokenValidAlignment = false;
end

validateIntegerScalar(pipelineStages,0,4, ...
    'P06:InvalidPipelineStages','pipelineStages');
validateIntegerScalar(inputPeriod,1,4, ...
    'P06:InvalidInputPeriod','inputPeriod');
validateBooleanScalar(brokenValidAlignment);
pipelineStages = double(pipelineStages);
inputPeriod = double(inputPeriod);
brokenValidAlignment = logical(brokenValidAlignment);

inputCodeSequence = [3 -2 5 1 -4 6 -1 4].';
coefficientCodeSequence = [2 4 -1 3 2 -2 5 5].';
sampleCount = numel(inputCodeSequence);
operandFractionBits = 2;
operandIntegerBits = 1;
operandWordLength = 1+operandIntegerBits+operandFractionBits;
productCodeWordLength = 2*operandWordLength;
productFractionBits = 2*operandFractionBits;
operandLsb = 2.^(-operandFractionBits);
productLsb = 2.^(-productFractionBits);
productCodeSequence = inputCodeSequence.*coefficientCodeSequence;
productValueSequence = productCodeSequence*productLsb;
sampleIndex = (1:sampleCount).';

lastInputCycle = 1+(sampleCount-1)*inputPeriod;
totalCycles = lastInputCycle+pipelineStages;
maxCycleCount = 1+(sampleCount-1)*4+4;
validateIntegerScalar(selectedCycle,1,totalCycles, ...
    'P06:InvalidSelectedCycle','selectedCycle');
selectedCycle = double(selectedCycle);
cycle = (1:totalCycles).';

inputValid = mod(cycle-1,inputPeriod) == 0 & cycle <= lastInputCycle;
inputTokenIndex = zeros(totalCycles,1);
inputTokenIndex(inputValid) = (cycle(inputValid)-1)/inputPeriod+1;
bubbleInputCode = 7;
bubbleCoefficientCode = -8;
bubbleProductCode = bubbleInputCode*bubbleCoefficientCode;
inputCode = repmat(bubbleInputCode,totalCycles,1);
coefficientCode = repmat(bubbleCoefficientCode,totalCycles,1);
inputProductCode = repmat(bubbleProductCode,totalCycles,1);
inputCode(inputValid) = inputCodeSequence(inputTokenIndex(inputValid));
coefficientCode(inputValid) = ...
    coefficientCodeSequence(inputTokenIndex(inputValid));
inputProductCode(inputValid) = ...
    productCodeSequence(inputTokenIndex(inputValid));
inputProductValue = inputProductCode*productLsb;

productStageBefore = zeros(totalCycles,pipelineStages);
productStageAfter = zeros(totalCycles,pipelineStages);
validStageBefore = false(totalCycles,pipelineStages);
validStageAfter = false(totalCycles,pipelineStages);
tokenStageBefore = zeros(totalCycles,pipelineStages);
tokenStageAfter = zeros(totalCycles,pipelineStages);
referenceAccumulatorProductCode = zeros(totalCycles,1);
referenceAccumulatorValid = false(totalCycles,1);
referenceAccumulatorTokenIndex = zeros(totalCycles,1);

previousProduct = zeros(1,pipelineStages);
previousValid = false(1,pipelineStages);
previousToken = zeros(1,pipelineStages);
for cycleIndex = 1:totalCycles
    if pipelineStages == 0
        referenceAccumulatorProductCode(cycleIndex) = ...
            inputProductCode(cycleIndex);
        referenceAccumulatorValid(cycleIndex) = inputValid(cycleIndex);
        referenceAccumulatorTokenIndex(cycleIndex) = ...
            inputTokenIndex(cycleIndex);
    else
        productStageBefore(cycleIndex,:) = previousProduct;
        validStageBefore(cycleIndex,:) = previousValid;
        tokenStageBefore(cycleIndex,:) = previousToken;
        referenceAccumulatorProductCode(cycleIndex) = previousProduct(end);
        referenceAccumulatorValid(cycleIndex) = previousValid(end);
        referenceAccumulatorTokenIndex(cycleIndex) = previousToken(end);

        nextProduct = previousProduct;
        nextValid = previousValid;
        nextToken = previousToken;
        nextProduct(1) = inputProductCode(cycleIndex);
        nextValid(1) = inputValid(cycleIndex);
        nextToken(1) = inputTokenIndex(cycleIndex);
        for stageIndex = 2:pipelineStages
            nextProduct(stageIndex) = previousProduct(stageIndex-1);
            nextValid(stageIndex) = previousValid(stageIndex-1);
            nextToken(stageIndex) = previousToken(stageIndex-1);
        end
        productStageAfter(cycleIndex,:) = nextProduct;
        validStageAfter(cycleIndex,:) = nextValid;
        tokenStageAfter(cycleIndex,:) = nextToken;
        previousProduct = nextProduct;
        previousValid = nextValid;
        previousToken = nextToken;
    end
end

if brokenValidAlignment
    accumulatorValid = inputValid;
    accumulatorValidTokenIndex = inputTokenIndex;
    alignmentPolicy = 'broken: valid and token bypass the product registers';
else
    accumulatorValid = referenceAccumulatorValid;
    accumulatorValidTokenIndex = referenceAccumulatorTokenIndex;
    alignmentPolicy = 'healthy: product, valid, and token use equal delay';
end
accumulatorProductCode = referenceAccumulatorProductCode;
accumulatorProductValue = accumulatorProductCode*productLsb;

runningSumCode = zeros(totalCycles,1);
referenceRunningSumCode = zeros(totalCycles,1);
actualCode = 0;
referenceCode = 0;
seenTokenMask = false(sampleCount,1);
for cycleIndex = 1:totalCycles
    if accumulatorValid(cycleIndex)
        actualCode = actualCode+accumulatorProductCode(cycleIndex);
        dataToken = referenceAccumulatorTokenIndex(cycleIndex);
        if dataToken > 0
            seenTokenMask(dataToken) = true;
        end
    end
    if referenceAccumulatorValid(cycleIndex)
        referenceCode = referenceCode+ ...
            referenceAccumulatorProductCode(cycleIndex);
    end
    runningSumCode(cycleIndex) = actualCode;
    referenceRunningSumCode(cycleIndex) = referenceCode;
end

runningSum = runningSumCode*productLsb;
referenceRunningSum = referenceRunningSumCode*productLsb;
finalSumCode = runningSumCode(end);
referenceFinalSumCode = referenceRunningSumCode(end);
finalSum = runningSum(end);
referenceFinalSum = referenceRunningSum(end);
sumErrorCode = finalSumCode-referenceFinalSumCode;
sumError = finalSum-referenceFinalSum;

emptyAccumulationMask = accumulatorValid & ...
    referenceAccumulatorTokenIndex == 0;
mispairedProductMask = accumulatorValid & ...
    referenceAccumulatorTokenIndex > 0 & ...
    accumulatorValidTokenIndex ~= referenceAccumulatorTokenIndex;
claimedTokenMismatchMask = accumulatorValid & ...
    accumulatorValidTokenIndex ~= referenceAccumulatorTokenIndex;
prematureValidMask = accumulatorValid & ~referenceAccumulatorValid;
lateReferenceMask = referenceAccumulatorValid & ~accumulatorValid;
validDataMismatchMask = ...
    accumulatorValid ~= referenceAccumulatorValid | ...
    (accumulatorValid & referenceAccumulatorValid & ...
    accumulatorValidTokenIndex ~= referenceAccumulatorTokenIndex);
sumMismatchMask = runningSumCode ~= referenceRunningSumCode;
accumulatedTokenIndices = sampleIndex(seenTokenMask);
droppedTokenIndices = sampleIndex(~seenTokenMask);

minimumReferenceCode = min([0; referenceRunningSumCode]);
maximumReferenceCode = max([0; referenceRunningSumCode]);
minimumSequenceAccumulatorBits = 1;
for candidateWordLength = 1:16
    candidateMinimum = -2.^(candidateWordLength-1);
    candidateMaximum = 2.^(candidateWordLength-1)-1;
    if minimumReferenceCode >= candidateMinimum && ...
            maximumReferenceCode <= candidateMaximum
        minimumSequenceAccumulatorBits = candidateWordLength;
        break;
    end
end
modeledAccumulatorWordLength = ...
    productCodeWordLength+ceil(log2(sampleCount));
modeledAccumulatorMinimumCode = -2.^(modeledAccumulatorWordLength-1);
modeledAccumulatorMaximumCode = 2.^(modeledAccumulatorWordLength-1)-1;

referenceValidCycles = cycle(referenceAccumulatorValid);
actualValidCycles = cycle(accumulatorValid);
firstReferenceAccumulationCycle = referenceValidCycles(1);
completionCycle = referenceValidCycles(end);

out = struct( ...
    'pipelineStages',pipelineStages, ...
    'inputPeriod',inputPeriod, ...
    'selectedCycle',selectedCycle, ...
    'brokenValidAlignment',brokenValidAlignment, ...
    'sampleCount',sampleCount, ...
    'sampleIndex',sampleIndex, ...
    'operandFractionBits',operandFractionBits, ...
    'operandIntegerBits',operandIntegerBits, ...
    'operandWordLength',operandWordLength, ...
    'operandFormat','signed W=4, I=1 (sign excluded), F=2', ...
    'productCodeWordLength',productCodeWordLength, ...
    'productFractionBits',productFractionBits, ...
    'operandLsb',operandLsb, ...
    'productLsb',productLsb, ...
    'inputCodeSequence',inputCodeSequence, ...
    'coefficientCodeSequence',coefficientCodeSequence, ...
    'productCodeSequence',productCodeSequence, ...
    'productValueSequence',productValueSequence, ...
    'cycle',cycle, ...
    'totalCycles',totalCycles, ...
    'maxCycleCount',maxCycleCount, ...
    'lastInputCycle',lastInputCycle, ...
    'inputValid',inputValid, ...
    'inputTokenIndex',inputTokenIndex, ...
    'bubbleInputCode',bubbleInputCode, ...
    'bubbleCoefficientCode',bubbleCoefficientCode, ...
    'bubbleProductCode',bubbleProductCode, ...
    'inputCode',inputCode, ...
    'coefficientCode',coefficientCode, ...
    'inputProductCode',inputProductCode, ...
    'inputProductValue',inputProductValue, ...
    'productStageBefore',productStageBefore, ...
    'productStageAfter',productStageAfter, ...
    'validStageBefore',validStageBefore, ...
    'validStageAfter',validStageAfter, ...
    'tokenStageBefore',tokenStageBefore, ...
    'tokenStageAfter',tokenStageAfter, ...
    'referenceAccumulatorProductCode',referenceAccumulatorProductCode, ...
    'referenceAccumulatorValid',referenceAccumulatorValid, ...
    'referenceAccumulatorTokenIndex',referenceAccumulatorTokenIndex, ...
    'accumulatorProductCode',accumulatorProductCode, ...
    'accumulatorProductValue',accumulatorProductValue, ...
    'accumulatorValid',accumulatorValid, ...
    'accumulatorValidTokenIndex',accumulatorValidTokenIndex, ...
    'runningSumCode',runningSumCode, ...
    'referenceRunningSumCode',referenceRunningSumCode, ...
    'runningSum',runningSum, ...
    'referenceRunningSum',referenceRunningSum, ...
    'finalSumCode',finalSumCode, ...
    'referenceFinalSumCode',referenceFinalSumCode, ...
    'finalSum',finalSum, ...
    'referenceFinalSum',referenceFinalSum, ...
    'sumErrorCode',sumErrorCode, ...
    'sumError',sumError, ...
    'emptyAccumulationMask',emptyAccumulationMask, ...
    'emptyAccumulationCount',sum(emptyAccumulationMask), ...
    'mispairedProductMask',mispairedProductMask, ...
    'mispairedProductCount',sum(mispairedProductMask), ...
    'claimedTokenMismatchMask',claimedTokenMismatchMask, ...
    'claimedTokenMismatchCount',sum(claimedTokenMismatchMask), ...
    'prematureValidMask',prematureValidMask, ...
    'prematureValidCount',sum(prematureValidMask), ...
    'lateReferenceMask',lateReferenceMask, ...
    'lateReferenceCount',sum(lateReferenceMask), ...
    'validDataMismatchMask',validDataMismatchMask, ...
    'validDataMismatchCycles',cycle(validDataMismatchMask), ...
    'validDataMismatchCount',sum(validDataMismatchMask), ...
    'sumMismatchMask',sumMismatchMask, ...
    'sumMismatchCycles',cycle(sumMismatchMask), ...
    'sumMismatchCount',sum(sumMismatchMask), ...
    'accumulatedTokenIndices',accumulatedTokenIndices, ...
    'accumulatedProductCount',numel(accumulatedTokenIndices), ...
    'droppedTokenIndices',droppedTokenIndices, ...
    'droppedProductCount',numel(droppedTokenIndices), ...
    'referenceAccumulationCount',sum(referenceAccumulatorValid), ...
    'accumulationEventCount',sum(accumulatorValid), ...
    'referenceValidCycles',referenceValidCycles, ...
    'actualValidCycles',actualValidCycles, ...
    'firstReferenceAccumulationCycle',firstReferenceAccumulationCycle, ...
    'completionCycle',completionCycle, ...
    'latencyCycles',pipelineStages, ...
    'productDelayCycles',pipelineStages, ...
    'initiationIntervalCycles',inputPeriod, ...
    'modeledProductStorageSlots',pipelineStages, ...
    'modeledProductStorageBits',pipelineStages*productCodeWordLength, ...
    'modeledValidStorageBits',pipelineStages, ...
    'minimumReferenceCode',minimumReferenceCode, ...
    'maximumReferenceCode',maximumReferenceCode, ...
    'minimumSequenceAccumulatorBits',minimumSequenceAccumulatorBits, ...
    'modeledAccumulatorWordLength',modeledAccumulatorWordLength, ...
    'modeledAccumulatorMinimumCode',modeledAccumulatorMinimumCode, ...
    'modeledAccumulatorMaximumCode',modeledAccumulatorMaximumCode, ...
    'alignmentPolicy',alignmentPolicy, ...
    'selectedInputValid',inputValid(selectedCycle), ...
    'selectedInputToken',inputTokenIndex(selectedCycle), ...
    'selectedInputProductCode',inputProductCode(selectedCycle), ...
    'selectedReferenceValid',referenceAccumulatorValid(selectedCycle), ...
    'selectedActualValid',accumulatorValid(selectedCycle), ...
    'selectedDataToken',referenceAccumulatorTokenIndex(selectedCycle), ...
    'selectedValidToken',accumulatorValidTokenIndex(selectedCycle), ...
    'selectedAccumulatorProductCode',accumulatorProductCode(selectedCycle), ...
    'selectedRunningSumCode',runningSumCode(selectedCycle), ...
    'selectedReferenceSumCode',referenceRunningSumCode(selectedCycle), ...
    'equationText',['p_code[k] = x_code[k] h_code[k]; F_p = F_x + F_h; ' ...
        'A_code[c] = A_code[c-1] + v_in[c-L] p_code[c-L], with ' ...
        'c-L <= 0 treated as invalid reset fill.']);
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
        ~isnan(value) && ~isinf(value) && value == fix(value) && ...
        value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P06:InvalidBrokenValidAlignment', ...
        'brokenValidAlignment must be logical or numeric 0 or 1.');
end
end
