function run_checks
%RUN_CHECKS Execute independent P06 numeric, schedule, and boundary checks.
clear model;

%% Baseline codes, binary point, cycle convention, and exact recurrence
baseline = model(2,1,5,false);
expectedInputCodes = [3 -2 5 1 -4 6 -1 4].';
expectedCoefficientCodes = [2 4 -1 3 2 -2 5 5].';
expectedProductCodes = [6 -8 -5 3 -8 -12 -5 20].';
expectedPrefixCodes = [6 -2 -7 -4 -12 -24 -29 -9].';
expectedInputValid = [true(8,1); false(2,1)];
expectedAccumulatorValid = [false(2,1); true(8,1)];
expectedArrivingProducts = [0; 0; expectedProductCodes];
expectedRunningCodes = [0; 0; expectedPrefixCodes];
assert(isequal(baseline.inputCodeSequence,expectedInputCodes) && ...
    isequal(baseline.coefficientCodeSequence,expectedCoefficientCodes) && ...
    isequal(baseline.productCodeSequence,expectedProductCodes), ...
    'P06:BaselineCodes','The deterministic operand or product codes changed.');
assert(baseline.operandWordLength == 4 && ...
    baseline.operandFractionBits == 2 && ...
    baseline.productCodeWordLength == 8 && ...
    baseline.productFractionBits == 4 && ...
    baseline.operandLsb == 0.25 && baseline.productLsb == 0.0625 && ...
    isequal(baseline.productValueSequence,expectedProductCodes/16), ...
    'P06:BinaryPoint','Operand or product binary-point scaling changed.');
assert(isequal(baseline.inputValid,expectedInputValid) && ...
    isequal(baseline.referenceAccumulatorValid,expectedAccumulatorValid) && ...
    isequal(baseline.referenceAccumulatorProductCode, ...
        expectedArrivingProducts), ...
    'P06:BaselineSchedule','The two-stage dense schedule changed.');
assert(baseline.bubbleInputCode == 7 && ...
    baseline.bubbleCoefficientCode == -8 && ...
    baseline.bubbleProductCode == -56 && ...
    all(baseline.inputProductCode(~baseline.inputValid) == -56), ...
    'P06:BubblePoison', ...
    'Invalid input slots must retain nonzero ignored diagnostic data.');
assert(isequal(baseline.referenceRunningSumCode,expectedRunningCodes) && ...
    isequal(baseline.runningSumCode,expectedRunningCodes) && ...
    baseline.finalSumCode == -9 && baseline.finalSum == -0.5625 && ...
    baseline.sumErrorCode == 0, ...
    'P06:BaselineAccumulation','The exact baseline prefix sum changed.');
assert(baseline.firstReferenceAccumulationCycle == 3 && ...
    baseline.completionCycle == 10 && baseline.latencyCycles == 2 && ...
    baseline.referenceAccumulationCount == 8 && ...
    baseline.accumulationEventCount == 8, ...
    'P06:PostEdgeConvention', ...
    'Token k must accumulate at post-edge k+L for the dense baseline.');
assert(isequal(baseline.productStageBefore(1:3,:), ...
    [0 0; 6 0; -8 6]) && ...
    isequal(baseline.productStageAfter(1:3,:), ...
    [6 0; -8 6; -5 -8]) && ...
    isequal(baseline.tokenStageBefore(1:3,:), ...
    [0 0; 1 0; 2 1]), ...
    'P06:PrePostStageState', ...
    'Accumulator input must come from the last pre-edge product stage.');
assert(baseline.minimumReferenceCode == -29 && ...
    baseline.maximumReferenceCode == 6 && ...
    baseline.minimumSequenceAccumulatorBits == 6 && ...
    baseline.modeledAccumulatorWordLength == 11 && ...
    baseline.modeledAccumulatorMinimumCode == -1024 && ...
    baseline.modeledAccumulatorMaximumCode == 1023, ...
    'P06:AccumulatorRange','The fixed-sequence accumulator range changed.');
assert(baseline.selectedCycle == 5 && baseline.selectedInputToken == 5 && ...
    baseline.selectedDataToken == 3 && baseline.selectedValidToken == 3 && ...
    baseline.selectedAccumulatorProductCode == -5 && ...
    baseline.selectedRunningSumCode == -7, ...
    'P06:SelectedBaseline','The selected baseline observation changed.');
typedBaseline = model(uint8(2),int8(1),single(5),uint8(0));
assert(isequaln(typedBaseline,baseline), ...
    'P06:NumericClassNormalization', ...
    'Accepted numeric scalar classes must match the double-input baseline.');

%% Sweep 1 limits - change only registered product delay
pipelineStageCounts = 0:4;
expectedFirstCycles = 1:5;
expectedCompletionCycles = 8:12;
expectedStorageSlots = 0:4;
expectedStorageBits = 0:8:32;
observedFirstCycles = zeros(size(pipelineStageCounts));
observedCompletionCycles = zeros(size(pipelineStageCounts));
observedStorageSlots = zeros(size(pipelineStageCounts));
observedStorageBits = zeros(size(pipelineStageCounts));
for sweepIndex = 1:numel(pipelineStageCounts)
    pipelineStages = pipelineStageCounts(sweepIndex);
    current = model(pipelineStages,1,5,false);
    expectedValidCycles = ((1:8)+pipelineStages).';
    expectedShiftedSum = [zeros(pipelineStages,1); expectedPrefixCodes];
    assert(current.inputPeriod == 1 && ...
        isequal(current.cycle(current.inputValid),(1:8).') && ...
        isequal(current.productCodeSequence,expectedProductCodes), ...
        'P06:StageSweepIsolation', ...
        'Stage sweep must preserve input cadence and product codes.');
    assert(isequal(current.referenceValidCycles,expectedValidCycles) && ...
        isequal(current.runningSumCode,expectedShiftedSum) && ...
        current.finalSumCode == -9 && current.validDataMismatchCount == 0, ...
        'P06:StageSweep','Healthy stages must shift rather than edit the MAC.');
    observedFirstCycles(sweepIndex) = ...
        current.firstReferenceAccumulationCycle;
    observedCompletionCycles(sweepIndex) = current.completionCycle;
    observedStorageSlots(sweepIndex) = current.modeledProductStorageSlots;
    observedStorageBits(sweepIndex) = current.modeledProductStorageBits;
end
assert(isequal(observedFirstCycles,expectedFirstCycles) && ...
    isequal(observedCompletionCycles,expectedCompletionCycles) && ...
    isequal(observedStorageSlots,expectedStorageSlots) && ...
    isequal(observedStorageBits,expectedStorageBits), ...
    'P06:StageSweepLimits','Stage-delay or modeled-storage limits changed.');

%% Sweep 2 limits - reset to two stages, then change input spacing
inputPeriods = 1:4;
expectedPeriodCompletionCycles = [10 17 24 31];
expectedBubbleCounts = [0 7 14 21];
observedPeriodCompletionCycles = zeros(size(inputPeriods));
observedBubbleCounts = zeros(size(inputPeriods));
for sweepIndex = 1:numel(inputPeriods)
    inputPeriod = inputPeriods(sweepIndex);
    current = model(2,inputPeriod,5,false);
    expectedInputCycles = (1+(0:7)*inputPeriod).';
    expectedValidCycles = expectedInputCycles+2;
        assert(current.pipelineStages == 2 && ...
        isequal(current.cycle(current.inputValid),expectedInputCycles) && ...
        isequal(current.referenceValidCycles,expectedValidCycles) && ...
        isequal(diff(current.referenceValidCycles), ...
            repmat(inputPeriod,7,1)), ...
        'P06:PeriodSweepIsolation', ...
        'Input period must change only token and bubble spacing.');
    assert(all(current.inputProductCode(~current.inputValid) == -56), ...
        'P06:BubbleDataIgnored', ...
        'Bubble slots must carry nonzero data so valid gating is observable.');
    assert(current.firstReferenceAccumulationCycle == 3 && ...
        isequal(current.referenceAccumulatorTokenIndex(expectedValidCycles), ...
            (1:8).') && current.finalSumCode == -9 && ...
        current.accumulatedProductCount == 8 && ...
        current.droppedProductCount == 0, ...
        'P06:PeriodSweep','Healthy bubbles changed token order or arithmetic.');
    observedPeriodCompletionCycles(sweepIndex) = current.completionCycle;
    observedBubbleCounts(sweepIndex) = ...
        sum(~current.inputValid(1:current.lastInputCycle));
end
assert(isequal(observedPeriodCompletionCycles, ...
    expectedPeriodCompletionCycles) && ...
    isequal(observedBubbleCounts,expectedBubbleCounts), ...
    'P06:PeriodSweepLimits','Input-period completion or bubble limits changed.');

%% Complete healthy grid, per-cycle holds, and fixed resource bounds
for pipelineStages = 0:4
    for inputPeriod = 1:4
        current = model(pipelineStages,inputPeriod,5,false);
        expectedInputCycles = (1+(0:7)*inputPeriod).';
        expectedOutputCycles = expectedInputCycles+pipelineStages;
        assert(current.totalCycles == expectedOutputCycles(end) && ...
            current.totalCycles <= 33 && current.maxCycleCount == 33 && ...
            isequal(size(current.productStageAfter), ...
                [current.totalCycles pipelineStages]) && ...
            numel(current.productStageAfter) <= 132, ...
            'P06:ResourceBound', ...
            'The bounded cycle or product-stage allocation changed.');
        assert(all(current.referenceRunningSumCode >= ...
                current.modeledAccumulatorMinimumCode) && ...
            all(current.referenceRunningSumCode <= ...
                current.modeledAccumulatorMaximumCode), ...
            'P06:AccumulatorResourceBound', ...
            'Reference sums exceeded the conservative modeled width.');
        assert(isequal(current.inputTokenIndex(expectedInputCycles),(1:8).') && ...
            isequal(current.inputProductCode(expectedInputCycles), ...
                expectedProductCodes) && ...
            isequal(current.referenceAccumulatorTokenIndex( ...
                expectedOutputCycles),(1:8).') && ...
            isequal(current.referenceAccumulatorProductCode( ...
                expectedOutputCycles),expectedProductCodes), ...
            'P06:TokenOrder','Healthy product tokens changed order.');
        assert(isequal(current.runningSumCode(expectedOutputCycles), ...
            expectedPrefixCodes) && ...
            isequal(current.runningSumCode,current.referenceRunningSumCode) && ...
            current.finalSumCode == -9 && ...
            current.referenceAccumulationCount == 8 && ...
            current.accumulatedProductCount == 8 && ...
            isempty(current.droppedTokenIndices) && ...
            current.validDataMismatchCount == 0, ...
            'P06:HealthyGrid','Healthy grid lost, duplicated, or edited a token.');
        for cycleIndex = 2:current.totalCycles
            if ~current.referenceAccumulatorValid(cycleIndex)
                assert(current.runningSumCode(cycleIndex) == ...
                    current.runningSumCode(cycleIndex-1), ...
                    'P06:BubbleHold', ...
                    'An invalid bubble must hold accumulator state.');
            end
        end
    end
end
maximumTimeline = model(4,4,33,false);
assert(maximumTimeline.totalCycles == 33 && ...
    maximumTimeline.completionCycle == 33 && ...
    maximumTimeline.modeledProductStorageBits == 32, ...
    'P06:MaximumTimeline','The maximum bounded configuration changed.');

%% Deliberately broken valid bypass, token symptom, and inert limit
healthyDense = model(2,1,5,false);
brokenDense = model(2,1,5,true);
expectedBrokenRunningCodes = [0 0 6 -2 -7 -4 -12 -24 -24 -24].';
expectedClaimedTokens = (1:8).';
expectedDataTokensAtClaims = [0 0 1 2 3 4 5 6].';
assert(isequal(brokenDense.runningSumCode,expectedBrokenRunningCodes) && ...
    brokenDense.finalSumCode == -24 && ...
    brokenDense.sumErrorCode == -15 && brokenDense.sumError == -0.9375, ...
    'P06:BrokenFinalSum','The broken valid-bypass result changed.');
assert(isequal(brokenDense.accumulatorValidTokenIndex(1:8), ...
        expectedClaimedTokens) && ...
    isequal(brokenDense.referenceAccumulatorTokenIndex(1:8), ...
        expectedDataTokensAtClaims) && ...
    brokenDense.claimedTokenMismatchCount == 8 && ...
    brokenDense.emptyAccumulationCount == 2 && ...
    brokenDense.mispairedProductCount == 6, ...
    'P06:BrokenTokenAssociation', ...
    'Every broken valid claim must name empty or stale product data.');
assert(isequal(brokenDense.accumulatedTokenIndices,(1:6).') && ...
    isequal(brokenDense.droppedTokenIndices,[7; 8]) && ...
    brokenDense.droppedProductCount == 2 && ...
    brokenDense.prematureValidCount == 2 && ...
    brokenDense.lateReferenceCount == 2 && ...
    isequal(brokenDense.validDataMismatchCycles,(1:10).') && ...
    isequal(brokenDense.sumMismatchCycles,[9; 10]), ...
    'P06:BrokenTailLoss', ...
    'Broken bypass must expose the two unconsumed tail products.');
assert(isequal(brokenDense.referenceRunningSumCode, ...
        healthyDense.runningSumCode) && ...
    isequal(brokenDense.referenceAccumulatorProductCode, ...
        healthyDense.accumulatorProductCode) && ...
    isequal(brokenDense.productStageAfter,healthyDense.productStageAfter), ...
    'P06:BrokenIsolation', ...
    'The fault must change only valid/token gating, not product movement.');
for pipelineStages = 1:4
    current = model(pipelineStages,1,5,true);
    expectedConsumedCount = 8-pipelineStages;
    assert(current.emptyAccumulationCount == pipelineStages && ...
        current.mispairedProductCount == expectedConsumedCount && ...
        current.claimedTokenMismatchCount == 8 && ...
        isequal(current.accumulatedTokenIndices, ...
            (1:expectedConsumedCount).') && ...
        isequal(current.droppedTokenIndices, ...
            (expectedConsumedCount+1:8).') && ...
        current.finalSumCode == sum(expectedProductCodes( ...
            1:expectedConsumedCount)), ...
        'P06:BrokenDepthGrid', ...
        'Broken loss severity must follow the bypassed product delay.');
end
for pipelineStages = 1:4
    for inputPeriod = 1:4
        current = model(pipelineStages,inputPeriod,5,true);
        assert(current.accumulationEventCount == 8 && ...
            current.claimedTokenMismatchCount == 8 && ...
            current.droppedProductCount >= 1 && ...
            all(current.runningSumCode >= ...
                current.modeledAccumulatorMinimumCode) && ...
            all(current.runningSumCode <= ...
                current.modeledAccumulatorMaximumCode), ...
            'P06:BrokenResourceGrid', ...
            'Broken schedules must remain bounded and expose every bad claim.');
    end
end
brokenSparse = model(1,4,5,true);
assert(brokenSparse.finalSumCode == -392 && ...
    brokenSparse.accumulatedProductCount == 0 && ...
    brokenSparse.emptyAccumulationCount == 8 && ...
    isequal(brokenSparse.droppedTokenIndices,(1:8).'), ...
    'P06:BrokenBubblePoison', ...
    'Sparse valid bypass must expose ignored nonzero bubble data.');
healthyDirect = model(0,1,5,false);
brokenDirect = model(0,1,5,true);
assert(isequaln(healthyDirect,brokenDirect) == false && ...
    isequal(healthyDirect.runningSumCode,brokenDirect.runningSumCode) && ...
    brokenDirect.validDataMismatchCount == 0 && ...
    brokenDirect.droppedProductCount == 0 && brokenDirect.sumErrorCode == 0, ...
    'P06:BrokenInertLimit', ...
    'Valid bypass must be numerically and temporally inert at L=0.');

%% Malformed inputs, selected-view isolation, and deterministic recovery
assertRejects(@() model(-1,1,5,false),'P06:InvalidPipelineStages');
assertRejects(@() model(5,1,5,false),'P06:InvalidPipelineStages');
assertRejects(@() model(2.5,1,5,false),'P06:InvalidPipelineStages');
assertRejects(@() model([2 3],1,5,false),'P06:InvalidPipelineStages');
assertRejects(@() model(NaN,1,5,false),'P06:InvalidPipelineStages');
assertRejects(@() model(Inf,1,5,false),'P06:InvalidPipelineStages');
assertRejects(@() model(1+1i,1,5,false),'P06:InvalidPipelineStages');
assertRejects(@() model(true,1,5,false),'P06:InvalidPipelineStages');
assertRejects(@() model(2,0,5,false),'P06:InvalidInputPeriod');
assertRejects(@() model(2,5,5,false),'P06:InvalidInputPeriod');
assertRejects(@() model(2,1.5,5,false),'P06:InvalidInputPeriod');
assertRejects(@() model(2,[1 2],5,false),'P06:InvalidInputPeriod');
assertRejects(@() model(2,NaN,5,false),'P06:InvalidInputPeriod');
assertRejects(@() model(2,Inf,5,false),'P06:InvalidInputPeriod');
assertRejects(@() model(2,1+1i,5,false),'P06:InvalidInputPeriod');
assertRejects(@() model(2,true,5,false),'P06:InvalidInputPeriod');
assertRejects(@() model(0,1,0,false),'P06:InvalidSelectedCycle');
assertRejects(@() model(0,1,9,false),'P06:InvalidSelectedCycle');
assertRejects(@() model(4,4,34,false),'P06:InvalidSelectedCycle');
assertRejects(@() model(2,1,2.5,false),'P06:InvalidSelectedCycle');
assertRejects(@() model(2,1,[2 3],false),'P06:InvalidSelectedCycle');
assertRejects(@() model(2,1,NaN,false),'P06:InvalidSelectedCycle');
assertRejects(@() model(2,1,Inf,false),'P06:InvalidSelectedCycle');
assertRejects(@() model(2,1,1+1i,false),'P06:InvalidSelectedCycle');
assertRejects(@() model(2,1,true,false),'P06:InvalidSelectedCycle');
assertRejects(@() model(2,1,5,2),'P06:InvalidBrokenValidAlignment');
assertRejects(@() model(2,1,5,0.5),'P06:InvalidBrokenValidAlignment');
assertRejects(@() model(2,1,5,[false true]), ...
    'P06:InvalidBrokenValidAlignment');
assertRejects(@() model(2,1,5,NaN),'P06:InvalidBrokenValidAlignment');
assertRejects(@() model(2,1,5,Inf),'P06:InvalidBrokenValidAlignment');
assertRejects(@() model(2,1,5,1+1i), ...
    'P06:InvalidBrokenValidAlignment');

selectedFirst = model(2,3,1,false);
selectedLast = model(2,3,24,false);
assert(isequal(selectedFirst.inputProductCode,selectedLast.inputProductCode) && ...
    isequal(selectedFirst.productStageAfter,selectedLast.productStageAfter) && ...
    isequal(selectedFirst.referenceAccumulatorProductCode, ...
        selectedLast.referenceAccumulatorProductCode) && ...
    isequal(selectedFirst.runningSumCode,selectedLast.runningSumCode), ...
    'P06:SelectedViewIsolation', ...
    'Selecting a cycle must not alter the deterministic calculation.');
baselineAfterFailures = model(2,1,5,false);
differentConfiguration = model(4,4,33,true); %#ok<NASGU>
baselineAfterOtherCall = model(2,1,5,false);
assert(isequaln(baseline,baselineAfterFailures) && ...
    isequaln(baseline,baselineAfterOtherCall), ...
    'P06:DeterminismRecovery', ...
    'Valid output must recover unchanged after failures and other calls.');

disp(['P06 checks passed: codes, stages, bubbles, alignment, validation, ' ...
    'resource bounds, and recovery.']);
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P06:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
