function interactive
%INTERACTIVE Explore NCO tuning, phase lookup resolution, and one fault.
clear model;
modelFcn = @model;
figureName = 'P08 Numerically Controlled Oscillator Explorer';
delete(findall(groot,'Type','figure','Name',figureName));

fig = uifigure('Name',figureName,'Position',[80 70 1240 790]);
gridLayout = uigridlayout(fig,[4 4]);
gridLayout.RowHeight = {72,'1x',122,154};
gridLayout.ColumnWidth = {'1x','1x','1x','1x'};

instruction = uilabel(gridLayout,'WordWrap','on', ...
    'Text',['Read the K=411, P=8 baseline first. Change the tuning word ' ...
    'or phase-address width independently: K controls phase advance and ' ...
    'frequency; P controls lookup granularity and entries. The broken ' ...
    'switch removes low bits from K before accumulation.']);
instruction.Layout.Row = 1;
instruction.Layout.Column = [1 4];

phaseAxes = uiaxes(gridLayout);
phaseAxes.Layout.Row = 2;
phaseAxes.Layout.Column = [1 2];
spectrumAxes = uiaxes(gridLayout);
spectrumAxes.Layout.Row = 2;
spectrumAxes.Layout.Column = [3 4];

tuningPanel = uipanel(gridLayout,'Title','Lever 1: tuning word K');
tuningPanel.Layout.Row = 3;
tuningPanel.Layout.Column = 1;
tuningGrid = uigridlayout(tuningPanel,[2 1]);
tuningGrid.RowHeight = {52,'1x'};
uilabel(tuningGrid,'WordWrap','on', ...
    'Text','Changes phase codes/sample and frequency; lookup width stays fixed.');
tuningSpinner = uispinner(tuningGrid,'Limits',[0 2047], ...
    'RoundFractionalValues','on','Step',1,'Value',411, ...
    'Tooltip','Unsigned 12-bit phase increment below Nyquist.');

addressPanel = uipanel(gridLayout,'Title','Lever 2: lookup address P');
addressPanel.Layout.Row = 3;
addressPanel.Layout.Column = 2;
addressGrid = uigridlayout(addressPanel,[2 1]);
addressGrid.RowHeight = {52,'1x'};
uilabel(addressGrid,'WordWrap','on', ...
    'Text','Changes 2^P phase entries and truncation error; K stays intact.');
addressSpinner = uispinner(addressGrid,'Limits',[3 12], ...
    'RoundFractionalValues','on','Step',1,'Value',8, ...
    'Tooltip','Most-significant accumulator bits used by the phase lookup.');

offsetPanel = uipanel(gridLayout,'Title','Initial phase');
offsetPanel.Layout.Row = 3;
offsetPanel.Layout.Column = 3;
offsetGrid = uigridlayout(offsetPanel,[2 1]);
offsetGrid.RowHeight = {52,'1x'};
uilabel(offsetGrid,'WordWrap','on', ...
    'Text','Rotates the starting phase without changing frequency or resources.');
offsetSpinner = uispinner(offsetGrid,'Limits',[0 4095], ...
    'RoundFractionalValues','on','Step',1,'Value',0, ...
    'Tooltip','Initial unsigned 12-bit accumulator code.');

faultPanel = uipanel(gridLayout,'Title','Deliberately broken case');
faultPanel.Layout.Row = 3;
faultPanel.Layout.Column = 4;
faultGrid = uigridlayout(faultPanel,[2 1]);
faultGrid.RowHeight = {56,'1x'};
uilabel(faultGrid,'WordWrap','on', ...
    'Text','Enabled only when premature truncation would remove nonzero K bits.');
faultCheckbox = uicheckbox(faultGrid, ...
    'Text','Truncate K before accumulation','Value',false, ...
    'Tooltip',['Violates full-width accumulation by clearing the same low ' ...
    'bits discarded at the lookup.']);

summary = uilabel(gridLayout,'WordWrap','on');
summary.Layout.Row = 4;
summary.Layout.Column = [1 4];

tuningSpinner.ValueChangedFcn = @(~,~) updatePlots();
addressSpinner.ValueChangedFcn = @(~,~) updatePlots();
offsetSpinner.ValueChangedFcn = @(~,~) updatePlots();
faultCheckbox.ValueChangedFcn = @(~,~) updatePlots();
updatePlots();

    function updatePlots
        tuningWord = round(tuningSpinner.Value);
        phaseAddressBits = round(addressSpinner.Value);
        initialPhaseCode = round(offsetSpinner.Value);
        truncationFactor = 2^(12-phaseAddressBits);
        if mod(tuningWord,truncationFactor) == 0
            faultCheckbox.Value = false;
            faultCheckbox.Enable = 'off';
        else
            faultCheckbox.Enable = 'on';
        end
        brokenIncrementTruncation = faultCheckbox.Value;
        out = modelFcn(tuningWord,phaseAddressBits,initialPhaseCode, ...
            brokenIncrementTruncation);

        visibleSamples = 64;
        cla(phaseAxes);
        stairs(phaseAxes,out.sampleIndex(1:visibleSamples), ...
            out.referencePhaseCode(1:visibleSamples),'LineWidth',1.2, ...
            'DisplayName','Required full-width phase');
        hold(phaseAxes,'on');
        stairs(phaseAxes,out.sampleIndex(1:visibleSamples), ...
            out.phaseCode(1:visibleSamples),'--','LineWidth',1.2, ...
            'DisplayName','Applied phase');
        hold(phaseAxes,'off');
        grid(phaseAxes,'on');
        xlabel(phaseAxes,'Sample [index]');
        ylabel(phaseAxes,'Accumulator phase [unsigned 12-bit code]');
        title(phaseAxes,'Modulo accumulator: reference versus applied path');
        phaseAxes.XLim = [0 visibleSamples-1];
        phaseAxes.YLim = [0 4095];
        legend(phaseAxes,'Location','best');

        cla(spectrumAxes);
        plot(spectrumAxes,out.spectrumFrequencyMHz, ...
            max(out.referenceSpectrumDbcCentered,-120),'LineWidth',1.2, ...
            'DisplayName','Required output');
        hold(spectrumAxes,'on');
        plot(spectrumAxes,out.spectrumFrequencyMHz, ...
            max(out.spectrumDbcCentered,-120),'--','LineWidth',1.2, ...
            'DisplayName','Applied output');
        hold(spectrumAxes,'off');
        grid(spectrumAxes,'on');
        xlabel(spectrumAxes, ...
            'Discrete-time frequency [MHz at assumed 100 MHz]');
        ylabel(spectrumAxes,'4096-sample spectrum [dBc to each carrier]');
        title(spectrumAxes,'Carrier location and phase-truncation spurs');
        spectrumAxes.XLim = [-50 50];
        spectrumAxes.YLim = [-120 5];
        legend(spectrumAxes,'Location','best');

        health = 'healthy: full K is accumulated before phase lookup';
        if out.faultActive
            health = ['BROKEN: low K bits were removed before the ' ...
                'accumulator, so the carrier moved'];
        end
        summary.Text = sprintf([ ...
            'K required/applied=%d/%d codes/sample; phase step=%0.6g/%0.6g ' ...
            'degrees/sample; frequency required/applied=%0.9g/%0.9g MHz; ' ...
            'error=%0.9g kHz (%d resolution steps); next-state wraps ' ...
            'required/applied=%d/%d across %d transitions, including the ' ...
            'terminal transition (stored-state discontinuities=%d/%d ' ...
            'across %d adjacent transitions); period=%d/%d samples. ' ...
            'P=%d gives %d lookup entries, ' ...
            '%g degree lookup steps, max/RMS applied phase error=' ...
            '%0.6g/%0.6g degrees, modeled record SFDR=%0.6g dB ' ...
            '(Inf means no spur resolved above the %g dBc numerical ' ...
            'floor), and %d ' ...
            'sine/cosine table values. Initial phase=%d code. %s. ' ...
            'The %g MHz clock is assumed, and lookup entries are not BRAM, ' ...
            'area, timing, or hardware evidence. %s'], ...
            out.tuningWord,out.effectiveTuningWord, ...
            out.requestedPhaseStepDegrees,out.actualPhaseStepDegrees, ...
            out.requestedFrequencyMHz,out.actualFrequencyMHz, ...
            out.frequencyErrorKHz,-out.discardedTuningWordCode, ...
            out.referenceWrapCount,out.wrapCount,out.transitionCount, ...
            out.referenceWithinRecordWrapCount,out.withinRecordWrapCount, ...
            out.withinRecordTransitionCount, ...
            out.referenceAccumulatorPeriodSamples, ...
            out.accumulatorPeriodSamples,out.phaseAddressBits, ...
            out.lookupEntryCount,out.lookupPhaseStepDegrees, ...
            out.maximumPhaseTruncationErrorDegrees, ...
            out.phaseTruncationRmsDegrees,out.recordSfdrDb, ...
            out.spectralNumericalFloorDbc, ...
            out.modeledLookupPairValueCount,out.initialPhaseCode,health, ...
            out.sampleClockMHz,out.equationText);
        drawnow;
    end
end
