function out = model(tuningWord,phaseAddressBits,initialPhaseCode,brokenIncrementTruncation)
%MODEL Generate a deterministic lookup-table NCO from a phase accumulator.
%   The healthy path accumulates the full 12-bit tuning word modulo 2^12,
%   then truncates phase only when addressing a sine/cosine lookup table.
%   The broken path discards the tuning word's low bits before accumulation,
%   which changes frequency whenever those bits are nonzero.

if nargin < 1
    tuningWord = 411;
end
if nargin < 2
    phaseAddressBits = 8;
end
if nargin < 3
    initialPhaseCode = 0;
end
if nargin < 4
    brokenIncrementTruncation = false;
end

accumulatorBits = 12;
phaseModulus = 2^accumulatorBits;
maximumTuningWord = phaseModulus/2-1;
validateIntegerScalar(tuningWord,0,maximumTuningWord, ...
    'P08:InvalidTuningWord','tuningWord');
validateIntegerScalar(phaseAddressBits,3,accumulatorBits, ...
    'P08:InvalidPhaseAddressBits','phaseAddressBits');
validateIntegerScalar(initialPhaseCode,0,phaseModulus-1, ...
    'P08:InvalidInitialPhaseCode','initialPhaseCode');
validateBooleanScalar(brokenIncrementTruncation);
tuningWord = double(tuningWord);
phaseAddressBits = double(phaseAddressBits);
initialPhaseCode = double(initialPhaseCode);
brokenIncrementTruncation = logical(brokenIncrementTruncation);

sampleClockMHz = 100;
recordSampleCount = phaseModulus;
sampleIndex = (0:recordSampleCount-1).';
sampleTimeMicroseconds = sampleIndex/sampleClockMHz;
lookupEntryCount = 2^phaseAddressBits;
discardedPhaseBits = accumulatorBits-phaseAddressBits;
phaseTruncationFactor = 2^discardedPhaseBits;
phaseAccumulatorLsbDegrees = 360/phaseModulus;
lookupPhaseStepDegrees = 360/lookupEntryCount;
frequencyResolutionKHz = sampleClockMHz*1000/phaseModulus;

effectiveTuningWord = tuningWord;
if brokenIncrementTruncation
    effectiveTuningWord = ...
        floor(tuningWord/phaseTruncationFactor)*phaseTruncationFactor;
end
discardedTuningWordCode = tuningWord-effectiveTuningWord;
faultActive = brokenIncrementTruncation && discardedTuningWordCode ~= 0;
faultCanChangeFrequency = phaseTruncationFactor > 1 && ...
    mod(tuningWord,phaseTruncationFactor) ~= 0;

referencePhaseCode = mod(initialPhaseCode+sampleIndex*tuningWord, ...
    phaseModulus);
phaseCode = mod(initialPhaseCode+sampleIndex*effectiveTuningWord, ...
    phaseModulus);
referenceNextPhaseCode = mod(referencePhaseCode+tuningWord,phaseModulus);
nextPhaseCode = mod(phaseCode+effectiveTuningWord,phaseModulus);
referencePhaseStepCode = mod(referenceNextPhaseCode-referencePhaseCode, ...
    phaseModulus);
phaseStepCode = mod(nextPhaseCode-phaseCode,phaseModulus);
referenceWrapEvent = referencePhaseCode+tuningWord >= phaseModulus;
wrapEvent = phaseCode+effectiveTuningWord >= phaseModulus;
referenceWithinRecordWrapEvent = ...
    [false; diff(referencePhaseCode) < 0];
withinRecordWrapEvent = [false; diff(phaseCode) < 0];

referenceLookupAddress = floor(referencePhaseCode/phaseTruncationFactor);
lookupAddress = floor(phaseCode/phaseTruncationFactor);
lookupAddressIndex = (0:lookupEntryCount-1).';
lookupPhaseRadians = 2*pi*lookupAddressIndex/lookupEntryCount;
lookupCosineTable = cos(lookupPhaseRadians);
lookupSineTable = sin(lookupPhaseRadians);
lookupComplexTable = lookupCosineTable+1i*lookupSineTable;
referenceComplexOutput = lookupComplexTable(referenceLookupAddress+1);
complexOutput = lookupComplexTable(lookupAddress+1);
referenceCosineOutput = real(referenceComplexOutput);
referenceSineOutput = imag(referenceComplexOutput);
cosineOutput = real(complexOutput);
sineOutput = imag(complexOutput);

referenceIdealPhaseRadians = 2*pi*referencePhaseCode/phaseModulus;
idealPhaseRadians = 2*pi*phaseCode/phaseModulus;
referenceIdealComplexOutput = ...
    cos(referenceIdealPhaseRadians)+1i*sin(referenceIdealPhaseRadians);
idealComplexOutput = cos(idealPhaseRadians)+1i*sin(idealPhaseRadians);
referencePhaseTruncationErrorCode = ...
    referenceLookupAddress*phaseTruncationFactor-referencePhaseCode;
phaseTruncationErrorCode = ...
    lookupAddress*phaseTruncationFactor-phaseCode;
referencePhaseTruncationErrorDegrees = ...
    referencePhaseTruncationErrorCode*phaseAccumulatorLsbDegrees;
phaseTruncationErrorDegrees = ...
    phaseTruncationErrorCode*phaseAccumulatorLsbDegrees;
referenceWaveformRmsError = sqrt(mean(abs( ...
    referenceComplexOutput-referenceIdealComplexOutput).^2));
waveformRmsError = sqrt(mean(abs(complexOutput-idealComplexOutput).^2));

referenceSpectrum = fft(referenceComplexOutput)/recordSampleCount;
spectrum = fft(complexOutput)/recordSampleCount;
referenceSpectrumMagnitude = abs(referenceSpectrum);
spectrumMagnitude = abs(spectrum);
referenceCarrierBinIndex = tuningWord+1;
carrierBinIndex = effectiveTuningWord+1;
referenceCarrierMagnitude = ...
    referenceSpectrumMagnitude(referenceCarrierBinIndex);
carrierMagnitude = spectrumMagnitude(carrierBinIndex);
referenceSpurMagnitude = referenceSpectrumMagnitude;
referenceSpurMagnitude(referenceCarrierBinIndex) = 0;
spurMagnitude = spectrumMagnitude;
spurMagnitude(carrierBinIndex) = 0;
largestReferenceSpurMagnitude = max(referenceSpurMagnitude);
largestSpurMagnitude = max(spurMagnitude);
spectralNumericalFloorDbc = -240;
spectralNumericalFloorRatio = 10^(spectralNumericalFloorDbc/20);
referenceSpectralFloorMagnitude = ...
    referenceCarrierMagnitude*spectralNumericalFloorRatio;
spectralFloorMagnitude = carrierMagnitude*spectralNumericalFloorRatio;
referenceSpectralFloorLimited = ...
    largestReferenceSpurMagnitude <= referenceSpectralFloorMagnitude;
spectralFloorLimited = largestSpurMagnitude <= spectralFloorMagnitude;
if referenceSpectralFloorLimited
    referenceRecordSfdrDb = Inf;
else
    referenceRecordSfdrDb = 20*log10( ...
        referenceCarrierMagnitude/largestReferenceSpurMagnitude);
end
if spectralFloorLimited
    recordSfdrDb = Inf;
else
    recordSfdrDb = 20*log10(carrierMagnitude/largestSpurMagnitude);
end
referenceSpectrumDbc = 20*log10(max(referenceSpectrumMagnitude, ...
    referenceSpectralFloorMagnitude)/referenceCarrierMagnitude);
spectrumDbc = 20*log10(max(spectrumMagnitude, ...
    spectralFloorMagnitude)/carrierMagnitude);
spectrumFrequencyMHz = (-recordSampleCount/2:recordSampleCount/2-1).' * ...
    sampleClockMHz/recordSampleCount;
referenceSpectrumDbcCentered = fftshift(referenceSpectrumDbc);
spectrumDbcCentered = fftshift(spectrumDbc);
[~,referenceDominantBinIndex] = max(referenceSpectrumMagnitude);
[~,dominantBinIndex] = max(spectrumMagnitude);
referenceDominantFrequencyMHz = ...
    (referenceDominantBinIndex-1)*sampleClockMHz/recordSampleCount;
dominantFrequencyMHz = ...
    (dominantBinIndex-1)*sampleClockMHz/recordSampleCount;

requestedFrequencyMHz = tuningWord*sampleClockMHz/phaseModulus;
actualFrequencyMHz = effectiveTuningWord*sampleClockMHz/phaseModulus;
frequencyErrorKHz = (actualFrequencyMHz-requestedFrequencyMHz)*1000;
requestedPhaseStepDegrees = tuningWord*phaseAccumulatorLsbDegrees;
actualPhaseStepDegrees = effectiveTuningWord*phaseAccumulatorLsbDegrees;
if tuningWord == 0
    referenceAccumulatorPeriodSamples = 1;
else
    referenceAccumulatorPeriodSamples = ...
        phaseModulus/gcd(phaseModulus,tuningWord);
end
if effectiveTuningWord == 0
    accumulatorPeriodSamples = 1;
else
    accumulatorPeriodSamples = ...
        phaseModulus/gcd(phaseModulus,effectiveTuningWord);
end

out = struct( ...
    'tuningWord',tuningWord, ...
    'phaseAddressBits',phaseAddressBits, ...
    'initialPhaseCode',initialPhaseCode, ...
    'brokenIncrementTruncation',brokenIncrementTruncation, ...
    'accumulatorBits',accumulatorBits, ...
    'phaseModulus',phaseModulus, ...
    'maximumTuningWord',maximumTuningWord, ...
    'sampleClockMHz',sampleClockMHz, ...
    'recordSampleCount',recordSampleCount, ...
    'sampleIndex',sampleIndex, ...
    'sampleTimeMicroseconds',sampleTimeMicroseconds, ...
    'lookupEntryCount',lookupEntryCount, ...
    'discardedPhaseBits',discardedPhaseBits, ...
    'phaseTruncationFactor',phaseTruncationFactor, ...
    'phaseAccumulatorLsbDegrees',phaseAccumulatorLsbDegrees, ...
    'lookupPhaseStepDegrees',lookupPhaseStepDegrees, ...
    'frequencyResolutionKHz',frequencyResolutionKHz, ...
    'effectiveTuningWord',effectiveTuningWord, ...
    'discardedTuningWordCode',discardedTuningWordCode, ...
    'faultActive',faultActive, ...
    'faultCanChangeFrequency',faultCanChangeFrequency, ...
    'referencePhaseCode',referencePhaseCode, ...
    'phaseCode',phaseCode, ...
    'referenceNextPhaseCode',referenceNextPhaseCode, ...
    'nextPhaseCode',nextPhaseCode, ...
    'referencePhaseStepCode',referencePhaseStepCode, ...
    'phaseStepCode',phaseStepCode, ...
    'referenceWrapEvent',referenceWrapEvent, ...
    'wrapEvent',wrapEvent, ...
    'referenceWrapCount',sum(referenceWrapEvent), ...
    'wrapCount',sum(wrapEvent), ...
    'referenceWithinRecordWrapEvent',referenceWithinRecordWrapEvent, ...
    'withinRecordWrapEvent',withinRecordWrapEvent, ...
    'referenceWithinRecordWrapCount', ...
        sum(referenceWithinRecordWrapEvent), ...
    'withinRecordWrapCount',sum(withinRecordWrapEvent), ...
    'transitionCount',recordSampleCount, ...
    'withinRecordTransitionCount',recordSampleCount-1, ...
    'referenceTerminalNextPhaseCode',referenceNextPhaseCode(end), ...
    'terminalNextPhaseCode',nextPhaseCode(end), ...
    'referenceLookupAddress',referenceLookupAddress, ...
    'lookupAddress',lookupAddress, ...
    'lookupAddressIndex',lookupAddressIndex, ...
    'lookupPhaseRadians',lookupPhaseRadians, ...
    'lookupCosineTable',lookupCosineTable, ...
    'lookupSineTable',lookupSineTable, ...
    'referenceComplexOutput',referenceComplexOutput, ...
    'complexOutput',complexOutput, ...
    'referenceCosineOutput',referenceCosineOutput, ...
    'referenceSineOutput',referenceSineOutput, ...
    'cosineOutput',cosineOutput, ...
    'sineOutput',sineOutput, ...
    'referenceIdealPhaseRadians',referenceIdealPhaseRadians, ...
    'idealPhaseRadians',idealPhaseRadians, ...
    'referenceIdealComplexOutput',referenceIdealComplexOutput, ...
    'idealComplexOutput',idealComplexOutput, ...
    'referencePhaseTruncationErrorCode', ...
        referencePhaseTruncationErrorCode, ...
    'phaseTruncationErrorCode',phaseTruncationErrorCode, ...
    'referencePhaseTruncationErrorDegrees', ...
        referencePhaseTruncationErrorDegrees, ...
    'phaseTruncationErrorDegrees',phaseTruncationErrorDegrees, ...
    'referencePhaseTruncationRmsDegrees',sqrt(mean( ...
        referencePhaseTruncationErrorDegrees.^2)), ...
    'phaseTruncationRmsDegrees',sqrt(mean( ...
        phaseTruncationErrorDegrees.^2)), ...
    'referenceMaximumPhaseTruncationErrorDegrees',max(abs( ...
        referencePhaseTruncationErrorDegrees)), ...
    'maximumPhaseTruncationErrorDegrees',max(abs( ...
        phaseTruncationErrorDegrees)), ...
    'referenceWaveformRmsError',referenceWaveformRmsError, ...
    'waveformRmsError',waveformRmsError, ...
    'referenceSpectrumMagnitude',referenceSpectrumMagnitude, ...
    'spectrumMagnitude',spectrumMagnitude, ...
    'spectrumFrequencyMHz',spectrumFrequencyMHz, ...
    'referenceSpectrumDbcCentered',referenceSpectrumDbcCentered, ...
    'spectrumDbcCentered',spectrumDbcCentered, ...
    'referenceCarrierBinIndex',referenceCarrierBinIndex, ...
    'carrierBinIndex',carrierBinIndex, ...
    'referenceCarrierMagnitude',referenceCarrierMagnitude, ...
    'carrierMagnitude',carrierMagnitude, ...
    'largestReferenceSpurMagnitude',largestReferenceSpurMagnitude, ...
    'largestSpurMagnitude',largestSpurMagnitude, ...
    'spectralNumericalFloorDbc',spectralNumericalFloorDbc, ...
    'referenceSpectralFloorMagnitude', ...
        referenceSpectralFloorMagnitude, ...
    'spectralFloorMagnitude',spectralFloorMagnitude, ...
    'referenceSpectralFloorLimited',referenceSpectralFloorLimited, ...
    'spectralFloorLimited',spectralFloorLimited, ...
    'referenceRecordSfdrDb',referenceRecordSfdrDb, ...
    'recordSfdrDb',recordSfdrDb, ...
    'referenceDominantBinIndex',referenceDominantBinIndex, ...
    'dominantBinIndex',dominantBinIndex, ...
    'referenceDominantFrequencyMHz',referenceDominantFrequencyMHz, ...
    'dominantFrequencyMHz',dominantFrequencyMHz, ...
    'requestedFrequencyMHz',requestedFrequencyMHz, ...
    'actualFrequencyMHz',actualFrequencyMHz, ...
    'frequencyErrorKHz',frequencyErrorKHz, ...
    'requestedPhaseStepDegrees',requestedPhaseStepDegrees, ...
    'actualPhaseStepDegrees',actualPhaseStepDegrees, ...
    'referenceAccumulatorPeriodSamples', ...
        referenceAccumulatorPeriodSamples, ...
    'accumulatorPeriodSamples',accumulatorPeriodSamples, ...
    'modeledLookupPairValueCount',2*lookupEntryCount, ...
    'maxRecordSamples',phaseModulus, ...
    'maxLookupEntries',phaseModulus, ...
    'maxLookupPairValues',2*phaseModulus, ...
    'equationText',['phase[n] = mod(phase[0] + n*K, 2^12); ' ...
        'f_out = K*f_s/2^12; address[n] = ' ...
        'floor(phase[n]/2^(12-P)).']);
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && ~isnan(value) && ~isinf(value) && ...
        value == fix(value) && value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P08:InvalidBrokenIncrementTruncation', ...
        'brokenIncrementTruncation must be logical or numeric 0 or 1.');
end
end
