function run_checks
%RUN_CHECKS Verify deterministic NCO recurrences, limits, and fault behavior.
clear model;

%% Exact baseline recurrence, units, lookup, and spectral carrier
baseline = model(411,8,0,false);
expectedPhaseCode = mod((0:4095).'*411,4096);
expectedFirstPhaseCode = [0 411 822 1233 1644 2055 2466 ...
    2877 3288 3699 14 425].';
expectedFirstLookupAddress = [0 25 51 77 102 128 154 179 ...
    205 231 0 26].';
assert(baseline.accumulatorBits == 12 && ...
    baseline.phaseModulus == 4096 && ...
    baseline.recordSampleCount == 4096 && ...
    isequal(baseline.sampleIndex,(0:4095).') && ...
    baseline.sampleTimeMicroseconds(2) == 0.01, ...
    'P08:BaselineShape', ...
    'Baseline accumulator, sample convention, or record shape changed.');
assert(isequal(baseline.referencePhaseCode,expectedPhaseCode) && ...
    isequal(baseline.phaseCode,expectedPhaseCode) && ...
    isequal(baseline.phaseCode(1:12),expectedFirstPhaseCode) && ...
    all(baseline.referencePhaseStepCode == 411) && ...
    all(baseline.phaseStepCode == 411) && ...
    baseline.referenceWrapCount == 411 && ...
    baseline.wrapCount == 411 && ...
    baseline.referenceWithinRecordWrapCount == 410 && ...
    baseline.withinRecordWrapCount == 410 && ...
    baseline.transitionCount == 4096 && ...
    baseline.withinRecordTransitionCount == 4095 && ...
    baseline.referenceTerminalNextPhaseCode == 0 && ...
    baseline.terminalNextPhaseCode == 0, ...
    'P08:BaselineRecurrence', ...
    'The baseline must add the complete tuning word modulo 4096.');
assert(baseline.lookupEntryCount == 256 && ...
    baseline.discardedPhaseBits == 4 && ...
    baseline.phaseTruncationFactor == 16 && ...
    isequal(baseline.lookupAddress, ...
        floor(expectedPhaseCode/16)) && ...
    isequal(baseline.lookupAddress(1:12), ...
        expectedFirstLookupAddress) && ...
    all(baseline.lookupAddress >= 0) && ...
    all(baseline.lookupAddress < 256), ...
    'P08:BaselineLookup', ...
    'The baseline lookup must use the eight most-significant phase bits.');
expectedFrequencyResolutionKHz = 100000/4096;
expectedFrequencyMHz = 411*100/4096;
assert(abs(baseline.frequencyResolutionKHz- ...
        expectedFrequencyResolutionKHz) < 1e-12 && ...
    abs(baseline.requestedFrequencyMHz-expectedFrequencyMHz) < 1e-12 && ...
    abs(baseline.actualFrequencyMHz-expectedFrequencyMHz) < 1e-12 && ...
    baseline.frequencyErrorKHz == 0 && ...
    abs(baseline.requestedPhaseStepDegrees-411*360/4096) < 1e-12 && ...
    baseline.referenceAccumulatorPeriodSamples == 4096 && ...
    baseline.accumulatorPeriodSamples == 4096, ...
    'P08:BaselineFrequency', ...
    'Frequency, phase step, or odd-word period changed.');
expectedMaximumErrorDegrees = 15*360/4096;
expectedRmsErrorDegrees = sqrt(mean((0:15).^2))*360/4096;
assert(isequal(baseline.phaseTruncationErrorCode, ...
        -mod(expectedPhaseCode,16)) && ...
    abs(baseline.maximumPhaseTruncationErrorDegrees- ...
        expectedMaximumErrorDegrees) < 1e-12 && ...
    abs(baseline.phaseTruncationRmsDegrees- ...
        expectedRmsErrorDegrees) < 1e-12 && ...
    max(abs(abs(baseline.complexOutput)-1)) < 1e-12, ...
    'P08:BaselinePhaseError', ...
    'Baseline phase-error distribution or unit-circle output changed.');
assert(baseline.referenceCarrierBinIndex == 412 && ...
    baseline.carrierBinIndex == 412 && ...
    baseline.referenceDominantBinIndex == 412 && ...
    baseline.dominantBinIndex == 412 && ...
    abs(baseline.dominantFrequencyMHz-expectedFrequencyMHz) < 1e-12 && ...
    baseline.carrierMagnitude > baseline.largestSpurMagnitude && ...
    baseline.spectralNumericalFloorDbc == -240 && ...
    ~baseline.spectralFloorLimited && ...
    abs(baseline.recordSfdrDb-48.07535746411204) < 1e-9, ...
    'P08:BaselineSpectrum', ...
    'The coherent record carrier must remain at tuning-word bin 411.');

%% Accepted numeric classes normalize to the same deterministic result
typedBaseline = model(uint16(411),uint8(8),uint16(0),uint8(0));
assert(isequaln(typedBaseline,baseline), ...
    'P08:NumericClassNormalization', ...
    'Accepted integer classes must normalize to the double/logical result.');

%% Sweep 1 - tuning word with lookup and allocation held fixed
tuningWords = [0 1 64 128 256 411 512 1024 2047];
expectedFrequenciesMHz = tuningWords*100/4096;
observedFrequenciesMHz = zeros(size(tuningWords));
observedDominantFrequenciesMHz = zeros(size(tuningWords));
observedWrapCounts = zeros(size(tuningWords));
observedWithinRecordWrapCounts = zeros(size(tuningWords));
observedPeriods = zeros(size(tuningWords));
for sweepIndex = 1:numel(tuningWords)
    tuningWord = tuningWords(sweepIndex);
    current = model(tuningWord,8,0,false);
    expectedCurrentPhase = mod((0:4095).'*tuningWord,4096);
    assert(current.phaseAddressBits == 8 && ...
        current.lookupEntryCount == 256 && ...
        current.modeledLookupPairValueCount == 512 && ...
        current.initialPhaseCode == 0 && ...
        current.recordSampleCount == 4096 && ...
        current.sampleClockMHz == 100 && ...
        ~current.brokenIncrementTruncation, ...
        'P08:TuningSweepIsolation', ...
        'Tuning sweep must preserve lookup, phase offset, clock, and record.');
    assert(isequal(current.phaseCode,expectedCurrentPhase) && ...
        all(current.phaseStepCode == tuningWord) && ...
        current.wrapCount == tuningWord && ...
        current.withinRecordWrapCount == max(tuningWord-1,0) && ...
        current.effectiveTuningWord == tuningWord && ...
        current.frequencyErrorKHz == 0 && ...
        current.dominantBinIndex == tuningWord+1, ...
        'P08:TuningSweep', ...
        'Healthy tuning must control recurrence, wraps, and carrier bin.');
    if tuningWord == 0
        expectedPeriod = 1;
    else
        expectedPeriod = 4096/gcd(4096,tuningWord);
    end
    assert(current.accumulatorPeriodSamples == expectedPeriod, ...
        'P08:TuningPeriod', ...
        'Accumulator period must follow 4096/gcd(4096,K).');
    observedFrequenciesMHz(sweepIndex) = current.actualFrequencyMHz;
    observedDominantFrequenciesMHz(sweepIndex) = ...
        current.dominantFrequencyMHz;
    observedWrapCounts(sweepIndex) = current.wrapCount;
    observedWithinRecordWrapCounts(sweepIndex) = ...
        current.withinRecordWrapCount;
    observedPeriods(sweepIndex) = current.accumulatorPeriodSamples;
end
assert(max(abs(observedFrequenciesMHz-expectedFrequenciesMHz)) < 1e-12 && ...
    max(abs(observedDominantFrequenciesMHz- ...
        expectedFrequenciesMHz)) < 1e-12 && ...
    isequal(observedWrapCounts,tuningWords) && ...
    isequal(observedWithinRecordWrapCounts, ...
        [0 0 63 127 255 410 511 1023 2046]) && ...
    isequal(observedPeriods,[1 4096 64 32 16 4096 8 4 4096]), ...
    'P08:TuningSweepLimits', ...
    'Tuning-word sweep endpoints or periods changed.');

%% DC, minimum-frequency, quarter-rate, and high-frequency limits
dc = model(0,8,777,false);
assert(all(dc.phaseCode == 777) && ...
    all(dc.lookupAddress == floor(777/16)) && ...
    all(dc.complexOutput == dc.complexOutput(1)) && ...
    dc.actualFrequencyMHz == 0 && ...
    dc.wrapCount == 0 && ...
    dc.withinRecordWrapCount == 0 && ...
    dc.accumulatorPeriodSamples == 1 && ...
    dc.dominantBinIndex == 1, ...
    'P08:DcLimit', ...
    'K=0 must hold phase and produce a constant complex output.');
minimumFrequency = model(1,8,0,false);
assert(minimumFrequency.actualFrequencyMHz == 100/4096 && ...
    minimumFrequency.wrapCount == 1 && ...
    minimumFrequency.withinRecordWrapCount == 0 && ...
    minimumFrequency.accumulatorPeriodSamples == 4096, ...
    'P08:MinimumFrequencyLimit', ...
    'K=1 must produce the minimum positive tuning step.');
quarterRate = model(1024,8,0,false);
expectedQuarterPhase = repmat([0; 1024; 2048; 3072],1024,1);
expectedQuarterOutput = repmat([1; 1i; -1; -1i],1024,1);
assert(isequal(quarterRate.phaseCode,expectedQuarterPhase) && ...
    max(abs(quarterRate.complexOutput-expectedQuarterOutput)) < 1e-12 && ...
    quarterRate.actualFrequencyMHz == 25 && ...
    quarterRate.accumulatorPeriodSamples == 4 && ...
    quarterRate.wrapCount == 1024 && ...
    quarterRate.withinRecordWrapCount == 1023, ...
    'P08:QuarterRateLimit', ...
    'K=1024 must advance one quarter turn per sample.');
highestFrequency = model(2047,8,0,false);
assert(highestFrequency.actualFrequencyMHz == 2047*100/4096 && ...
    highestFrequency.actualFrequencyMHz < 50 && ...
    highestFrequency.dominantBinIndex == 2048 && ...
    highestFrequency.wrapCount == 2047 && ...
    highestFrequency.withinRecordWrapCount == 2046, ...
    'P08:HighestFrequencyLimit', ...
    'The bounded tuning range must stop one code below Nyquist.');

%% Sweep 2 - lookup phase-address width with full phase held fixed
phaseAddressWidths = 3:12;
observedEntries = zeros(size(phaseAddressWidths));
observedMaximumErrors = zeros(size(phaseAddressWidths));
observedRmsErrors = zeros(size(phaseAddressWidths));
observedWaveformErrors = zeros(size(phaseAddressWidths));
for sweepIndex = 1:numel(phaseAddressWidths)
    phaseAddressBits = phaseAddressWidths(sweepIndex);
    current = model(411,phaseAddressBits,0,false);
    truncationFactor = 2^(12-phaseAddressBits);
    expectedAddress = floor(expectedPhaseCode/truncationFactor);
    expectedErrorCode = -mod(expectedPhaseCode,truncationFactor);
    expectedMaximumError = (truncationFactor-1)*360/4096;
    expectedRmsError = ...
        sqrt(mean((0:truncationFactor-1).^2))*360/4096;
    assert(current.tuningWord == 411 && ...
        current.effectiveTuningWord == 411 && ...
        current.initialPhaseCode == 0 && ...
        current.sampleClockMHz == 100 && ...
        current.recordSampleCount == 4096 && ...
        current.requestedFrequencyMHz == expectedFrequencyMHz && ...
        current.actualFrequencyMHz == expectedFrequencyMHz && ...
        isequal(current.phaseCode,expectedPhaseCode), ...
        'P08:AddressSweepIsolation', ...
        'Address-width sweep must preserve accumulator phase and frequency.');
    assert(current.lookupEntryCount == 2^phaseAddressBits && ...
        current.phaseTruncationFactor == truncationFactor && ...
        isequal(current.lookupAddress,expectedAddress) && ...
        isequal(current.phaseTruncationErrorCode,expectedErrorCode) && ...
        abs(current.maximumPhaseTruncationErrorDegrees- ...
            expectedMaximumError) < 1e-12 && ...
        abs(current.phaseTruncationRmsDegrees-expectedRmsError) < 1e-12, ...
        'P08:AddressSweep', ...
        'Lookup address and phase error must follow P exactly.');
    observedEntries(sweepIndex) = current.lookupEntryCount;
    observedMaximumErrors(sweepIndex) = ...
        current.maximumPhaseTruncationErrorDegrees;
    observedRmsErrors(sweepIndex) = current.phaseTruncationRmsDegrees;
    observedWaveformErrors(sweepIndex) = current.waveformRmsError;
end
assert(isequal(observedEntries,2.^phaseAddressWidths) && ...
    all(diff(observedEntries) > 0) && ...
    all(diff(observedMaximumErrors) <= 0) && ...
    all(diff(observedRmsErrors) <= 0) && ...
    all(diff(observedWaveformErrors) <= 1e-15), ...
    'P08:AddressSweepLimits', ...
    'Lookup growth and phase/waveform error must move monotonically.');
fullAddress = model(411,12,0,false);
assert(fullAddress.lookupEntryCount == 4096 && ...
    fullAddress.phaseTruncationFactor == 1 && ...
    isequal(fullAddress.lookupAddress,fullAddress.phaseCode) && ...
    all(fullAddress.phaseTruncationErrorCode == 0) && ...
    fullAddress.maximumPhaseTruncationErrorDegrees == 0 && ...
    fullAddress.phaseTruncationRmsDegrees == 0 && ...
    fullAddress.waveformRmsError == 0 && ...
    fullAddress.spectralFloorLimited && ...
    isinf(fullAddress.recordSfdrDb) && ...
    fullAddress.largestSpurMagnitude <= ...
        fullAddress.spectralFloorMagnitude, ...
    'P08:FullAddressLimit', ...
    'P=12 must expose every accumulator phase code without truncation.');

%% Deliberately broken increment truncation and exact carrier symptom
healthy = model(411,8,0,false);
broken = model(411,8,0,true);
expectedBrokenPhaseCode = mod((0:4095).'*400,4096);
assert(broken.brokenIncrementTruncation && ...
    broken.faultCanChangeFrequency && ...
    broken.faultActive && ...
    broken.effectiveTuningWord == 400 && ...
    broken.discardedTuningWordCode == 11 && ...
    all(broken.phaseStepCode == 400) && ...
    isequal(broken.phaseCode,expectedBrokenPhaseCode), ...
    'P08:BrokenIncrement', ...
    'Broken mode must remove the exact low four tuning-word bits.');
assert(abs(broken.requestedFrequencyMHz-10.0341796875) < 1e-12 && ...
    abs(broken.actualFrequencyMHz-9.765625) < 1e-12 && ...
    abs(broken.frequencyErrorKHz+268.5546875) < 1e-12 && ...
    broken.referenceCarrierBinIndex == 412 && ...
    broken.carrierBinIndex == 401 && ...
    broken.referenceDominantBinIndex == 412 && ...
    broken.dominantBinIndex == 401 && ...
    broken.referenceWrapCount == 411 && ...
    broken.wrapCount == 400 && ...
    broken.referenceWithinRecordWrapCount == 410 && ...
    broken.withinRecordWrapCount == 399 && ...
    broken.referenceTerminalNextPhaseCode == 0 && ...
    broken.terminalNextPhaseCode == 0 && ...
    broken.referenceAccumulatorPeriodSamples == 4096 && ...
    broken.accumulatorPeriodSamples == 256, ...
    'P08:BrokenFrequency', ...
    'Premature truncation must move the carrier by negative eleven bins.');
assert(isequal(broken.referencePhaseCode,healthy.referencePhaseCode) && ...
    isequal(broken.referenceLookupAddress, ...
        healthy.referenceLookupAddress) && ...
    isequal(broken.referenceComplexOutput, ...
        healthy.referenceComplexOutput) && ...
    broken.lookupEntryCount == healthy.lookupEntryCount && ...
    broken.recordSampleCount == healthy.recordSampleCount && ...
    broken.sampleClockMHz == healthy.sampleClockMHz, ...
    'P08:BrokenIsolation', ...
    'The fault must preserve reference behavior, lookup size, and bounds.');

%% Inert fault limits and deterministic recovery
divisibleHealthy = model(512,8,0,false);
divisibleBroken = model(512,8,0,true);
zeroHealthy = model(0,3,901,false);
zeroBroken = model(0,3,901,true);
fullWidthHealthy = model(411,12,0,false);
fullWidthBroken = model(411,12,0,true);
assert(~divisibleBroken.faultActive && ...
    isequaln(divisibleBroken,withFaultFlag(divisibleHealthy,true)) && ...
    ~zeroBroken.faultActive && ...
    isequaln(zeroBroken,withFaultFlag(zeroHealthy,true)) && ...
    ~fullWidthBroken.faultActive && ...
    isequaln(fullWidthBroken,withFaultFlag(fullWidthHealthy,true)), ...
    'P08:BrokenInertLimits', ...
    'Fault must be behaviorally inert when no tuning bits are removed.');

%% Representative healthy/fault grid and fixed resource bounds
gridTuningWords = [0 1 15 16 17 255 256 411 512 1024 2047];
for tuningIndex = 1:numel(gridTuningWords)
    tuningWord = gridTuningWords(tuningIndex);
    for phaseAddressBits = 3:12
        healthyGrid = model(tuningWord,phaseAddressBits,4095,false);
        brokenGrid = model(tuningWord,phaseAddressBits,4095,true);
        truncationFactor = 2^(12-phaseAddressBits);
        expectedEffectiveWord = ...
            floor(tuningWord/truncationFactor)*truncationFactor;
        expectedHealthyPhase = mod(4095+(0:4095).'*tuningWord,4096);
        expectedBrokenPhase = ...
            mod(4095+(0:4095).'*expectedEffectiveWord,4096);
        assert(isequal(healthyGrid.phaseCode,expectedHealthyPhase) && ...
            healthyGrid.effectiveTuningWord == tuningWord && ...
            healthyGrid.frequencyErrorKHz == 0 && ...
            all(healthyGrid.lookupAddress >= 0) && ...
            all(healthyGrid.lookupAddress < healthyGrid.lookupEntryCount), ...
            'P08:HealthyGrid', ...
            'Healthy representative controls changed recurrence or bounds.');
        assert(brokenGrid.effectiveTuningWord == expectedEffectiveWord && ...
            brokenGrid.discardedTuningWordCode == ...
                tuningWord-expectedEffectiveWord && ...
            isequal(brokenGrid.phaseCode,expectedBrokenPhase) && ...
            isequal(brokenGrid.referencePhaseCode, ...
                healthyGrid.referencePhaseCode) && ...
            brokenGrid.actualFrequencyMHz <= ...
                brokenGrid.requestedFrequencyMHz, ...
            'P08:BrokenGrid', ...
            'Broken representative controls changed the truncation rule.');
        if mod(tuningWord,truncationFactor) == 0
            assert(~brokenGrid.faultActive && ...
                isequal(brokenGrid.phaseCode,healthyGrid.phaseCode) && ...
                isequal(brokenGrid.complexOutput,healthyGrid.complexOutput), ...
                'P08:BrokenGridInert', ...
                'Representable tuning words must be inert in broken mode.');
        else
            assert(brokenGrid.faultActive && ...
                brokenGrid.actualFrequencyMHz < ...
                    brokenGrid.requestedFrequencyMHz && ...
                brokenGrid.dominantBinIndex == expectedEffectiveWord+1, ...
                'P08:BrokenGridActive', ...
                'Removed low tuning bits must lower the modeled carrier.');
        end
        assert(healthyGrid.recordSampleCount == 4096 && ...
            brokenGrid.recordSampleCount == 4096 && ...
            healthyGrid.lookupEntryCount <= 4096 && ...
            brokenGrid.lookupEntryCount <= 4096 && ...
            numel(healthyGrid.lookupCosineTable) <= 4096 && ...
            numel(healthyGrid.lookupSineTable) <= 4096 && ...
            numel(healthyGrid.spectrumMagnitude) == 4096 && ...
            healthyGrid.modeledLookupPairValueCount <= 8192 && ...
            healthyGrid.maxRecordSamples == 4096 && ...
            healthyGrid.maxLookupEntries == 4096 && ...
            healthyGrid.maxLookupPairValues == 8192, ...
            'P08:ResourceBound', ...
            'The fixed record or lookup allocation bound changed.');
    end
end

%% Initial-phase isolation
zeroPhase = model(411,8,0,false);
quarterTurnPhase = model(411,8,1024,false);
assert(isequal(quarterTurnPhase.phaseCode, ...
        mod(zeroPhase.phaseCode+1024,4096)) && ...
    quarterTurnPhase.tuningWord == zeroPhase.tuningWord && ...
    quarterTurnPhase.effectiveTuningWord == zeroPhase.effectiveTuningWord && ...
    quarterTurnPhase.requestedFrequencyMHz == ...
        zeroPhase.requestedFrequencyMHz && ...
    quarterTurnPhase.actualFrequencyMHz == zeroPhase.actualFrequencyMHz && ...
    quarterTurnPhase.lookupEntryCount == zeroPhase.lookupEntryCount && ...
    quarterTurnPhase.recordSampleCount == zeroPhase.recordSampleCount && ...
    max(abs(quarterTurnPhase.spectrumMagnitude- ...
        zeroPhase.spectrumMagnitude)) < 1e-12, ...
    'P08:InitialPhaseIsolation', ...
    'Initial phase must rotate phase without changing frequency/resources.');

%% Initial phase moves a wrap between stored and terminal transitions
initialPhaseCases = [0 399 400 410 411 1024 4095];
for phaseIndex = 1:numel(initialPhaseCases)
    initialPhaseCode = initialPhaseCases(phaseIndex);
    current = model(411,8,initialPhaseCode,true);
    expectedReferenceTerminalWrap = initialPhaseCode < 411;
    expectedAppliedTerminalWrap = initialPhaseCode < 400;
    assert(current.referenceWrapCount == 411 && ...
        current.wrapCount == 400 && ...
        current.referenceWrapEvent(end) == ...
            expectedReferenceTerminalWrap && ...
        current.wrapEvent(end) == expectedAppliedTerminalWrap && ...
        current.referenceWithinRecordWrapCount == ...
            411-double(expectedReferenceTerminalWrap) && ...
        current.withinRecordWrapCount == ...
            400-double(expectedAppliedTerminalWrap) && ...
        current.referenceWithinRecordWrapCount+ ...
            double(current.referenceWrapEvent(end)) == ...
            current.referenceWrapCount && ...
        current.withinRecordWrapCount+double(current.wrapEvent(end)) == ...
            current.wrapCount && ...
        current.referenceTerminalNextPhaseCode == initialPhaseCode && ...
        current.terminalNextPhaseCode == initialPhaseCode, ...
        'P08:InitialPhaseWrapPartition', ...
        ['Initial phase may move one wrap between adjacent stored states ' ...
        'and the terminal transition, but it must not change total wraps.']);
end

%% Malformed inputs and post-failure recovery
assertRejects(@() model(-1,8,0,false),'P08:InvalidTuningWord');
assertRejects(@() model(2048,8,0,false),'P08:InvalidTuningWord');
assertRejects(@() model(411.5,8,0,false),'P08:InvalidTuningWord');
assertRejects(@() model([411 412],8,0,false),'P08:InvalidTuningWord');
assertRejects(@() model(NaN,8,0,false),'P08:InvalidTuningWord');
assertRejects(@() model(Inf,8,0,false),'P08:InvalidTuningWord');
assertRejects(@() model(411+1i,8,0,false),'P08:InvalidTuningWord');
assertRejects(@() model(true,8,0,false),'P08:InvalidTuningWord');
assertRejects(@() model(411,2,0,false), ...
    'P08:InvalidPhaseAddressBits');
assertRejects(@() model(411,13,0,false), ...
    'P08:InvalidPhaseAddressBits');
assertRejects(@() model(411,8.5,0,false), ...
    'P08:InvalidPhaseAddressBits');
assertRejects(@() model(411,[8 9],0,false), ...
    'P08:InvalidPhaseAddressBits');
assertRejects(@() model(411,NaN,0,false), ...
    'P08:InvalidPhaseAddressBits');
assertRejects(@() model(411,Inf,0,false), ...
    'P08:InvalidPhaseAddressBits');
assertRejects(@() model(411,8+1i,0,false), ...
    'P08:InvalidPhaseAddressBits');
assertRejects(@() model(411,true,0,false), ...
    'P08:InvalidPhaseAddressBits');
assertRejects(@() model(411,8,-1,false), ...
    'P08:InvalidInitialPhaseCode');
assertRejects(@() model(411,8,4096,false), ...
    'P08:InvalidInitialPhaseCode');
assertRejects(@() model(411,8,0.5,false), ...
    'P08:InvalidInitialPhaseCode');
assertRejects(@() model(411,8,[0 1],false), ...
    'P08:InvalidInitialPhaseCode');
assertRejects(@() model(411,8,NaN,false), ...
    'P08:InvalidInitialPhaseCode');
assertRejects(@() model(411,8,Inf,false), ...
    'P08:InvalidInitialPhaseCode');
assertRejects(@() model(411,8,1i,false), ...
    'P08:InvalidInitialPhaseCode');
assertRejects(@() model(411,8,true,false), ...
    'P08:InvalidInitialPhaseCode');
assertRejects(@() model(411,8,0,2), ...
    'P08:InvalidBrokenIncrementTruncation');
assertRejects(@() model(411,8,0,0.5), ...
    'P08:InvalidBrokenIncrementTruncation');
assertRejects(@() model(411,8,0,[false true]), ...
    'P08:InvalidBrokenIncrementTruncation');
assertRejects(@() model(411,8,0,NaN), ...
    'P08:InvalidBrokenIncrementTruncation');
assertRejects(@() model(411,8,0,Inf), ...
    'P08:InvalidBrokenIncrementTruncation');
assertRejects(@() model(411,8,0,1+1i), ...
    'P08:InvalidBrokenIncrementTruncation');
baselineAfterFailures = model(411,8,0,false);
maximumFault = model(2047,3,4095,true); %#ok<NASGU>
baselineAfterOtherCall = model(411,8,0,false);
assert(isequaln(baseline,baselineAfterFailures) && ...
    isequaln(baseline,baselineAfterOtherCall), ...
    'P08:DeterminismRecovery', ...
    'Valid baseline output must recover after failures and unrelated calls.');

disp(['P08 checks passed: recurrence, frequency, lookup precision, ' ...
    'broken tuning, validation, isolation, resource bounds, and recovery.']);
end

function changed = withFaultFlag(original,value)
changed = original;
changed.brokenIncrementTruncation = logical(value);
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P08:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
