function out = model(requiredHigh,inputHighProbability,selectedAddress,faultAddress)
%MODEL Evaluate a transparent three-input truth table and its LUT copy.
%   Inputs A, B, and C form address 4*A + 2*B + C. The specification is
%   a k-of-3 vote: Y is HIGH when at least requiredHigh inputs are HIGH.
%   inputHighProbability weights rows under the stated assumption that the
%   three inputs are independent and have the same probability of being HIGH.
%   faultAddress is -1 for a correct LUT or 0..7 to flip one LUT entry.

if nargin < 1
    requiredHigh = 2;
end
if nargin < 2
    inputHighProbability = 0.5;
end
if nargin < 3
    selectedAddress = 3;
end
if nargin < 4
    faultAddress = -1;
end

validateIntegerScalar(requiredHigh,1,3,'P02:InvalidRequiredHigh','requiredHigh');
validateProbability(inputHighProbability);
validateIntegerScalar(selectedAddress,0,7,'P02:InvalidSelectedAddress','selectedAddress');
validateIntegerScalar(faultAddress,-1,7,'P02:InvalidFaultAddress','faultAddress');

inputAddress = (0:7).';
inputBits = logical([bitget(inputAddress,3), ...
    bitget(inputAddress,2),bitget(inputAddress,1)]);
highCount = sum(inputBits,2);

specifiedOutput = highCount >= requiredHigh;
lutOutput = specifiedOutput;
if faultAddress >= 0
    lutOutput(faultAddress + 1) = ~lutOutput(faultAddress + 1);
end

A = inputBits(:,1);
B = inputBits(:,2);
C = inputBits(:,3);
switch requiredHigh
    case 1
        equationOutput = A | B | C;
        equationText = 'Y = A OR B OR C';
    case 2
        equationOutput = (A & B) | (A & C) | (B & C);
        equationText = 'Y = (A AND B) OR (A AND C) OR (B AND C)';
    case 3
        equationOutput = A & B & C;
        equationText = 'Y = A AND B AND C';
end

p = inputHighProbability;
rowProbability = (p .^ highCount) .* ((1-p) .^ (3-highCount));
mismatchMask = xor(specifiedOutput,lutOutput);
selectedRow = selectedAddress + 1;
inputLabels = cell(8,1);
for row = 1:8
    inputLabels{row} = sprintf('%d%d%d',inputBits(row,1), ...
        inputBits(row,2),inputBits(row,3));
end

out = struct( ...
    'requiredHigh',requiredHigh, ...
    'inputHighProbability',inputHighProbability, ...
    'selectedAddress',selectedAddress, ...
    'faultAddress',faultAddress, ...
    'inputAddress',inputAddress, ...
    'inputBits',inputBits, ...
    'inputLabels',{inputLabels}, ...
    'highCount',highCount, ...
    'specifiedOutput',specifiedOutput, ...
    'lutOutput',lutOutput, ...
    'equationOutput',equationOutput, ...
    'equationText',equationText, ...
    'rowProbability',rowProbability, ...
    'mismatchMask',mismatchMask, ...
    'mismatchAddresses',inputAddress(mismatchMask), ...
    'mismatchCount',sum(mismatchMask), ...
    'assertedRowCount',sum(specifiedOutput), ...
    'assertedRowFraction',mean(specifiedOutput), ...
    'specifiedHighProbability',sum(rowProbability(specifiedOutput)), ...
    'lutHighProbability',sum(rowProbability(lutOutput)), ...
    'mismatchProbability',sum(rowProbability(mismatchMask)), ...
    'selectedBits',inputBits(selectedRow,:), ...
    'selectedSpecifiedOutput',specifiedOutput(selectedRow), ...
    'selectedLutOutput',lutOutput(selectedRow), ...
    'selectedMatches',~mismatchMask(selectedRow), ...
    'truthTable',[inputAddress,double(inputBits),highCount, ...
        double(specifiedOutput),double(lutOutput),double(mismatchMask)]);
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
        ~isnan(value) && ~isinf(value) && value == fix(value) && ...
        value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateProbability(value)
if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
        ~isnan(value) && ~isinf(value) && value >= 0 && value <= 1)
    error('P02:InvalidInputHighProbability', ...
        'inputHighProbability must be a finite real scalar in [0, 1].');
end
end
