function out = model(completionDelay,timeoutLimit,selectedCycle,brokenPriority)
%MODEL Simulate a bounded command-controller finite-state machine.
%   Inputs are sampled immediately before each rising edge. State and Moore
%   outputs are observed immediately after it. The healthy WAIT transition
%   gives completion priority over an expiration on the same edge. The
%   deliberately broken mode reverses only that contested priority.

if nargin < 1
    completionDelay = 3;
end
if nargin < 2
    timeoutLimit = 5;
end
if nargin < 3
    selectedCycle = 5;
end
if nargin < 4
    brokenPriority = false;
end

validateIntegerScalar(completionDelay,1,8, ...
    'P04:InvalidCompletionDelay','completionDelay');
validateIntegerScalar(timeoutLimit,1,8, ...
    'P04:InvalidTimeoutLimit','timeoutLimit');
validateIntegerScalar(selectedCycle,1,16, ...
    'P04:InvalidSelectedCycle','selectedCycle');
validateBooleanScalar(brokenPriority);
brokenPriority = logical(brokenPriority);

IDLE = 0;
WAIT = 1;
DONE = 2;
TIMEOUT = 3;
stateCodes = [IDLE WAIT DONE TIMEOUT];
stateLabels = {'IDLE','WAIT','DONE','TIMEOUT'};
stateCount = numel(stateCodes);
modeledStateBits = ceil(log2(stateCount));

cycle = (1:16).';
cycleCount = numel(cycle);
startCycle = 2;
reset = cycle == 1;
start = cycle == startCycle;
workDone = cycle == startCycle + completionDelay;
deadlineExpired = cycle == startCycle + timeoutLimit;

stateBefore = zeros(cycleCount,1);
stateAfter = zeros(cycleCount,1);
referenceStateBefore = zeros(cycleCount,1);
referenceStateAfter = zeros(cycleCount,1);
transitionReason = cell(cycleCount,1);
referenceTransitionReason = cell(cycleCount,1);
previousState = IDLE;
previousReferenceState = IDLE;

for cycleIndex = 1:cycleCount
    stateBefore(cycleIndex) = previousState;
    referenceStateBefore(cycleIndex) = previousReferenceState;
    if reset(cycleIndex)
        nextState = IDLE;
        correctNextState = IDLE;
        reason = 'reset to IDLE';
        correctReason = reason;
    else
        [nextState,reason] = advanceState(previousState, ...
            start(cycleIndex),workDone(cycleIndex), ...
            deadlineExpired(cycleIndex),brokenPriority, ...
            IDLE,WAIT,DONE,TIMEOUT);
        [correctNextState,correctReason] = advanceState( ...
            previousReferenceState,start(cycleIndex), ...
            workDone(cycleIndex),deadlineExpired(cycleIndex),false, ...
            IDLE,WAIT,DONE,TIMEOUT);
    end
    stateAfter(cycleIndex) = nextState;
    referenceStateAfter(cycleIndex) = correctNextState;
    transitionReason{cycleIndex} = reason;
    referenceTransitionReason{cycleIndex} = correctReason;
    previousState = nextState;
    previousReferenceState = correctNextState;
end

busy = stateAfter == WAIT;
donePulse = stateAfter == DONE;
timeoutPulse = stateAfter == TIMEOUT;
terminalEntry = donePulse | timeoutPulse;
terminalCycle = find(terminalEntry,1,'first');
referenceDonePulse = referenceStateAfter == DONE;
referenceTimeoutPulse = referenceStateAfter == TIMEOUT;
mismatchMask = stateAfter ~= referenceStateAfter;
wrongTimeoutMask = timeoutPulse & referenceDonePulse;
mismatchCycles = cycle(mismatchMask);
firstMismatchCycle = find(mismatchMask,1,'first');
lateWorkDoneMask = workDone & stateBefore ~= WAIT;
lateDeadlineMask = deadlineExpired & stateBefore ~= WAIT;
stateName = stateLabels(stateAfter+1);
referenceStateName = stateLabels(referenceStateAfter+1);
terminalStateName = stateLabels{stateAfter(terminalCycle)+1};

out = struct( ...
    'completionDelay',completionDelay, ...
    'timeoutLimit',timeoutLimit, ...
    'brokenPriority',brokenPriority, ...
    'cycle',cycle, ...
    'cycleCount',cycleCount, ...
    'startCycle',startCycle, ...
    'reset',reset, ...
    'start',start, ...
    'workDone',workDone, ...
    'deadlineExpired',deadlineExpired, ...
    'stateCodes',stateCodes, ...
    'stateLabels',{stateLabels}, ...
    'stateCount',stateCount, ...
    'modeledStateBits',modeledStateBits, ...
    'stateBefore',stateBefore, ...
    'stateAfter',stateAfter, ...
    'stateName',{stateName}, ...
    'referenceStateBefore',referenceStateBefore, ...
    'referenceStateAfter',referenceStateAfter, ...
    'referenceStateName',{referenceStateName}, ...
    'transitionReason',{transitionReason}, ...
    'referenceTransitionReason',{referenceTransitionReason}, ...
    'busy',busy, ...
    'donePulse',donePulse, ...
    'timeoutPulse',timeoutPulse, ...
    'referenceDonePulse',referenceDonePulse, ...
    'referenceTimeoutPulse',referenceTimeoutPulse, ...
    'inputMatrix',[reset start workDone deadlineExpired], ...
    'outputMatrix',[busy donePulse timeoutPulse], ...
    'terminalEntry',terminalEntry, ...
    'terminalCycle',terminalCycle, ...
    'terminalStateName',terminalStateName, ...
    'busyCycleCount',sum(busy), ...
    'completionCount',sum(donePulse), ...
    'timeoutCount',sum(timeoutPulse), ...
    'success',any(donePulse), ...
    'expectedSuccess',completionDelay <= timeoutLimit, ...
    'mismatchMask',mismatchMask, ...
    'mismatchCycles',mismatchCycles, ...
    'mismatchCount',sum(mismatchMask), ...
    'firstMismatchCycle',firstMismatchCycle, ...
    'wrongTimeoutMask',wrongTimeoutMask, ...
    'wrongTimeoutCount',sum(wrongTimeoutMask), ...
    'lateWorkDoneMask',lateWorkDoneMask, ...
    'lateDeadlineMask',lateDeadlineMask, ...
    'ignoredLateWorkDoneCount',sum(lateWorkDoneMask), ...
    'ignoredLateDeadlineCount',sum(lateDeadlineMask), ...
    'selectedCycle',selectedCycle, ...
    'selectedReset',reset(selectedCycle), ...
    'selectedStart',start(selectedCycle), ...
    'selectedWorkDone',workDone(selectedCycle), ...
    'selectedDeadlineExpired',deadlineExpired(selectedCycle), ...
    'selectedStateBefore',stateLabels{stateBefore(selectedCycle)+1}, ...
    'selectedStateAfter',stateLabels{stateAfter(selectedCycle)+1}, ...
    'selectedTransitionReason',transitionReason{selectedCycle}, ...
    'selectedBusy',busy(selectedCycle), ...
    'selectedDone',donePulse(selectedCycle), ...
    'selectedTimeout',timeoutPulse(selectedCycle), ...
    'selectedMismatch',mismatchMask(selectedCycle), ...
    'equationText',['stateAfter(n) = delta(stateBefore(n), inputs(n)); ' ...
        'Moore outputs decode stateAfter(n).']);
end

function [nextState,reason] = advanceState(currentState,start,workDone, ...
        deadlineExpired,brokenPriority,IDLE,WAIT,DONE,TIMEOUT)
nextState = currentState;
reason = 'hold current state';
if currentState == IDLE
    if start
        nextState = WAIT;
        reason = 'start accepted: IDLE to WAIT';
    else
        reason = 'IDLE waits for start';
    end
elseif currentState == WAIT
    if brokenPriority
        if deadlineExpired
            nextState = TIMEOUT;
            reason = 'broken priority: deadline wins';
        elseif workDone
            nextState = DONE;
            reason = 'work completed';
        else
            reason = 'WAIT for completion or deadline';
        end
    else
        if workDone
            nextState = DONE;
            reason = 'completion wins: WAIT to DONE';
        elseif deadlineExpired
            nextState = TIMEOUT;
            reason = 'deadline expires: WAIT to TIMEOUT';
        else
            reason = 'WAIT for completion or deadline';
        end
    end
elseif currentState == DONE || currentState == TIMEOUT
    nextState = IDLE;
    reason = 'terminal pulse complete: recover to IDLE';
else
    error('P04:InternalInvalidState','Encountered an invalid state code.');
end
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
        ~isnan(value) && ~isinf(value) && value == fix(value) && ...
        value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P04:InvalidBrokenPriority', ...
        'brokenPriority must be a logical scalar or numeric 0 or 1.');
end
end
