function run_checks
%RUN_CHECKS Execute independent P04 FSM behavior and boundary checks.
clear model;

%% Baseline state trace, input timing, and Moore output decode
baseline = model(3,5,5,false);
expectedState = [0 1 1 1 2 zeros(1,11)].';
assert(isequal(baseline.stateAfter,expectedState), ...
    'P04:BaselineStateTrace','The deterministic baseline state trace changed.');
assert(isequal(find(baseline.reset),1) && ...
    isequal(find(baseline.start),2) && ...
    isequal(find(baseline.workDone),5) && ...
    isequal(find(baseline.deadlineExpired),7), ...
    'P04:BaselineInputTiming','The deterministic input pulse timing changed.');
assert(isequal(find(baseline.busy),(2:4).') && ...
    isequal(find(baseline.donePulse),5) && ...
    ~any(baseline.timeoutPulse), ...
    'P04:BaselineOutputs','Baseline Moore outputs decode the wrong states.');
assert(baseline.terminalCycle == 5 && baseline.busyCycleCount == 3 && ...
    baseline.success && strcmp(baseline.terminalStateName,'DONE'), ...
    'P04:BaselineMetrics','Baseline latency or outcome metrics changed.');
assert(baseline.stateBefore(5) == 1 && baseline.stateAfter(5) == 2 && ...
    baseline.workDone(5) && ~baseline.deadlineExpired(5), ...
    'P04:PrePostEdgeConvention', ...
    'Completion must be sampled in WAIT and produce post-edge DONE.');
assert(baseline.stateAfter(6) == 0 && baseline.donePulse(5) && ...
    ~baseline.donePulse(6), ...
    'P04:TerminalRecovery','DONE must be a one-cycle state before IDLE recovery.');
assert(baseline.deadlineExpired(7) && baseline.stateBefore(7) == 0 && ...
    baseline.stateAfter(7) == 0 && baseline.ignoredLateDeadlineCount == 1, ...
    'P04:LateDeadlineIgnored', ...
    'A deadline arriving after completion must not restart a transition.');
assert(all(sum(baseline.outputMatrix,2) <= 1), ...
    'P04:MutuallyExclusiveOutputs', ...
    'Busy, done, and timeout Moore outputs must be mutually exclusive.');

%% Sweep 1 limits - change only completion delay
completionDelays = 1:8;
busyCounts = zeros(size(completionDelays));
terminalCycles = zeros(size(completionDelays));
for sweepIndex = 1:numel(completionDelays)
    completionDelay = completionDelays(sweepIndex);
    current = model(completionDelay,8,5,false);
    assert(current.timeoutLimit == 8 && ...
        isequal(current.deadlineExpired,cyclePulse(10)), ...
        'P04:CompletionSweepIsolation', ...
        'Completion-delay sweep must preserve timeout limit and pulse.');
    assert(current.success && current.completionCount == 1 && ...
        current.timeoutCount == 0, ...
        'P04:CompletionSweepOutcome', ...
        'Completion delays through the inclusive deadline must succeed.');
    busyCounts(sweepIndex) = current.busyCycleCount;
    terminalCycles(sweepIndex) = current.terminalCycle;
end
assert(isequal(busyCounts,1:8) && isequal(terminalCycles,3:10), ...
    'P04:CompletionSweep','Completion-delay limits changed.');

%% Sweep 2 limits - change only timeout limit
timeoutLimits = 1:8;
expectedTimeouts = [1 1 1 0 0 0 0 0];
expectedTerminalCycles = [3 4 5 6 6 6 6 6];
expectedBusyCounts = [1 2 3 4 4 4 4 4];
observedTimeouts = zeros(size(timeoutLimits));
observedTerminalCycles = zeros(size(timeoutLimits));
observedBusyCounts = zeros(size(timeoutLimits));
for sweepIndex = 1:numel(timeoutLimits)
    timeoutLimit = timeoutLimits(sweepIndex);
    current = model(4,timeoutLimit,6,false);
    assert(current.completionDelay == 4 && ...
        isequal(current.workDone,cyclePulse(6)), ...
        'P04:TimeoutSweepIsolation', ...
        'Timeout sweep must preserve completion delay and pulse.');
    observedTimeouts(sweepIndex) = current.timeoutCount;
    observedTerminalCycles(sweepIndex) = current.terminalCycle;
    observedBusyCounts(sweepIndex) = current.busyCycleCount;
end
assert(isequal(observedTimeouts,expectedTimeouts) && ...
    isequal(observedTerminalCycles,expectedTerminalCycles) && ...
    isequal(observedBusyCounts,expectedBusyCounts), ...
    'P04:TimeoutSweep','Timeout threshold or inclusive-boundary behavior changed.');

%% Exhaustive healthy invariant grid, limiting cases, and resource bounds
for completionDelay = 1:8
    for timeoutLimit = 1:8
        current = model(completionDelay,timeoutLimit,16,false);
        expectedSuccess = completionDelay <= timeoutLimit;
        expectedTerminalCycle = 2 + min(completionDelay,timeoutLimit);
        assert(current.success == expectedSuccess && ...
            current.expectedSuccess == expectedSuccess, ...
            'P04:OutcomeInvariant', ...
            'Healthy success must mean completion is no later than timeout.');
        assert(current.terminalCycle == expectedTerminalCycle && ...
            current.busyCycleCount == min(completionDelay,timeoutLimit), ...
            'P04:LatencyInvariant', ...
            'Terminal cycle and WAIT dwell must follow the earlier event.');
        assert(current.completionCount + current.timeoutCount == 1 && ...
            all(sum(current.outputMatrix,2) <= 1), ...
            'P04:SingleTerminalPulse', ...
            'Exactly one mutually exclusive terminal pulse is required.');
        assert(current.stateAfter(expectedTerminalCycle+1) == 0 && ...
            ~current.terminalEntry(expectedTerminalCycle+1), ...
            'P04:ExhaustiveRecovery', ...
            'Every terminal state must recover to IDLE on the next edge.');
        assert(isequal(size(current.stateAfter),[16 1]) && ...
            isequal(size(current.inputMatrix),[16 4]) && ...
            isequal(size(current.outputMatrix),[16 3]) && ...
            all(ismember(current.stateAfter,current.stateCodes)) && ...
            current.stateCount == 4 && current.modeledStateBits == 2, ...
            'P04:ResourceBound','The fixed trace or state-space bound changed.');
        if completionDelay < timeoutLimit
            assert(current.ignoredLateDeadlineCount == 1 && ...
                current.ignoredLateWorkDoneCount == 0, ...
                'P04:LateTimeoutIsolation', ...
                'Only the late deadline should be ignored after success.');
        elseif completionDelay > timeoutLimit
            assert(current.ignoredLateWorkDoneCount == 1 && ...
                current.ignoredLateDeadlineCount == 0, ...
                'P04:LateCompletionIsolation', ...
                'Only late completion should be ignored after timeout.');
        else
            assert(current.ignoredLateWorkDoneCount == 0 && ...
                current.ignoredLateDeadlineCount == 0, ...
                'P04:TieEventIsolation', ...
                'Simultaneous events are consumed while the controller is waiting.');
        end
    end
end

%% Deliberately broken priority and equality-only fault activation
healthyTie = model(4,4,6,false);
brokenTie = model(4,4,6,true);
assert(healthyTie.stateAfter(6) == 2 && healthyTie.donePulse(6) && ...
    ~healthyTie.timeoutPulse(6), ...
    'P04:InclusiveDeadline','Healthy policy must accept completion at the deadline.');
assert(brokenTie.stateAfter(6) == 3 && brokenTie.timeoutPulse(6) && ...
    ~brokenTie.donePulse(6), ...
    'P04:BrokenPriority','Broken priority must report timeout at the tie edge.');
assert(isequal(brokenTie.mismatchCycles,6) && ...
    brokenTie.mismatchCount == 1 && brokenTie.wrongTimeoutCount == 1 && ...
    brokenTie.stateAfter(7) == 0, ...
    'P04:BrokenSymptom', ...
    'The wrong timeout must be isolated to the contested terminal edge.');
for tieDelay = 1:8
    tieCycle = 2 + tieDelay;
    currentHealthyTie = model(tieDelay,tieDelay,tieCycle,false);
    currentBrokenTie = model(tieDelay,tieDelay,tieCycle,true);
    assert(currentHealthyTie.terminalCycle == tieCycle && ...
        currentHealthyTie.donePulse(tieCycle) && ...
        ~currentHealthyTie.timeoutPulse(tieCycle) && ...
        currentBrokenTie.terminalCycle == tieCycle && ...
        currentBrokenTie.timeoutPulse(tieCycle) && ...
        ~currentBrokenTie.donePulse(tieCycle), ...
        'P04:EqualDelayPriorityGrid', ...
        'Every exposed equal-delay case must exercise the declared priority.');
    assert(isequal(currentBrokenTie.mismatchCycles,tieCycle) && ...
        currentBrokenTie.mismatchCount == 1 && ...
        currentBrokenTie.wrongTimeoutCount == 1 && ...
        currentBrokenTie.stateAfter(tieCycle+1) == 0 && ...
        isequal(currentBrokenTie.referenceStateAfter, ...
            currentHealthyTie.stateAfter), ...
        'P04:EqualDelayFaultRecovery', ...
        'Each equal-delay fault must be one wrong pulse followed by recovery.');
end
for completionDelay = 1:8
    for timeoutLimit = 1:8
        if completionDelay ~= timeoutLimit
            current = model(completionDelay,timeoutLimit,5,true);
            assert(current.mismatchCount == 0 && ...
                isequal(current.stateAfter,current.referenceStateAfter), ...
                'P04:BrokenInertLimit', ...
                'Priority order cannot matter when events do not coincide.');
        end
    end
end

%% Malformed inputs, selected-view isolation, and deterministic recovery
assertRejects(@() model(0,5,5,false),'P04:InvalidCompletionDelay');
assertRejects(@() model(9,5,5,false),'P04:InvalidCompletionDelay');
assertRejects(@() model(2.5,5,5,false),'P04:InvalidCompletionDelay');
assertRejects(@() model([2 3],5,5,false),'P04:InvalidCompletionDelay');
assertRejects(@() model(NaN,5,5,false),'P04:InvalidCompletionDelay');
assertRejects(@() model(Inf,5,5,false),'P04:InvalidCompletionDelay');
assertRejects(@() model(1+1i,5,5,false),'P04:InvalidCompletionDelay');
assertRejects(@() model(true,5,5,false),'P04:InvalidCompletionDelay');
assertRejects(@() model(3,0,5,false),'P04:InvalidTimeoutLimit');
assertRejects(@() model(3,9,5,false),'P04:InvalidTimeoutLimit');
assertRejects(@() model(3,2.5,5,false),'P04:InvalidTimeoutLimit');
assertRejects(@() model(3,[4 5],5,false),'P04:InvalidTimeoutLimit');
assertRejects(@() model(3,NaN,5,false),'P04:InvalidTimeoutLimit');
assertRejects(@() model(3,Inf,5,false),'P04:InvalidTimeoutLimit');
assertRejects(@() model(3,1+1i,5,false),'P04:InvalidTimeoutLimit');
assertRejects(@() model(3,true,5,false),'P04:InvalidTimeoutLimit');
assertRejects(@() model(3,5,0,false),'P04:InvalidSelectedCycle');
assertRejects(@() model(3,5,17,false),'P04:InvalidSelectedCycle');
assertRejects(@() model(3,5,2.5,false),'P04:InvalidSelectedCycle');
assertRejects(@() model(3,5,[4 5],false),'P04:InvalidSelectedCycle');
assertRejects(@() model(3,5,NaN,false),'P04:InvalidSelectedCycle');
assertRejects(@() model(3,5,Inf,false),'P04:InvalidSelectedCycle');
assertRejects(@() model(3,5,1+1i,false),'P04:InvalidSelectedCycle');
assertRejects(@() model(3,5,true,false),'P04:InvalidSelectedCycle');
assertRejects(@() model(3,5,5,2),'P04:InvalidBrokenPriority');
assertRejects(@() model(3,5,5,0.5),'P04:InvalidBrokenPriority');
assertRejects(@() model(3,5,5,[false true]), ...
    'P04:InvalidBrokenPriority');
assertRejects(@() model(3,5,5,NaN),'P04:InvalidBrokenPriority');
assertRejects(@() model(3,5,5,Inf),'P04:InvalidBrokenPriority');
assertRejects(@() model(3,5,5,1+1i),'P04:InvalidBrokenPriority');

selectedFirst = model(3,5,1,false);
selectedLast = model(3,5,16,false);
assert(isequal(selectedFirst.stateAfter,selectedLast.stateAfter) && ...
    isequal(selectedFirst.inputMatrix,selectedLast.inputMatrix) && ...
    isequal(selectedFirst.outputMatrix,selectedLast.outputMatrix), ...
    'P04:SelectedViewIsolation', ...
    'Selecting an edge must not alter the controller trace.');
baselineAfterFailure = model(3,5,5,false);
differentConfiguration = model(8,1,16,true); %#ok<NASGU>
baselineAfterOtherCall = model(3,5,5,false);
assert(isequaln(baseline,baselineAfterFailure) && ...
    isequaln(baseline,baselineAfterOtherCall), ...
    'P04:DeterminismRecovery', ...
    'Valid output must recover unchanged after failures and other calls.');

disp('P04 checks passed: state, timing, sweeps, timeout, fault, validation, and recovery.');
end

function pulse = cyclePulse(cycleNumber)
pulse = false(16,1);
pulse(cycleNumber) = true;
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P04:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
