function interactive
%INTERACTIVE Explore packet boundaries and one broken LAST hold rule.
clear model;
modelFcn = @model;
figureName = 'P11 Packet Framing Explorer';
delete(findall(groot,'Type','figure','Name',figureName));

fig = uifigure('Name',figureName,'Position',[70 70 1240 790]);
gridLayout = uigridlayout(fig,[4 4]);
gridLayout.RowHeight = {82,'1x',126,176};
gridLayout.ColumnWidth = {'1x','1x','1x','1x'};

instruction = uilabel(gridLayout,'WordWrap','on', ...
    'Text',['Read the four-beat, three-stall baseline first. Change packet ' ...
    'length or consumer ready-low duration independently. A packet closes ' ...
    'only when valid && ready && LAST are high on the same edge.']);
instruction.Layout.Row = 1;
instruction.Layout.Column = [1 4];

streamAxes = uiaxes(gridLayout);
streamAxes.Layout.Row = 2;
streamAxes.Layout.Column = [1 2];
packetAxes = uiaxes(gridLayout);
packetAxes.Layout.Row = 2;
packetAxes.Layout.Column = [3 4];

lengthPanel = uipanel(gridLayout,'Title','Lever 1: packet length');
lengthPanel.Layout.Row = 3;
lengthPanel.Layout.Column = 1;
lengthGrid = uigridlayout(lengthPanel,[2 1]);
lengthGrid.RowHeight = {56,'1x'};
uilabel(lengthGrid,'WordWrap','on', ...
    'Text','Accepted beats between successive LAST boundaries.');
lengthDropdown = uidropdown(lengthGrid, ...
    'Items',{'2','3','4','6'},'Value','4', ...
    'Tooltip','Packet length in beats; each choice divides 12 payload beats.');

stallPanel = uipanel(gridLayout,'Title','Lever 2: consumer stall');
stallPanel.Layout.Row = 3;
stallPanel.Layout.Column = 2;
stallGrid = uigridlayout(stallPanel,[2 1]);
stallGrid.RowHeight = {56,'1x'};
uilabel(stallGrid,'WordWrap','on', ...
    'Text','Consumer deasserts ready beginning at fixed cycle 4.');
stallSpinner = uispinner(stallGrid,'Limits',[0 6], ...
    'RoundFractionalValues','on','Step',1,'Value',3, ...
    'Tooltip','Consecutive consumer ready-low clock cycles.');

cyclePanel = uipanel(gridLayout,'Title','Observation cycle');
cyclePanel.Layout.Row = 3;
cyclePanel.Layout.Column = 3;
cycleGrid = uigridlayout(cyclePanel,[2 1]);
cycleGrid.RowHeight = {56,'1x'};
uilabel(cycleGrid,'WordWrap','on', ...
    'Text','Highlights one pre-edge offer in the linked stream view.');
cycleSpinner = uispinner(cycleGrid,'Limits',[1 24], ...
    'RoundFractionalValues','on','Step',1,'Value',4, ...
    'Tooltip','Clock cycle to inspect in the fixed teaching trace.');

faultPanel = uipanel(gridLayout,'Title','Deliberately broken case');
faultPanel.Layout.Row = 3;
faultPanel.Layout.Column = 4;
faultGrid = uigridlayout(faultPanel,[2 1]);
faultGrid.RowHeight = {60,'1x'};
uilabel(faultGrid,'WordWrap','on', ...
    'Text',['Enabled when a stall can activate boundary-counter drift; ' ...
    'payload itself still obeys backpressure.']);
faultCheckbox = uicheckbox(faultGrid, ...
    'Text','Advance LAST state while ready is low','Value',false, ...
    'Tooltip','Violates the P10 hold obligation for packet metadata.');

summary = uilabel(gridLayout,'WordWrap','on');
summary.Layout.Row = 4;
summary.Layout.Column = [1 4];

lengthDropdown.ValueChangedFcn = @(~,~) updatePlots();
stallSpinner.ValueChangedFcn = @(~,~) updatePlots();
cycleSpinner.ValueChangedFcn = @(~,~) updatePlots();
faultCheckbox.ValueChangedFcn = @(~,~) updatePlots();
updatePlots();

    function updatePlots
        packetLength = str2double(lengthDropdown.Value);
        consumerStallCycles = round(stallSpinner.Value);
        selectedCycle = round(cycleSpinner.Value);
        if consumerStallCycles == 0
            faultCheckbox.Value = false;
            faultCheckbox.Enable = 'off';
        else
            faultCheckbox.Enable = 'on';
        end
        brokenMode = faultCheckbox.Value;
        out = modelFcn(packetLength,consumerStallCycles,brokenMode);

        cla(streamAxes);
        stairs(streamAxes,out.cycle,double(out.applied.sourceValid), ...
            'LineWidth',1.25,'DisplayName','valid');
        hold(streamAxes,'on');
        stairs(streamAxes,out.cycle, ...
            2+double(out.applied.sourceReady), ...
            'LineWidth',1.25,'DisplayName','ready');
        stairs(streamAxes,out.cycle, ...
            4+double(out.applied.sourceLast), ...
            'LineWidth',1.25,'DisplayName','LAST');
        stairs(streamAxes,out.cycle, ...
            6+double(out.applied.transfer), ...
            'LineWidth',1.25,'DisplayName','transfer');
        xline(streamAxes,selectedCycle,':','Selected cycle', ...
            'LabelVerticalAlignment','bottom');
        hold(streamAxes,'off');
        grid(streamAxes,'on');
        xlabel(streamAxes,'Clock cycle [cycles]');
        ylabel(streamAxes, ...
            'Handshake and boundary [binary, vertically offset]');
        title(streamAxes,'Valid/ready transfer with LAST sideband');
        streamAxes.YTick = [0.5 2.5 4.5 6.5];
        streamAxes.YTickLabel = {'valid','ready','LAST','transfer'};
        streamAxes.YLim = [-0.2 7.2];
        streamAxes.XLim = [1 out.recordCycleCount];

        receiverPacketIndex = cumsum( ...
            [1; double(out.applied.acceptedLast(1:end-1))]);
        cla(packetAxes);
        stairs(packetAxes,out.beatOrdinal, ...
            out.expectedPacketIndexByBeat, ...
            'LineWidth',1.25,'DisplayName','expected packet');
        hold(packetAxes,'on');
        stairs(packetAxes,out.applied.acceptedBeatOrdinals, ...
            receiverPacketIndex,'--','LineWidth',1.25, ...
            'DisplayName','receiver packet');
        scatter(packetAxes,out.applied.observedBoundaryBeatOrdinals, ...
            receiverPacketIndex(out.applied.observedBoundaryPositions), ...
            48,'filled','DisplayName','accepted LAST');
        hold(packetAxes,'off');
        grid(packetAxes,'on');
        xlabel(packetAxes,'Accepted payload [beat ordinal from one]');
        ylabel(packetAxes,'Packet assignment [packet index from one]');
        title(packetAxes,'Receiver grouping from accepted LAST markers');
        packetAxes.XLim = [1 out.beatCount];
        packetAxes.YLim = [0 out.maximumPacketCount+1];
        legend(packetAxes,'Location','best');

        if out.applied.sourceValid(selectedCycle)
            sourceOffer = sprintf('beat %d / code %g / LAST %d', ...
                out.applied.sourceBeatOrdinal(selectedCycle), ...
                out.applied.sourcePayloadWord(selectedCycle), ...
                out.applied.sourceLast(selectedCycle));
        else
            sourceOffer = 'none (source valid is low)';
        end
        if out.frameFaultVisible
            health = ['BROKEN: all payloads arrived, but accepted LAST ' ...
                'markers split the receiver stream incorrectly'];
        elseif out.faultActive
            health = ['PROTOCOL FAULT: LAST state advanced during a stall, ' ...
                'but whole-packet drift realigned accepted boundaries'];
        elseif brokenMode
            health = ['inert fault selection: ready never blocked a valid ' ...
                'beat, so boundary state did not drift from payload'];
        else
            health = ['healthy: payload and LAST advance together only on ' ...
                'valid/ready transfer edges'];
        end
        completedLengthsText = sprintf('%d ', ...
            out.applied.completedPacketLengths);
        summary.Text = sprintf([ ...
            'Cycle %d: valid/ready/transfer/LAST=%d/%d/%d/%d, offer=%s. ' ...
            'Packet length=%d beats; consumer ready low=%d cycles. ' ...
            'Applied completion/accepted/payload errors=%g cycles/%d ' ...
            'beats/%d events; completed lengths=[%s] beats; packets/' ...
            'boundary mismatches/trailing=%d/%d/%d. LAST hold ' ...
            'violations=%d; marker advances while ' ...
            'stalled=%d. %s. The 24-cycle trace, 12 payload words, ' ...
            'six-packet maximum, and 12-bit labels are teaching-model ' ...
            'bounds, not measured throughput, synthesized logic, or an ' ...
            'AXI-Stream compliance claim. %s.'], ...
            selectedCycle,out.applied.sourceValid(selectedCycle), ...
            out.applied.sourceReady(selectedCycle), ...
            out.applied.transfer(selectedCycle), ...
            out.applied.sourceLast(selectedCycle),sourceOffer, ...
            out.packetLength,out.consumerStallCycles, ...
            out.applied.completionCycle,out.applied.acceptedBeatCount, ...
            out.applied.lostBeatCount+out.applied.duplicateBeatCount+ ...
                out.applied.outOfOrderCount, ...
            completedLengthsText, ...
            out.applied.observedPacketCount, ...
            out.applied.boundaryMismatchCount, ...
            out.applied.trailingBeatCount, ...
            out.applied.lastHoldViolationCount, ...
            out.applied.markerAdvanceWhileStalledCount,health, ...
            out.holdRuleText);
        drawnow;
    end
end
