function out = model(packetLength,consumerStallCycles,brokenAdvanceLast)
%MODEL Simulate packet boundaries carried by a valid/ready stream.
%   A transfer occurs only when valid and ready are both high immediately
%   before an edge. The LAST sideband belongs to the same beat as payload,
%   so a stalled source must hold valid, payload, and LAST together.

if nargin < 1
    packetLength = 4;
end
if nargin < 2
    consumerStallCycles = 3;
end
if nargin < 3
    brokenAdvanceLast = false;
end

allowedPacketLengths = [2 3 4 6];
validatePacketLength(packetLength,allowedPacketLengths);
validateIntegerScalar(consumerStallCycles,0,6, ...
    'P11:InvalidConsumerStallCycles','consumerStallCycles');
validateBooleanScalar(brokenAdvanceLast);
packetLength = double(packetLength);
consumerStallCycles = double(consumerStallCycles);
brokenAdvanceLast = logical(brokenAdvanceLast);

payloadAccumulatorBits = 12;
payloadModulus = 2^payloadAccumulatorBits;
payloadTuningWord = 411;
beatCount = 12;
recordCycleCount = 24;
consumerStallStartCycle = 4;
maximumConsumerStallCycles = 6;
maximumPacketCount = beatCount/min(allowedPacketLengths);
cycle = (1:recordCycleCount).';
beatOrdinal = (1:beatCount).';
payloadWords = mod((beatOrdinal-1)*payloadTuningWord,payloadModulus);
expectedLastByBeat = mod(beatOrdinal,packetLength) == 0;
expectedPacketIndexByBeat = ceil(beatOrdinal/packetLength);
expectedBeatIndexInPacket = mod(beatOrdinal-1,packetLength)+1;
expectedPacketCount = beatCount/packetLength;

consumerReady = true(recordCycleCount,1);
if consumerStallCycles > 0
    consumerStallEndCycle = ...
        consumerStallStartCycle+consumerStallCycles-1;
    consumerReady(consumerStallStartCycle:consumerStallEndCycle) = false;
else
    consumerStallEndCycle = consumerStallStartCycle-1;
end

reference = simulatePath(payloadWords,expectedLastByBeat,packetLength, ...
    consumerReady,false);
applied = simulatePath(payloadWords,expectedLastByBeat,packetLength, ...
    consumerReady,brokenAdvanceLast);

out = struct( ...
    'packetLength',packetLength, ...
    'consumerStallCycles',consumerStallCycles, ...
    'brokenAdvanceLast',brokenAdvanceLast, ...
    'allowedPacketLengths',allowedPacketLengths, ...
    'payloadAccumulatorBits',payloadAccumulatorBits, ...
    'payloadModulus',payloadModulus, ...
    'payloadTuningWord',payloadTuningWord, ...
    'beatCount',beatCount, ...
    'recordCycleCount',recordCycleCount, ...
    'consumerStallStartCycle',consumerStallStartCycle, ...
    'consumerStallEndCycle',consumerStallEndCycle, ...
    'maximumConsumerStallCycles',maximumConsumerStallCycles, ...
    'maximumPacketCount',maximumPacketCount, ...
    'cycle',cycle, ...
    'beatOrdinal',beatOrdinal, ...
    'payloadWords',payloadWords, ...
    'expectedLastByBeat',expectedLastByBeat, ...
    'expectedPacketIndexByBeat',expectedPacketIndexByBeat, ...
    'expectedBeatIndexInPacket',expectedBeatIndexInPacket, ...
    'expectedPacketCount',expectedPacketCount, ...
    'expectedBoundaryBeatOrdinals',find(expectedLastByBeat), ...
    'consumerReady',consumerReady, ...
    'reference',reference, ...
    'applied',applied, ...
    'faultActive',brokenAdvanceLast && ...
        any(applied.markerAdvanceWhileStalled), ...
    'frameFaultVisible',brokenAdvanceLast && ...
        ~applied.framingValid, ...
    'maxRecordCycles',recordCycleCount, ...
    'maxBeatCount',beatCount, ...
    'maxPacketCount',maximumPacketCount, ...
    'modeledPayloadBits',payloadAccumulatorBits, ...
    'transferEquationText', ...
        'transfer[n] = valid[n] && ready[n]', ...
    'boundaryRuleText', ...
        'last[n] = 1 exactly on the final beat of each packet', ...
    'receiverRuleText', ...
        'an accepted beat with last = 1 closes the current packet', ...
    'holdRuleText', ...
        ['if valid[n] && ~ready[n], valid, payload, and last stay ' ...
        'stable until an accepting edge']);
end

function path = simulatePath(payloadWords,expectedLastByBeat,packetLength, ...
        consumerReady,brokenMode)
recordCycleCount = numel(consumerReady);
beatCount = numel(payloadWords);

sourceValid = false(recordCycleCount,1);
sourceReady = consumerReady;
sourceBeatOrdinal = zeros(recordCycleCount,1);
sourcePayloadWord = NaN(recordCycleCount,1);
sourceExpectedLast = false(recordCycleCount,1);
sourceLast = false(recordCycleCount,1);
markerBeatOrdinal = zeros(recordCycleCount,1);
transfer = false(recordCycleCount,1);
sourceStalled = false(recordCycleCount,1);
payloadAdvance = false(recordCycleCount,1);
markerAdvance = false(recordCycleCount,1);
acceptedBeatOrdinalByCycle = zeros(recordCycleCount,1);
acceptedPayloadWordByCycle = NaN(recordCycleCount,1);
acceptedLastByCycle = false(recordCycleCount,1);
acceptedExpectedLastByCycle = false(recordCycleCount,1);
transferCycleByBeat = NaN(beatCount,1);

currentPayloadBeat = 1;
currentMarkerBeat = 1;
for cycleIndex = 1:recordCycleCount
    sourceValid(cycleIndex) = currentPayloadBeat <= beatCount;
    if sourceValid(cycleIndex)
        sourceBeatOrdinal(cycleIndex) = currentPayloadBeat;
        sourcePayloadWord(cycleIndex) = payloadWords(currentPayloadBeat);
        sourceExpectedLast(cycleIndex) = ...
            expectedLastByBeat(currentPayloadBeat);
        markerBeatOrdinal(cycleIndex) = currentMarkerBeat;
        sourceLast(cycleIndex) = mod(currentMarkerBeat,packetLength) == 0;
    end

    transfer(cycleIndex) = sourceValid(cycleIndex) && ...
        sourceReady(cycleIndex);
    sourceStalled(cycleIndex) = sourceValid(cycleIndex) && ...
        ~sourceReady(cycleIndex);
    payloadAdvance(cycleIndex) = transfer(cycleIndex);
    markerAdvance(cycleIndex) = transfer(cycleIndex) || ...
        (brokenMode && sourceValid(cycleIndex));

    if transfer(cycleIndex)
        acceptedBeatOrdinalByCycle(cycleIndex) = currentPayloadBeat;
        acceptedPayloadWordByCycle(cycleIndex) = ...
            payloadWords(currentPayloadBeat);
        acceptedLastByCycle(cycleIndex) = sourceLast(cycleIndex);
        acceptedExpectedLastByCycle(cycleIndex) = ...
            expectedLastByBeat(currentPayloadBeat);
        transferCycleByBeat(currentPayloadBeat) = cycleIndex;
    end

    if payloadAdvance(cycleIndex)
        currentPayloadBeat = currentPayloadBeat+1;
    end
    if markerAdvance(cycleIndex)
        currentMarkerBeat = currentMarkerBeat+1;
    end
end

payloadHoldViolation = false(recordCycleCount,1);
lastHoldViolation = false(recordCycleCount,1);
for cycleIndex = 2:recordCycleCount
    if sourceValid(cycleIndex-1) && ~sourceReady(cycleIndex-1)
        payloadHoldViolation(cycleIndex) = ...
            ~sourceValid(cycleIndex) || ...
            sourceBeatOrdinal(cycleIndex) ~= ...
                sourceBeatOrdinal(cycleIndex-1) || ...
            sourcePayloadWord(cycleIndex) ~= ...
                sourcePayloadWord(cycleIndex-1);
        lastHoldViolation(cycleIndex) = ...
            ~sourceValid(cycleIndex) || ...
            sourceLast(cycleIndex) ~= sourceLast(cycleIndex-1);
    end
end

acceptedBeatOrdinals = sourceBeatOrdinal(transfer);
acceptedPayloadWords = sourcePayloadWord(transfer);
acceptedLast = sourceLast(transfer);
acceptedExpectedLast = sourceExpectedLast(transfer);
observedBoundaryPositions = find(acceptedLast);
observedBoundaryBeatOrdinals = ...
    acceptedBeatOrdinals(observedBoundaryPositions);
completedPacketLengths = diff([0; observedBoundaryPositions]);
if isempty(observedBoundaryPositions)
    trailingBeatCount = numel(acceptedBeatOrdinals);
else
    trailingBeatCount = ...
        numel(acceptedBeatOrdinals)-observedBoundaryPositions(end);
end

lostBeatMask = true(beatCount,1);
if ~isempty(acceptedBeatOrdinals)
    lostBeatMask(unique(acceptedBeatOrdinals)) = false;
end
lostBeatCount = sum(lostBeatMask);
duplicateBeatCount = numel(acceptedBeatOrdinals)- ...
    numel(unique(acceptedBeatOrdinals));
outOfOrderCount = sum(diff(acceptedBeatOrdinals) <= 0);
dataCompleted = numel(acceptedBeatOrdinals) == beatCount && ...
    lostBeatCount == 0 && duplicateBeatCount == 0 && ...
    outOfOrderCount == 0;
if dataCompleted
    completionCycle = find(transfer,1,'last');
else
    completionCycle = NaN;
end

boundaryMismatch = acceptedLast ~= acceptedExpectedLast;
boundaryMismatchCount = sum(boundaryMismatch);
observedPacketCount = sum(acceptedLast);
packetLengthsCorrect = ...
    numel(completedPacketLengths) == beatCount/packetLength && ...
    all(completedPacketLengths == packetLength);
framingValid = dataCompleted && boundaryMismatchCount == 0 && ...
    observedPacketCount == beatCount/packetLength && ...
    trailingBeatCount == 0 && packetLengthsCorrect;
if isnan(completionCycle)
    activeWindowCycleCount = recordCycleCount;
else
    activeWindowCycleCount = completionCycle;
end

path = struct( ...
    'brokenMode',logical(brokenMode), ...
    'sourceValid',sourceValid, ...
    'sourceReady',sourceReady, ...
    'sourceBeatOrdinal',sourceBeatOrdinal, ...
    'sourcePayloadWord',sourcePayloadWord, ...
    'sourceExpectedLast',sourceExpectedLast, ...
    'sourceLast',sourceLast, ...
    'markerBeatOrdinal',markerBeatOrdinal, ...
    'transfer',transfer, ...
    'sourceStalled',sourceStalled, ...
    'payloadAdvance',payloadAdvance, ...
    'markerAdvance',markerAdvance, ...
    'markerAdvanceWhileStalled',markerAdvance & sourceStalled, ...
    'payloadHoldViolation',payloadHoldViolation, ...
    'lastHoldViolation',lastHoldViolation, ...
    'acceptedBeatOrdinalByCycle',acceptedBeatOrdinalByCycle, ...
    'acceptedPayloadWordByCycle',acceptedPayloadWordByCycle, ...
    'acceptedLastByCycle',acceptedLastByCycle, ...
    'acceptedExpectedLastByCycle',acceptedExpectedLastByCycle, ...
    'acceptedBeatOrdinals',acceptedBeatOrdinals, ...
    'acceptedPayloadWords',acceptedPayloadWords, ...
    'acceptedLast',acceptedLast, ...
    'acceptedExpectedLast',acceptedExpectedLast, ...
    'transferCycleByBeat',transferCycleByBeat, ...
    'observedBoundaryPositions',observedBoundaryPositions, ...
    'observedBoundaryBeatOrdinals',observedBoundaryBeatOrdinals, ...
    'completedPacketLengths',completedPacketLengths, ...
    'trailingBeatCount',trailingBeatCount, ...
    'lostBeatMask',lostBeatMask, ...
    'boundaryMismatch',boundaryMismatch, ...
    'acceptedBeatCount',sum(transfer), ...
    'observedPacketCount',observedPacketCount, ...
    'sourceStallCycleCount',sum(sourceStalled), ...
    'payloadHoldViolationCount',sum(payloadHoldViolation), ...
    'lastHoldViolationCount',sum(lastHoldViolation), ...
    'markerAdvanceWhileStalledCount', ...
        sum(markerAdvance & sourceStalled), ...
    'boundaryMismatchCount',boundaryMismatchCount, ...
    'lostBeatCount',lostBeatCount, ...
    'duplicateBeatCount',duplicateBeatCount, ...
    'outOfOrderCount',outOfOrderCount, ...
    'dataCompleted',dataCompleted, ...
    'framingValid',framingValid, ...
    'completionCycle',completionCycle, ...
    'activeWindowCycleCount',activeWindowCycleCount, ...
    'activeWindowTransferRate',sum(transfer)/activeWindowCycleCount, ...
    'boundaryDensity',sum(acceptedLast)/max(1,sum(transfer)), ...
    'traceCycleCount',recordCycleCount, ...
    'traceBeatCapacity',beatCount);
end

function validatePacketLength(value,allowedValues)
valid = isnumeric(value) && ~islogical(value) && isreal(value) && ...
    isscalar(value) && ~isnan(value) && ~isinf(value) && ...
    value == fix(value) && any(double(value) == allowedValues);
if ~valid
    error('P11:InvalidPacketLength', ...
        'packetLength must be one of [2, 3, 4, 6] beats.');
end
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && ~isnan(value) && ~isinf(value) && ...
        value == fix(value) && value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P11:InvalidBrokenAdvanceLast', ...
        'brokenAdvanceLast must be logical or numeric 0 or 1.');
end
end
