function run_checks
%RUN_CHECKS Verify packet boundaries, stalls, limits, and the LAST fault.
clear model;

%% Exact baseline payload, handshake, packet boundaries, and latency
baseline = model(4,3,false);
expectedPayloadWords = ...
    [0 411 822 1233 1644 2055 2466 2877 3288 3699 14 425].';
expectedReady = true(24,1);
expectedReady(4:6) = false;
expectedTransfer = false(24,1);
expectedTransfer([1:3 7:15]) = true;
expectedStalled = false(24,1);
expectedStalled(4:6) = true;
assert(baseline.packetLength == 4 && ...
    baseline.consumerStallCycles == 3 && ...
    ~baseline.brokenAdvanceLast && ...
    baseline.beatCount == 12 && baseline.recordCycleCount == 24 && ...
    isequal(baseline.cycle,(1:24).') && ...
    isequal(baseline.payloadWords,expectedPayloadWords) && ...
    isequal(baseline.consumerReady,expectedReady), ...
    'P11:BaselineShape', ...
    'Baseline controls, payloads, readiness, or record shape changed.');
assert(isequal(baseline.expectedBoundaryBeatOrdinals,[4 8 12].') && ...
    baseline.expectedPacketCount == 3 && ...
    isequal(baseline.expectedPacketIndexByBeat, ...
        [1 1 1 1 2 2 2 2 3 3 3 3].') && ...
    isequal(baseline.expectedBeatIndexInPacket, ...
        [1 2 3 4 1 2 3 4 1 2 3 4].'), ...
    'P11:BaselinePacketMap', ...
    'Four-beat packet identity or expected boundaries changed.');
assert(isequal(find(baseline.expectedLastByBeat),[4 8 12].') && ...
    isequal(baseline.expectedLastByBeat, ...
        [false false false true false false false true ...
        false false false true].'), ...
    'P11:BaselineLastMap', ...
    'Expected LAST must belong only to final beats 4, 8, and 12.');
assert(isequal(baseline.applied.transfer,expectedTransfer) && ...
    isequal(baseline.applied.sourceStalled,expectedStalled) && ...
    isequal(baseline.applied.acceptedBeatOrdinals,(1:12).') && ...
    isequal(baseline.applied.acceptedPayloadWords,expectedPayloadWords) && ...
    isequal(baseline.applied.transferCycleByBeat, ...
        [1 2 3 7 8 9 10 11 12 13 14 15].'), ...
    'P11:BaselineTransfers', ...
    'Baseline must accept all 12 payload beats in order around the stall.');
assert(isequal(baseline.applied.observedBoundaryBeatOrdinals,[4 8 12].') && ...
    isequal(baseline.applied.completedPacketLengths,[4 4 4].') && ...
    baseline.applied.observedPacketCount == 3 && ...
    baseline.applied.trailingBeatCount == 0 && ...
    baseline.applied.boundaryMismatchCount == 0 && ...
    baseline.applied.framingValid, ...
    'P11:BaselineFraming', ...
    'Healthy accepted LAST markers must close three four-beat packets.');
assert(isequal(find(baseline.applied.acceptedLast),[4 8 12].') && ...
    isequal(baseline.applied.acceptedLast, ...
        baseline.applied.acceptedExpectedLast) && ...
    isequal(find(baseline.applied.acceptedLastByCycle),[7 11 15].'), ...
    'P11:BaselineAcceptedLast', ...
    'Expected and observed LAST must coincide on exact accepting edges.');
assert(baseline.applied.dataCompleted && ...
    baseline.applied.completionCycle == 15 && ...
    baseline.applied.sourceStallCycleCount == 3 && ...
    baseline.applied.acceptedBeatCount == 12 && ...
    baseline.applied.activeWindowTransferRate == 12/15 && ...
    baseline.applied.boundaryDensity == 1/4 && ...
    baseline.applied.lostBeatCount == 0 && ...
    baseline.applied.duplicateBeatCount == 0 && ...
    baseline.applied.outOfOrderCount == 0, ...
    'P11:BaselineMetrics', ...
    'Baseline completion, rate, density, or payload integrity changed.');
assert(baseline.maxRecordCycles == 24 && ...
    baseline.maxBeatCount == 12 && baseline.maxPacketCount == 6 && ...
    baseline.maximumPacketCount == 6 && ...
    baseline.maximumConsumerStallCycles == 6 && ...
    baseline.modeledPayloadBits == 12, ...
    'P11:BaselineResourceContract', ...
    'Baseline fixed record, payload, packet, and control bounds changed.');

%% Accepted numeric classes normalize to the same deterministic result
typedBaseline = model(uint8(4),uint8(3),uint8(0));
assert(isequaln(typedBaseline,baseline), ...
    'P11:NumericClassNormalization', ...
    'Accepted integer classes must normalize to double/logical controls.');

%% Transfer equation and the payload-plus-LAST hold obligation
for cycleIndex = 1:baseline.recordCycleCount
    assert(baseline.applied.transfer(cycleIndex) == ...
            (baseline.applied.sourceValid(cycleIndex) && ...
            baseline.applied.sourceReady(cycleIndex)) && ...
        baseline.applied.sourceReady(cycleIndex) == ...
            baseline.consumerReady(cycleIndex), ...
        'P11:TransferEquation', ...
        'Every accepted beat must require valid and ready on one edge.');
end
assert(all(baseline.applied.sourceBeatOrdinal(4:7) == 4) && ...
    all(baseline.applied.sourcePayloadWord(4:7) == 1233) && ...
    all(baseline.applied.sourceLast(4:7)) && ...
    all(~baseline.applied.payloadHoldViolation) && ...
    all(~baseline.applied.lastHoldViolation), ...
    'P11:HealthyWholeBeatHold', ...
    'Payload beat four and its LAST marker must stay together while stalled.');
assert(isequaln(baseline.reference,baseline.applied), ...
    'P11:HealthyReference', ...
    'Healthy applied and reference paths must be identical.');

%% Sweep 1 - packet length moves only boundary placement
packetLengthSweep = [2 3 4 6];
expectedPacketCounts = [6 4 3 2];
expectedBoundaryDensity = 1./packetLengthSweep;
baselineTransferCycles = find(baseline.applied.transfer);
for sweepIndex = 1:numel(packetLengthSweep)
    current = model(packetLengthSweep(sweepIndex),3,false);
    assert(current.expectedPacketCount == ...
            expectedPacketCounts(sweepIndex) && ...
        current.applied.observedPacketCount == ...
            expectedPacketCounts(sweepIndex) && ...
        current.applied.boundaryDensity == ...
            expectedBoundaryDensity(sweepIndex) && ...
        all(current.applied.completedPacketLengths == ...
            packetLengthSweep(sweepIndex)), ...
        'P11:PacketLengthSweep', ...
        'Packet length must set boundary count, spacing, and density exactly.');
    assert(current.consumerStallCycles == 3 && ...
        isequal(current.consumerReady,expectedReady) && ...
        isequal(current.payloadWords,expectedPayloadWords) && ...
        isequal(find(current.applied.transfer),baselineTransferCycles) && ...
        current.applied.completionCycle == 15 && ...
        current.applied.sourceStallCycleCount == 3 && ...
        current.applied.dataCompleted && current.applied.framingValid && ...
        current.applied.payloadHoldViolationCount == 0 && ...
        current.applied.lastHoldViolationCount == 0, ...
        'P11:PacketLengthSweepIsolation', ...
        ['Packet-length sweep must preserve readiness, payloads, timing, ' ...
        'and whole-beat holds.']);
end

%% Sweep 2 - consumer stall moves only transfer timing
consumerStallSweep = 0:6;
expectedCompletionCycles = 12:18;
for sweepIndex = 1:numel(consumerStallSweep)
    current = model(4,consumerStallSweep(sweepIndex),false);
    assert(current.applied.completionCycle == ...
            expectedCompletionCycles(sweepIndex) && ...
        current.applied.sourceStallCycleCount == ...
            consumerStallSweep(sweepIndex) && ...
        current.applied.activeWindowTransferRate == ...
            12/expectedCompletionCycles(sweepIndex), ...
        'P11:ConsumerStallSweep', ...
        'Each ready-low edge must delay one accepted beat and completion edge.');
    assert(current.packetLength == 4 && ...
        isequal(current.payloadWords,expectedPayloadWords) && ...
        isequal(current.applied.observedBoundaryBeatOrdinals,[4 8 12].') && ...
        isequal(current.applied.completedPacketLengths,[4 4 4].') && ...
        current.applied.observedPacketCount == 3 && ...
        current.applied.acceptedBeatCount == 12 && ...
        current.applied.dataCompleted && current.applied.framingValid && ...
        current.applied.boundaryMismatchCount == 0, ...
        'P11:ConsumerStallSweepIsolation', ...
        ['Consumer-stall sweep must preserve packet length, payload order, ' ...
        'boundary identity, and packet count.']);
end

%% Limiting cases remain complete and bounded
shortPacketsNoStall = model(2,0,false);
assert(isequal(shortPacketsNoStall.applied.transferCycleByBeat,(1:12).') && ...
    isequal(shortPacketsNoStall.applied.observedBoundaryBeatOrdinals, ...
        (2:2:12).') && ...
    isequal(shortPacketsNoStall.applied.completedPacketLengths, ...
        2*ones(6,1)) && ...
    shortPacketsNoStall.applied.observedPacketCount == 6 && ...
    shortPacketsNoStall.applied.completionCycle == 12 && ...
    shortPacketsNoStall.applied.framingValid, ...
    'P11:ShortestPacketNoStallLimit', ...
    'Shortest packets with ready high must close every second beat.');
longPacketsLongestStall = model(6,6,false);
assert(isequal(longPacketsLongestStall.applied.observedBoundaryBeatOrdinals, ...
        [6 12].') && ...
    isequal(longPacketsLongestStall.applied.completedPacketLengths,[6 6].') && ...
    longPacketsLongestStall.applied.sourceStallCycleCount == 6 && ...
    longPacketsLongestStall.applied.completionCycle == 18 && ...
    longPacketsLongestStall.applied.dataCompleted && ...
    longPacketsLongestStall.applied.framingValid, ...
    'P11:LongestPacketLongestStallLimit', ...
    'Maximum healthy controls must complete two six-beat packets by cycle 18.');

%% Deliberately broken LAST state advances without an accepted payload beat
healthy = model(4,3,false);
broken = model(4,3,true);
assert(broken.brokenAdvanceLast && broken.faultActive && ...
    broken.frameFaultVisible && ...
    isequaln(broken.reference,healthy.applied) && ...
    broken.applied.markerAdvanceWhileStalledCount == 3 && ...
    isequal(find(broken.applied.lastHoldViolation),5) && ...
    broken.applied.lastHoldViolationCount == 1 && ...
    broken.applied.payloadHoldViolationCount == 0, ...
    'P11:BrokenLastHold', ...
    'Broken mode must advance LAST three times while payload beat four waits.');
assert(isequal(broken.applied.markerBeatOrdinal(4:7),[4 5 6 7].') && ...
    all(broken.applied.sourceBeatOrdinal(4:7) == 4) && ...
    isequal(broken.applied.sourceLast(4:7), ...
        [true false false false].'), ...
    'P11:BrokenMarkerDrift', ...
    'Boundary state must advance while payload identity remains beat four.');
assert(isequal(broken.applied.acceptedBeatOrdinals,(1:12).') && ...
    isequal(broken.applied.acceptedPayloadWords,expectedPayloadWords) && ...
    broken.applied.dataCompleted && ...
    broken.applied.lostBeatCount == 0 && ...
    broken.applied.duplicateBeatCount == 0 && ...
    broken.applied.outOfOrderCount == 0 && ...
    broken.applied.completionCycle == healthy.applied.completionCycle, ...
    'P11:BrokenPayloadIsolation', ...
    'The selected fault must corrupt framing without corrupting payload order.');
assert(isequal(broken.applied.observedBoundaryBeatOrdinals,[5 9].') && ...
    isequal(broken.applied.completedPacketLengths,[5 4].') && ...
    broken.applied.trailingBeatCount == 3 && ...
    broken.applied.observedPacketCount == 2 && ...
    broken.applied.boundaryMismatchCount == 5 && ...
    isequal(find(broken.applied.boundaryMismatch),[4 5 8 9 12].') && ...
    ~broken.applied.framingValid, ...
    'P11:BrokenFramingSymptom', ...
    ['Advanced LAST must produce packets of five and four beats plus an ' ...
    'unterminated three-beat tail.']);

%% Fault activation, inert no-stall behavior, and aliasing limit
inertNoStall = model(4,0,true);
healthyNoStall = model(4,0,false);
assert(~inertNoStall.faultActive && ~inertNoStall.frameFaultVisible && ...
    inertNoStall.applied.brokenMode && ...
    ~healthyNoStall.applied.brokenMode && ...
    isequaln(rmfield(inertNoStall.applied,'brokenMode'), ...
        rmfield(healthyNoStall.applied,'brokenMode')), ...
    'P11:BrokenInertNoStall', ...
    'The fault is inert when every offered beat is accepted immediately.');
aliasedFault = model(4,4,true);
assert(aliasedFault.faultActive && ...
    aliasedFault.applied.markerAdvanceWhileStalledCount == 4 && ...
    aliasedFault.applied.lastHoldViolationCount > 0 && ...
    aliasedFault.applied.framingValid && ...
    ~aliasedFault.frameFaultVisible && ...
    isequal(aliasedFault.applied.observedBoundaryBeatOrdinals,[4 8 12].'), ...
    'P11:BrokenBoundaryAliasingLimit', ...
    ['Advancing exactly one packet length can hide at accepted boundaries ' ...
    'even though the stalled-sideband contract was violated.']);
assert(isequal(find(aliasedFault.applied.lastHoldViolation),[5 8].') && ...
    aliasedFault.applied.boundaryMismatchCount == 0 && ...
    aliasedFault.applied.trailingBeatCount == 0, ...
    'P11:AliasedHoldSymptom', ...
    'Whole-packet drift must retain hold evidence despite clean framing.');

%% A non-boundary stall can hide the state advance until a later beat
healthyNonBoundary = model(3,1,false);
brokenNonBoundary = model(3,1,true);
assert(isequaln(brokenNonBoundary.reference, ...
        healthyNonBoundary.applied) && ...
    isequal(find(brokenNonBoundary.applied.sourceStalled),4) && ...
    isequal(brokenNonBoundary.applied.sourceBeatOrdinal(4:5),[4 4].') && ...
    isequal(brokenNonBoundary.applied.markerBeatOrdinal(4:5),[4 5].') && ...
    all(~brokenNonBoundary.applied.sourceLast(4:5)) && ...
    brokenNonBoundary.applied.markerAdvanceWhileStalledCount == 1 && ...
    brokenNonBoundary.applied.lastHoldViolationCount == 0 && ...
    brokenNonBoundary.faultActive && brokenNonBoundary.frameFaultVisible, ...
    'P11:NonBoundaryHiddenAdvance', ...
    ['One illegal marker-state advance can leave the offered LAST value ' ...
    'unchanged on a stalled non-boundary beat.']);
assert(isequal(healthyNonBoundary.applied.observedBoundaryBeatOrdinals, ...
        [3 6 9 12].') && ...
    isequal(brokenNonBoundary.applied.acceptedBeatOrdinals,(1:12).') && ...
    isequal(brokenNonBoundary.applied.acceptedPayloadWords, ...
        expectedPayloadWords) && ...
    brokenNonBoundary.applied.dataCompleted && ...
    brokenNonBoundary.applied.payloadHoldViolationCount == 0 && ...
    brokenNonBoundary.applied.completionCycle == 13 && ...
    isequal(brokenNonBoundary.applied.observedBoundaryBeatOrdinals, ...
        [3 5 8 11].') && ...
    isequal(brokenNonBoundary.applied.completedPacketLengths, ...
        [3 2 3 3].') && ...
    brokenNonBoundary.applied.trailingBeatCount == 1 && ...
    brokenNonBoundary.applied.boundaryMismatchCount == 6 && ...
    isequal(find(brokenNonBoundary.applied.boundaryMismatch), ...
        [5 6 8 9 11 12].') && ...
    ~brokenNonBoundary.applied.framingValid, ...
    'P11:NonBoundaryDelayedCorruption', ...
    ['Hidden state advance on beat four must move later accepted ' ...
    'boundaries even without an immediate LAST hold-value change.']);

%% Complete bounded healthy/fault grid and fixed resource contract
for packetLength = [2 3 4 6]
    for consumerStallCycles = 0:6
        healthyGrid = model(packetLength,consumerStallCycles,false);
        healthyAgain = model(packetLength,consumerStallCycles,false);
        brokenGrid = model(packetLength,consumerStallCycles,true);
        assert(isequaln(healthyGrid,healthyAgain) && ...
            healthyGrid.applied.dataCompleted && ...
            healthyGrid.applied.framingValid && ...
            healthyGrid.applied.completionCycle == ...
                12+consumerStallCycles && ...
            isequal(healthyGrid.applied.acceptedBeatOrdinals,(1:12).') && ...
            isequal(healthyGrid.applied.acceptedPayloadWords, ...
                expectedPayloadWords) && ...
            healthyGrid.applied.lostBeatCount == 0 && ...
            healthyGrid.applied.duplicateBeatCount == 0 && ...
            healthyGrid.applied.outOfOrderCount == 0 && ...
            healthyGrid.applied.payloadHoldViolationCount == 0 && ...
            healthyGrid.applied.lastHoldViolationCount == 0, ...
            'P11:HealthyGrid', ...
            'Every bounded healthy control pair must preserve whole packets.');
        assert(isequaln(brokenGrid.reference,healthyGrid.applied) && ...
            brokenGrid.applied.dataCompleted && ...
            isequal(brokenGrid.applied.acceptedBeatOrdinals,(1:12).') && ...
            brokenGrid.applied.payloadHoldViolationCount == 0 && ...
            brokenGrid.faultActive == (consumerStallCycles > 0) && ...
            brokenGrid.frameFaultVisible == ...
                (mod(consumerStallCycles,packetLength) ~= 0), ...
            'P11:BrokenGrid', ...
            ['Fault grid must preserve payload data and expose framing ' ...
            'corruption exactly when marker drift is not a whole packet.']);
        assert(numel(healthyGrid.cycle) == 24 && ...
            numel(healthyGrid.consumerReady) == 24 && ...
            numel(healthyGrid.applied.sourcePayloadWord) == 24 && ...
            numel(healthyGrid.applied.sourceLast) == 24 && ...
            numel(healthyGrid.payloadWords) == 12 && ...
            healthyGrid.maxRecordCycles == 24 && ...
            healthyGrid.maxBeatCount == 12 && ...
            healthyGrid.maxPacketCount == 6 && ...
            healthyGrid.modeledPayloadBits == 12 && ...
            healthyGrid.applied.traceCycleCount == 24 && ...
            healthyGrid.applied.traceBeatCapacity == 12 && ...
            healthyGrid.applied.completionCycle <= 18, ...
            'P11:ResourceBound', ...
            'Fixed trace, beat, packet, payload, and completion bounds changed.');
    end
end

%% Malformed inputs and deterministic recovery after failures and other calls
assertRejects(@() model(1,3,false),'P11:InvalidPacketLength');
assertRejects(@() model(5,3,false),'P11:InvalidPacketLength');
assertRejects(@() model(2.5,3,false),'P11:InvalidPacketLength');
assertRejects(@() model([2 4],3,false),'P11:InvalidPacketLength');
assertRejects(@() model(NaN,3,false),'P11:InvalidPacketLength');
assertRejects(@() model(Inf,3,false),'P11:InvalidPacketLength');
assertRejects(@() model(4+1i,3,false),'P11:InvalidPacketLength');
assertRejects(@() model(true,3,false),'P11:InvalidPacketLength');
assertRejects(@() model(4,-1,false), ...
    'P11:InvalidConsumerStallCycles');
assertRejects(@() model(4,7,false), ...
    'P11:InvalidConsumerStallCycles');
assertRejects(@() model(4,2.5,false), ...
    'P11:InvalidConsumerStallCycles');
assertRejects(@() model(4,[2 3],false), ...
    'P11:InvalidConsumerStallCycles');
assertRejects(@() model(4,NaN,false), ...
    'P11:InvalidConsumerStallCycles');
assertRejects(@() model(4,Inf,false), ...
    'P11:InvalidConsumerStallCycles');
assertRejects(@() model(4,3+1i,false), ...
    'P11:InvalidConsumerStallCycles');
assertRejects(@() model(4,true,false), ...
    'P11:InvalidConsumerStallCycles');
assertRejects(@() model(4,3,2),'P11:InvalidBrokenAdvanceLast');
assertRejects(@() model(4,3,0.5),'P11:InvalidBrokenAdvanceLast');
assertRejects(@() model(4,3,[false true]), ...
    'P11:InvalidBrokenAdvanceLast');
assertRejects(@() model(4,3,NaN),'P11:InvalidBrokenAdvanceLast');
assertRejects(@() model(4,3,Inf),'P11:InvalidBrokenAdvanceLast');
assertRejects(@() model(4,3,1+1i),'P11:InvalidBrokenAdvanceLast');
baselineAfterFailures = model(4,3,false);
maximumHealthyCall = model(6,6,false); %#ok<NASGU>
brokenCall = model(4,3,true); %#ok<NASGU>
baselineAfterOtherCalls = model(4,3,false);
assert(isequaln(baseline,baselineAfterFailures) && ...
    isequaln(baseline,baselineAfterOtherCalls), ...
    'P11:DeterminismRecovery', ...
    'Baseline must recover after malformed, maximum, and fault calls.');

disp(['P11 checks passed: packet boundaries, two isolated sweeps, ' ...
    'broken LAST, hidden state advance, validation, limits, isolation, ' ...
    'bounds, and recovery.']);
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P11:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
