function out = model(burstCycles,arrivalRateWordsPerCycle, ...
        serviceRateWordsPerCycle,fifoDepthWords, ...
        brokenAssumeFallThrough)
%MODEL Size a bounded registered FIFO from a finite burst and service rate.
%   The FIFO is empty initially and is registered, not fall-through.
%   Stored words depart first on an edge; their freed slots may accept new
%   words on that edge, but newly arriving words cannot depart immediately.

if nargin < 1
    burstCycles = 8;
end
if nargin < 2
    arrivalRateWordsPerCycle = 3;
end
if nargin < 3
    serviceRateWordsPerCycle = 1;
end
if nargin < 4
    fifoDepthWords = 17;
end
if nargin < 5
    brokenAssumeFallThrough = false;
end

maximumBurstCycles = 8;
maximumArrivalRateWordsPerCycle = 4;
maximumServiceRateWordsPerCycle = 4;
maximumFifoDepthWords = 32;
recordCycleCount = 40;

validateIntegerScalar(burstCycles,1,maximumBurstCycles, ...
    'P12:InvalidBurstCycles','burstCycles');
validateIntegerScalar(arrivalRateWordsPerCycle,1, ...
    maximumArrivalRateWordsPerCycle, ...
    'P12:InvalidArrivalRate','arrivalRateWordsPerCycle');
validateIntegerScalar(serviceRateWordsPerCycle,0, ...
    maximumServiceRateWordsPerCycle, ...
    'P12:InvalidServiceRate','serviceRateWordsPerCycle');
validateIntegerScalar(fifoDepthWords,0,maximumFifoDepthWords, ...
    'P12:InvalidFifoDepth','fifoDepthWords');
validateBooleanScalar(brokenAssumeFallThrough);

burstCycles = double(burstCycles);
arrivalRateWordsPerCycle = double(arrivalRateWordsPerCycle);
serviceRateWordsPerCycle = double(serviceRateWordsPerCycle);
fifoDepthWords = double(fifoDepthWords);
brokenAssumeFallThrough = logical(brokenAssumeFallThrough);

cycle = (1:recordCycleCount).';
arrivalWords = zeros(recordCycleCount,1);
arrivalWords(1:burstCycles) = arrivalRateWordsPerCycle;
serviceCapacityWords = serviceRateWordsPerCycle* ...
    ones(recordCycleCount,1);

reference = simulateUnbounded(arrivalWords,serviceCapacityWords);
analyticRequiredDepthWords = arrivalRateWordsPerCycle+ ...
    (burstCycles-1)*max(arrivalRateWordsPerCycle- ...
    serviceRateWordsPerCycle,0);
fallThroughEstimateWords = burstCycles* ...
    max(arrivalRateWordsPerCycle-serviceRateWordsPerCycle,0);

if brokenAssumeFallThrough
    appliedDepthWords = fallThroughEstimateWords;
    appliedDepthBasis = 'broken fall-through estimate';
else
    appliedDepthWords = fifoDepthWords;
    appliedDepthBasis = 'configured registered-FIFO depth';
end

applied = simulateFinite(arrivalWords,serviceCapacityWords, ...
    appliedDepthWords);
capacityDeficitWords = max(reference.occupancyAfter-appliedDepthWords,0);

out = struct( ...
    'burstCycles',burstCycles, ...
    'arrivalRateWordsPerCycle',arrivalRateWordsPerCycle, ...
    'serviceRateWordsPerCycle',serviceRateWordsPerCycle, ...
    'fifoDepthWords',fifoDepthWords, ...
    'brokenAssumeFallThrough',brokenAssumeFallThrough, ...
    'initialOccupancyWords',0, ...
    'burstWordCount',sum(arrivalWords), ...
    'cycle',cycle, ...
    'arrivalWords',arrivalWords, ...
    'serviceCapacityWords',serviceCapacityWords, ...
    'reference',reference, ...
    'applied',applied, ...
    'requiredDepthWords',reference.requiredDepthWords, ...
    'analyticRequiredDepthWords',analyticRequiredDepthWords, ...
    'fallThroughEstimateWords',fallThroughEstimateWords, ...
    'appliedDepthWords',appliedDepthWords, ...
    'appliedDepthBasis',appliedDepthBasis, ...
    'depthMarginWords',appliedDepthWords-reference.requiredDepthWords, ...
    'depthShortfallWords', ...
        max(reference.requiredDepthWords-appliedDepthWords,0), ...
    'capacityDeficitWords',capacityDeficitWords, ...
    'peakCapacityDeficitWords',max(capacityDeficitWords), ...
    'faultSelected',brokenAssumeFallThrough, ...
    'faultActive',brokenAssumeFallThrough && ...
        fallThroughEstimateWords < reference.requiredDepthWords, ...
    'faultVisible',brokenAssumeFallThrough && ...
        applied.notAcceptedWordCount > 0, ...
    'recordCycleCount',recordCycleCount, ...
    'maximumBurstCycles',maximumBurstCycles, ...
    'maximumArrivalRateWordsPerCycle', ...
        maximumArrivalRateWordsPerCycle, ...
    'maximumServiceRateWordsPerCycle', ...
        maximumServiceRateWordsPerCycle, ...
    'maximumFifoDepthWords',maximumFifoDepthWords, ...
    'maximumBurstWordCount',maximumBurstCycles* ...
        maximumArrivalRateWordsPerCycle, ...
    'referenceEquationText', ...
        ['qAfter[n] = arrivals[n] + max(0, qAfter[n-1] ' ...
        '- service[n])'], ...
    'requiredDepthEquationText', ...
        'Drequired = max(qAfter[n])', ...
    'constantRateEquationText', ...
        'Drequired = A + (B-1)*max(A-S,0)', ...
    'finiteAdmissionEquationText', ...
        ['admitted[n] = min(arrivals[n], D - ' ...
        '(qBefore[n]-departed[n]))'], ...
    'registeredRuleText', ...
        ['stored words may depart before admission on one edge; new ' ...
        'arrivals cannot depart until a later edge'], ...
    'backpressureRuleText', ...
        ['not-accepted words require valid/ready hold and retry; they ' ...
        'are lost only if the source cannot or does not backpressure']);
end

function path = simulateUnbounded(arrivalWords,serviceCapacityWords)
recordCycleCount = numel(arrivalWords);
occupancyBefore = zeros(recordCycleCount,1);
occupancyAfter = zeros(recordCycleCount,1);
departedWords = zeros(recordCycleCount,1);
unusedServiceWords = zeros(recordCycleCount,1);
queueWords = 0;

for cycleIndex = 1:recordCycleCount
    occupancyBefore(cycleIndex) = queueWords;
    departedWords(cycleIndex) = min( ...
        serviceCapacityWords(cycleIndex),queueWords);
    unusedServiceWords(cycleIndex) = ...
        serviceCapacityWords(cycleIndex)-departedWords(cycleIndex);
    queueWords = queueWords-departedWords(cycleIndex)+ ...
        arrivalWords(cycleIndex);
    occupancyAfter(cycleIndex) = queueWords;
end

cumulativeArrivals = cumsum(arrivalWords);
cumulativeDepartures = cumsum(departedWords);
requiredDepthWords = max(occupancyAfter);
peakCycle = find(occupancyAfter == requiredDepthWords,1,'first');
totalArrivalWords = sum(arrivalWords);
drainComplete = queueWords == 0 && ...
    sum(departedWords) == totalArrivalWords;
if drainComplete && totalArrivalWords > 0
    drainCompleteCycle = find( ...
        cumulativeDepartures == totalArrivalWords,1,'first');
else
    drainCompleteCycle = NaN;
end

path = struct( ...
    'occupancyBefore',occupancyBefore, ...
    'occupancyAfter',occupancyAfter, ...
    'departedWords',departedWords, ...
    'unusedServiceWords',unusedServiceWords, ...
    'cumulativeArrivals',cumulativeArrivals, ...
    'cumulativeDepartures',cumulativeDepartures, ...
    'cumulativeGapWords',cumulativeArrivals-cumulativeDepartures, ...
    'recurrenceResidual',occupancyAfter-occupancyBefore+ ...
        departedWords-arrivalWords, ...
    'finalConservationResidual',totalArrivalWords- ...
        sum(departedWords)-occupancyAfter(end), ...
    'requiredDepthWords',requiredDepthWords, ...
    'peakCycle',peakCycle, ...
    'totalArrivalWords',totalArrivalWords, ...
    'totalDepartedWords',sum(departedWords), ...
    'drainComplete',drainComplete, ...
    'drainCompleteCycle',drainCompleteCycle, ...
    'drainTimedOut',~drainComplete, ...
    'traceCycleCount',recordCycleCount);
end

function path = simulateFinite(arrivalWords,serviceCapacityWords,depthWords)
recordCycleCount = numel(arrivalWords);
occupancyBefore = zeros(recordCycleCount,1);
occupancyAfter = zeros(recordCycleCount,1);
departedWords = zeros(recordCycleCount,1);
admittedWords = zeros(recordCycleCount,1);
notAcceptedWords = zeros(recordCycleCount,1);
freeSlotsBeforeAdmission = zeros(recordCycleCount,1);
headroomAfter = zeros(recordCycleCount,1);
replacementWords = zeros(recordCycleCount,1);
queueWords = 0;

for cycleIndex = 1:recordCycleCount
    occupancyBefore(cycleIndex) = queueWords;
    departedWords(cycleIndex) = min( ...
        serviceCapacityWords(cycleIndex),queueWords);
    storedAfterDeparture = queueWords-departedWords(cycleIndex);
    freeSlotsBeforeAdmission(cycleIndex) = ...
        depthWords-storedAfterDeparture;
    admittedWords(cycleIndex) = min(arrivalWords(cycleIndex), ...
        freeSlotsBeforeAdmission(cycleIndex));
    notAcceptedWords(cycleIndex) = ...
        arrivalWords(cycleIndex)-admittedWords(cycleIndex);
    replacementWords(cycleIndex) = min( ...
        departedWords(cycleIndex),admittedWords(cycleIndex));
    queueWords = storedAfterDeparture+admittedWords(cycleIndex);
    occupancyAfter(cycleIndex) = queueWords;
    headroomAfter(cycleIndex) = depthWords-queueWords;
end

cumulativeAdmitted = cumsum(admittedWords);
cumulativeDeparted = cumsum(departedWords);
cumulativeNotAccepted = cumsum(notAcceptedWords);
totalOfferedWords = sum(arrivalWords);
totalAdmittedWords = sum(admittedWords);
allAdmittedDrained = queueWords == 0 && ...
    sum(departedWords) == totalAdmittedWords;
if allAdmittedDrained && totalAdmittedWords > 0
    admittedDrainCycle = find( ...
        cumulativeDeparted == totalAdmittedWords,1,'first');
else
    admittedDrainCycle = NaN;
end
allOfferedDelivered = allAdmittedDrained && ...
    sum(notAcceptedWords) == 0 && ...
    sum(departedWords) == totalOfferedWords;

path = struct( ...
    'depthWords',depthWords, ...
    'occupancyBefore',occupancyBefore, ...
    'occupancyAfter',occupancyAfter, ...
    'departedWords',departedWords, ...
    'admittedWords',admittedWords, ...
    'notAcceptedWords',notAcceptedWords, ...
    'freeSlotsBeforeAdmission',freeSlotsBeforeAdmission, ...
    'headroomAfter',headroomAfter, ...
    'replacementWords',replacementWords, ...
    'cumulativeAdmitted',cumulativeAdmitted, ...
    'cumulativeDeparted',cumulativeDeparted, ...
    'cumulativeNotAccepted',cumulativeNotAccepted, ...
    'recurrenceResidual',occupancyAfter-occupancyBefore+ ...
        departedWords-admittedWords, ...
    'offerResidual',arrivalWords-admittedWords-notAcceptedWords, ...
    'finalConservationResidual',totalAdmittedWords- ...
        sum(departedWords)-occupancyAfter(end), ...
    'offeredWordCount',totalOfferedWords, ...
    'admittedWordCount',totalAdmittedWords, ...
    'departedWordCount',sum(departedWords), ...
    'notAcceptedWordCount',sum(notAcceptedWords), ...
    'conditionalLossIfIgnoredWords',sum(notAcceptedWords), ...
    'backpressureRequired',any(notAcceptedWords > 0), ...
    'firstBackpressureCycle',firstTrueOrNaN(notAcceptedWords > 0), ...
    'peakOccupancyWords',max(occupancyAfter), ...
    'minimumHeadroomWords',min(headroomAfter), ...
    'allAdmittedDrained',allAdmittedDrained, ...
    'admittedDrainCycle',admittedDrainCycle, ...
    'allOfferedDelivered',allOfferedDelivered, ...
    'drainTimedOut',queueWords > 0, ...
    'traceCycleCount',recordCycleCount);
end

function cycleIndex = firstTrueOrNaN(mask)
cycleIndex = find(mask,1,'first');
if isempty(cycleIndex)
    cycleIndex = NaN;
end
end

function validateIntegerScalar(value,minimumValue,maximumValue, ...
        errorIdentifier,label)
valid = isnumeric(value) && ~islogical(value) && isscalar(value) && ...
    isreal(value) && isfinite(value) && value == fix(value) && ...
    value >= minimumValue && value <= maximumValue;
if ~valid
    error(errorIdentifier, ...
        '%s must be a finite integer scalar from %g through %g.', ...
        label,minimumValue,maximumValue);
end
end

function validateBooleanScalar(value)
logicalScalar = islogical(value) && isscalar(value);
numericFlag = isnumeric(value) && ~islogical(value) && ...
    isscalar(value) && isreal(value) && isfinite(value) && ...
    (value == 0 || value == 1);
if ~(logicalScalar || numericFlag)
    error('P12:InvalidBrokenAssumeFallThrough', ...
        'brokenAssumeFallThrough must be a logical scalar or numeric 0/1.');
end
end
