function run_checks
%RUN_CHECKS Verify P12 registered-FIFO sizing and failure boundaries.

%% Exact deterministic baseline and independent recurrence
baseline = model(8,3,1,17,false);
baselineAgain = model(8,3,1,17,false);
expectedOccupancy = [3 5 7 9 11 13 15 17 ...
    16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 ...
    zeros(1,15)].';
expectedDepartures = zeros(40,1);
expectedDepartures(2:25) = 1;
assert(isequaln(baseline,baselineAgain), ...
    'P12:BaselineDeterminism', ...
    'Repeated baseline calls must return exactly the same structure.');
assert(isequal(baseline.cycle,(1:40).') && ...
    isequal(baseline.arrivalWords,[3*ones(8,1);zeros(32,1)]) && ...
    isequal(baseline.serviceCapacityWords,ones(40,1)) && ...
    isequal(baseline.reference.occupancyAfter,expectedOccupancy) && ...
    isequal(baseline.reference.departedWords,expectedDepartures), ...
    'P12:BaselineTrace', ...
    'Baseline arrivals, service, occupancy, or departures changed.');
assert(all(baseline.reference.recurrenceResidual == 0) && ...
    baseline.reference.finalConservationResidual == 0 && ...
    isequal(baseline.reference.cumulativeGapWords, ...
        baseline.reference.occupancyAfter) && ...
    baseline.reference.totalArrivalWords == 24 && ...
    baseline.reference.totalDepartedWords == 24, ...
    'P12:ReferenceConservation', ...
    'The unbounded registered recurrence or conservation identity failed.');

%% Required depth, exact capacity, and drain metrics
assert(baseline.requiredDepthWords == 17 && ...
    baseline.analyticRequiredDepthWords == 17 && ...
    baseline.reference.peakCycle == 8 && ...
    baseline.reference.drainComplete && ...
    baseline.reference.drainCompleteCycle == 25 && ...
    ~baseline.reference.drainTimedOut, ...
    'P12:BaselineSizing', ...
    'The 24-word baseline must require 17 words and drain on cycle 25.');
assert(isequal(baseline.applied.occupancyAfter,expectedOccupancy) && ...
    isequal(baseline.applied.departedWords,expectedDepartures) && ...
    all(baseline.applied.admittedWords(1:8) == 3) && ...
    all(baseline.applied.admittedWords(9:end) == 0) && ...
    baseline.applied.notAcceptedWordCount == 0 && ...
    baseline.applied.allOfferedDelivered && ...
    baseline.applied.admittedDrainCycle == 25 && ...
    baseline.depthMarginWords == 0 && ...
    baseline.peakCapacityDeficitWords == 0, ...
    'P12:ExactDepth', ...
    'Exactly 17 registered slots must admit and drain all 24 words.');
assert(all(baseline.applied.recurrenceResidual == 0) && ...
    all(baseline.applied.offerResidual == 0) && ...
    baseline.applied.finalConservationResidual == 0 && ...
    baseline.applied.admittedWordCount == ...
        baseline.applied.departedWordCount && ...
    baseline.applied.offeredWordCount == ...
        baseline.applied.admittedWordCount, ...
    'P12:FiniteConservation', ...
    'Offered, admitted, departed, and stored word accounting must close.');

%% One word below the requirement produces the first exact capacity symptom
oneWordShort = model(8,3,1,16,false);
assert(oneWordShort.depthShortfallWords == 1 && ...
    oneWordShort.applied.notAcceptedWordCount == 1 && ...
    isequal(find(oneWordShort.applied.notAcceptedWords),8) && ...
    oneWordShort.applied.notAcceptedWords(8) == 1 && ...
    oneWordShort.applied.firstBackpressureCycle == 8 && ...
    oneWordShort.applied.admittedWordCount == 23 && ...
    oneWordShort.applied.departedWordCount == 23 && ...
    oneWordShort.applied.admittedDrainCycle == 24 && ...
    ~oneWordShort.applied.allOfferedDelivered && ...
    ~oneWordShort.faultSelected && ~oneWordShort.faultActive && ...
    ~oneWordShort.faultVisible && ...
    oneWordShort.applied.conditionalLossIfIgnoredWords == 1, ...
    'P12:OneWordShort', ...
    ['Depth 16 must require one held/retried word on cycle 8; it is ' ...
    'conditionally lost only when backpressure is ignored.']);

%% Zero-depth registered boundary has no implicit fall-through path
zeroDepth = model(8,3,1,0,false);
assert(zeroDepth.applied.depthWords == 0 && ...
    all(zeroDepth.applied.occupancyBefore == 0) && ...
    all(zeroDepth.applied.occupancyAfter == 0) && ...
    all(zeroDepth.applied.admittedWords == 0) && ...
    all(zeroDepth.applied.departedWords == 0) && ...
    isequal(zeroDepth.applied.notAcceptedWords,zeroDepth.arrivalWords) && ...
    zeroDepth.applied.offeredWordCount == 24 && ...
    zeroDepth.applied.admittedWordCount == 0 && ...
    zeroDepth.applied.departedWordCount == 0 && ...
    zeroDepth.applied.notAcceptedWordCount == 24 && ...
    zeroDepth.applied.backpressureRequired && ...
    zeroDepth.applied.firstBackpressureCycle == 1 && ...
    zeroDepth.applied.allAdmittedDrained && ...
    isnan(zeroDepth.applied.admittedDrainCycle) && ...
    ~zeroDepth.applied.allOfferedDelivered && ...
    ~zeroDepth.applied.drainTimedOut && ...
    all(zeroDepth.applied.recurrenceResidual == 0) && ...
    all(zeroDepth.applied.offerResidual == 0) && ...
    zeroDepth.applied.finalConservationResidual == 0 && ...
    ~zeroDepth.faultSelected && ~zeroDepth.faultActive && ...
    ~zeroDepth.faultVisible, ...
    'P12:ZeroDepthRegisteredBoundary', ...
    ['Depth zero must refuse the complete fixed burst without creating ' ...
    'an implicit fall-through path, stored work, or a false fault.']);

%% Sweep 1 - burst duration changes only exposure to the rate mismatch
burstSweep = [1 2 4 6 8];
expectedBurstWords = [3 6 12 18 24];
expectedBurstDepths = [3 5 9 13 17];
expectedBurstCompletion = [4 7 13 19 25];
observedBurstDepths = zeros(size(burstSweep));
for sweepIndex = 1:numel(burstSweep)
    current = model(burstSweep(sweepIndex),3,1,32,false);
    observedBurstDepths(sweepIndex) = current.requiredDepthWords;
    assert(current.burstWordCount == expectedBurstWords(sweepIndex) && ...
        current.reference.drainCompleteCycle == ...
            expectedBurstCompletion(sweepIndex) && ...
        current.arrivalRateWordsPerCycle == 3 && ...
        current.serviceRateWordsPerCycle == 1 && ...
        current.fifoDepthWords == 32 && ...
        ~current.brokenAssumeFallThrough && ...
        all(current.arrivalWords(1:current.burstCycles) == 3) && ...
        all(current.arrivalWords(current.burstCycles+1:end) == 0) && ...
        current.applied.notAcceptedWordCount == 0, ...
        'P12:BurstSweepIsolation', ...
        'Burst sweep changed a fixed lever or lost a word.');
end
assert(isequal(observedBurstDepths,expectedBurstDepths), ...
    'P12:BurstSweepDepths', ...
    'Burst sweep depths must be [3 5 9 13 17] words.');

%% Sweep 2 - service rate changes only removal capacity
serviceSweep = 0:4;
expectedServiceDepths = [24 17 10 3 3];
expectedServiceCompletion = [NaN 25 13 9 9];
observedServiceDepths = zeros(size(serviceSweep));
observedServiceCompletion = NaN(size(serviceSweep));
for sweepIndex = 1:numel(serviceSweep)
    current = model(8,3,serviceSweep(sweepIndex),32,false);
    observedServiceDepths(sweepIndex) = current.requiredDepthWords;
    observedServiceCompletion(sweepIndex) = ...
        current.reference.drainCompleteCycle;
    assert(current.burstCycles == 8 && ...
        current.arrivalRateWordsPerCycle == 3 && ...
        current.fifoDepthWords == 32 && ...
        ~current.brokenAssumeFallThrough && ...
        isequal(current.arrivalWords,[3*ones(8,1);zeros(32,1)]) && ...
        current.applied.notAcceptedWordCount == 0, ...
        'P12:ServiceSweepIsolation', ...
        'Service sweep changed the fixed burst or selected depth.');
end
assert(isequal(observedServiceDepths,expectedServiceDepths) && ...
    isequaln(observedServiceCompletion,expectedServiceCompletion), ...
    'P12:ServiceSweepResults', ...
    'Service sweep depth or completion results changed.');

%% Limiting cases - no service, matched service, and full replacement
noService = model(8,3,0,24,false);
assert(noService.requiredDepthWords == 24 && ...
    isequal(noService.reference.occupancyAfter(1:8),(3:3:24).') && ...
    all(noService.reference.occupancyAfter(9:end) == 24) && ...
    all(noService.reference.departedWords == 0) && ...
    ~noService.reference.drainComplete && ...
    isnan(noService.reference.drainCompleteCycle) && ...
    noService.reference.drainTimedOut && ...
    noService.applied.notAcceptedWordCount == 0 && ...
    noService.applied.drainTimedOut, ...
    'P12:NoServiceLimit', ...
    'Zero service must retain the whole finite burst and end bounded.');
matchedService = model(8,3,3,3,false);
fasterService = model(8,3,4,3,false);
assert(matchedService.requiredDepthWords == 3 && ...
    fasterService.requiredDepthWords == 3 && ...
    all(matchedService.reference.occupancyAfter(1:8) == 3) && ...
    all(fasterService.reference.occupancyAfter(1:8) == 3) && ...
    matchedService.reference.drainCompleteCycle == 9 && ...
    fasterService.reference.drainCompleteCycle == 9 && ...
    sum(matchedService.applied.replacementWords(2:8)) == 21 && ...
    matchedService.applied.notAcceptedWordCount == 0 && ...
    fasterService.applied.notAcceptedWordCount == 0, ...
    'P12:RegisteredStagingLimit', ...
    ['Matched or faster service still needs one three-word registered ' ...
    'staging batch; same-edge replacement preserves throughput.']);

%% Deliberately broken case - fall-through sizing on a registered FIFO
broken = model(8,3,1,17,true);
assert(isequaln(broken.reference,baseline.reference) && ...
    broken.fallThroughEstimateWords == 16 && ...
    broken.appliedDepthWords == 16 && ...
    strcmp(broken.appliedDepthBasis,'broken fall-through estimate') && ...
    broken.faultSelected && broken.faultActive && broken.faultVisible && ...
    broken.depthShortfallWords == 1 && ...
    broken.applied.notAcceptedWordCount == 1 && ...
    isequal(find(broken.applied.notAcceptedWords),8) && ...
    isequaln(broken.applied,oneWordShort.applied), ...
    'P12:BrokenFallThrough', ...
    ['The broken estimate must under-size by one word and expose the ' ...
    'cycle-eight admission failure without changing the reference.']);
brokenInert = model(8,3,0,17,true);
assert(brokenInert.faultSelected && ~brokenInert.faultActive && ...
    ~brokenInert.faultVisible && ...
    brokenInert.fallThroughEstimateWords == 24 && ...
    brokenInert.requiredDepthWords == 24 && ...
    brokenInert.applied.notAcceptedWordCount == 0, ...
    'P12:BrokenInertLimit', ...
    'With zero service, registered and fall-through estimates must agree.');

%% Accepted numeric classes and exact normalization
typedBaseline = model(uint8(8),uint8(3),uint8(1),uint8(17),uint8(0));
typedBroken = model(uint8(8),uint8(3),uint8(1),uint8(17),uint8(1));
assert(isequaln(typedBaseline,baseline) && isequaln(typedBroken,broken), ...
    'P12:TypedInputEquivalence', ...
    'Accepted integer classes and numeric flags must normalize exactly.');

%% Complete bounded grid, resource limits, isolation, and drain timeout
for burstCycles = 1:8
    for arrivalRate = 1:4
        for serviceRate = 0:4
            exactDepth = arrivalRate+(burstCycles-1)* ...
                max(arrivalRate-serviceRate,0);
            healthy = model(burstCycles,arrivalRate,serviceRate, ...
                exactDepth,false);
            healthyAgain = model(burstCycles,arrivalRate,serviceRate, ...
                exactDepth,false);
            faulty = model(burstCycles,arrivalRate,serviceRate, ...
                exactDepth,true);
            assert(isequaln(healthy,healthyAgain) && ...
                healthy.requiredDepthWords == exactDepth && ...
                healthy.analyticRequiredDepthWords == exactDepth && ...
                healthy.applied.notAcceptedWordCount == 0 && ...
                all(healthy.reference.recurrenceResidual == 0) && ...
                all(healthy.applied.recurrenceResidual == 0) && ...
                all(healthy.applied.offerResidual == 0) && ...
                healthy.reference.finalConservationResidual == 0 && ...
                healthy.applied.finalConservationResidual == 0, ...
                'P12:HealthyGrid', ...
                'Every exact-depth grid point must conserve all words.');
            assert(isequaln(faulty.reference,healthy.reference) && ...
                faulty.faultActive == (serviceRate > 0) && ...
                faulty.faultVisible == (serviceRate > 0) && ...
                (faulty.applied.notAcceptedWordCount > 0) == ...
                    (serviceRate > 0), ...
                'P12:FaultGrid', ...
                'Fault activation, visibility, or reference isolation changed.');
            assert(numel(healthy.cycle) == 40 && ...
                numel(healthy.arrivalWords) == 40 && ...
                healthy.burstWordCount <= 32 && ...
                healthy.requiredDepthWords <= 32 && ...
                healthy.recordCycleCount == 40 && ...
                healthy.maximumBurstWordCount == 32 && ...
                healthy.maximumFifoDepthWords == 32, ...
                'P12:ResourceBound', ...
                'Fixed trace, burst, or storage bounds changed.');
            if serviceRate == 0
                assert(healthy.reference.drainTimedOut && ...
                    isnan(healthy.reference.drainCompleteCycle), ...
                    'P12:BoundedNoDrain', ...
                    'Zero-service cases must return without claiming drain.');
            else
                assert(healthy.reference.drainComplete && ...
                    healthy.reference.drainCompleteCycle <= 33, ...
                    'P12:BoundedCompletion', ...
                    'Every positive-service case must drain by cycle 33.');
            end
        end
    end
end

%% Malformed inputs and deterministic recovery
assertRejects(@() model(0,3,1,17,false),'P12:InvalidBurstCycles');
assertRejects(@() model(9,3,1,17,false),'P12:InvalidBurstCycles');
assertRejects(@() model(2.5,3,1,17,false),'P12:InvalidBurstCycles');
assertRejects(@() model([8 8],3,1,17,false),'P12:InvalidBurstCycles');
assertRejects(@() model(NaN,3,1,17,false),'P12:InvalidBurstCycles');
assertRejects(@() model(Inf,3,1,17,false),'P12:InvalidBurstCycles');
assertRejects(@() model(8+1i,3,1,17,false),'P12:InvalidBurstCycles');
assertRejects(@() model(true,3,1,17,false),'P12:InvalidBurstCycles');
assertRejects(@() model(8,0,1,17,false),'P12:InvalidArrivalRate');
assertRejects(@() model(8,5,1,17,false),'P12:InvalidArrivalRate');
assertRejects(@() model(8,2.5,1,17,false),'P12:InvalidArrivalRate');
assertRejects(@() model(8,[3 4],1,17,false),'P12:InvalidArrivalRate');
assertRejects(@() model(8,NaN,1,17,false),'P12:InvalidArrivalRate');
assertRejects(@() model(8,Inf,1,17,false),'P12:InvalidArrivalRate');
assertRejects(@() model(8,3+1i,1,17,false),'P12:InvalidArrivalRate');
assertRejects(@() model(8,true,1,17,false),'P12:InvalidArrivalRate');
assertRejects(@() model(8,3,-1,17,false),'P12:InvalidServiceRate');
assertRejects(@() model(8,3,5,17,false),'P12:InvalidServiceRate');
assertRejects(@() model(8,3,0.5,17,false),'P12:InvalidServiceRate');
assertRejects(@() model(8,3,[1 2],17,false),'P12:InvalidServiceRate');
assertRejects(@() model(8,3,NaN,17,false),'P12:InvalidServiceRate');
assertRejects(@() model(8,3,Inf,17,false),'P12:InvalidServiceRate');
assertRejects(@() model(8,3,1+1i,17,false),'P12:InvalidServiceRate');
assertRejects(@() model(8,3,true,17,false),'P12:InvalidServiceRate');
assertRejects(@() model(8,3,1,-1,false),'P12:InvalidFifoDepth');
assertRejects(@() model(8,3,1,33,false),'P12:InvalidFifoDepth');
assertRejects(@() model(8,3,1,16.5,false),'P12:InvalidFifoDepth');
assertRejects(@() model(8,3,1,[16 17],false),'P12:InvalidFifoDepth');
assertRejects(@() model(8,3,1,NaN,false),'P12:InvalidFifoDepth');
assertRejects(@() model(8,3,1,Inf,false),'P12:InvalidFifoDepth');
assertRejects(@() model(8,3,1,17+1i,false),'P12:InvalidFifoDepth');
assertRejects(@() model(8,3,1,true,false),'P12:InvalidFifoDepth');
assertRejects(@() model(8,3,1,17,2), ...
    'P12:InvalidBrokenAssumeFallThrough');
assertRejects(@() model(8,3,1,17,0.5), ...
    'P12:InvalidBrokenAssumeFallThrough');
assertRejects(@() model(8,3,1,17,[false true]), ...
    'P12:InvalidBrokenAssumeFallThrough');
assertRejects(@() model(8,3,1,17,NaN), ...
    'P12:InvalidBrokenAssumeFallThrough');
assertRejects(@() model(8,3,1,17,Inf), ...
    'P12:InvalidBrokenAssumeFallThrough');
assertRejects(@() model(8,3,1,17,1+1i), ...
    'P12:InvalidBrokenAssumeFallThrough');
baselineAfterFailures = model(8,3,1,17,false);
maximumCall = model(8,4,1,32,false); %#ok<NASGU>
zeroServiceCall = model(8,4,0,32,false); %#ok<NASGU>
brokenCall = model(8,3,1,17,true); %#ok<NASGU>
baselineAfterOtherCalls = model(8,3,1,17,false);
assert(isequaln(baseline,baselineAfterFailures) && ...
    isequaln(baseline,baselineAfterOtherCalls), ...
    'P12:DeterminismRecovery', ...
    'Baseline must recover after malformed, maximum, timeout, and fault calls.');

disp(['P12 checks passed: registered sizing, exact depth, two isolated ' ...
    'sweeps, fall-through fault, limits, malformed inputs, timeout, ' ...
    'isolation, resource bounds, and recovery.']);
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P12:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
