function interactive
%INTERACTIVE Explore multiplier replication, demand, and schedule coverage.
clear model;
modelFcn = @model;
figureName = 'P07 Resource and Throughput Explorer';
delete(findall(groot,'Type','figure','Name',figureName));

fig = uifigure('Name',figureName,'Position',[70 70 1220 780]);
gridLayout = uigridlayout(fig,[4 4]);
gridLayout.RowHeight = {68,'1x',120,148};
gridLayout.ColumnWidth = {'1x','1x','1x','1x'};

instruction = uilabel(gridLayout,'WordWrap','on', ...
    'Text',['Read the two-lane baseline first. Change modeled multiplier ' ...
    'lanes or offered frame interval independently. Lanes set raw work ' ...
    'capacity; the frame policy and packing set complete-frame capacity; ' ...
    'the source sets demand. At a non-divisor lane count, enable floor ' ...
    'scheduling to expose uncovered tail products.']);
instruction.Layout.Row = 1;
instruction.Layout.Column = [1 4];

scheduleAxes = uiaxes(gridLayout);
scheduleAxes.Layout.Row = 2;
scheduleAxes.Layout.Column = [1 2];
productAxes = uiaxes(gridLayout);
productAxes.Layout.Row = 2;
productAxes.Layout.Column = [3 4];

resourcePanel = uipanel(gridLayout, ...
    'Title','Lever 1: modeled multiplier lanes');
resourcePanel.Layout.Row = 3;
resourcePanel.Layout.Column = 1;
resourceGrid = uigridlayout(resourcePanel,[2 1]);
resourceGrid.RowHeight = {50,'1x'};
uilabel(resourceGrid,'WordWrap','on', ...
    'Text','Adds issue slots and product-pipeline storage; ceiling sets G.');
resourceSpinner = uispinner(resourceGrid,'Limits',[1 8], ...
    'RoundFractionalValues','on','Step',1,'Value',2, ...
    'Tooltip','R: ideal modeled multiplier lanes, not synthesized DSP slices.');

demandPanel = uipanel(gridLayout,'Title','Lever 2: offered interval');
demandPanel.Layout.Row = 3;
demandPanel.Layout.Column = 2;
demandGrid = uigridlayout(demandPanel,[2 1]);
demandGrid.RowHeight = {50,'1x'};
uilabel(demandGrid,'WordWrap','on', ...
    'Text',['Changes source demand without changing raw lane work ' ...
    'capacity, the non-preemptive frame policy, or products.']);
demandSpinner = uispinner(demandGrid,'Limits',[1 8], ...
    'RoundFractionalValues','on','Step',1,'Value',4, ...
    'Tooltip','A: clock cycles between offered eight-product frames.');

framePanel = uipanel(gridLayout,'Title','Inspect one frame');
framePanel.Layout.Row = 3;
framePanel.Layout.Column = 3;
frameGrid = uigridlayout(framePanel,[2 1]);
frameGrid.RowHeight = {50,'1x'};
uilabel(frameGrid,'WordWrap','on', ...
    'Text','Selects one product vector without changing any schedule.');
frameSpinner = uispinner(frameGrid,'Limits',[1 6], ...
    'RoundFractionalValues','on','Step',1,'Value',3, ...
    'Tooltip','Deterministic frame identity from one through six.');

faultPanel = uipanel(gridLayout,'Title','Deliberately broken case');
faultPanel.Layout.Row = 3;
faultPanel.Layout.Column = 4;
faultGrid = uigridlayout(faultPanel,[2 1]);
faultGrid.RowHeight = {54,'1x'};
uilabel(faultGrid,'WordWrap','on', ...
    'Text','Available only when eight products do not divide by R.');
faultCheckbox = uicheckbox(faultGrid, ...
    'Text','Use floor groups; drop tail','Value',false, ...
    'Tooltip','Violates R*G >= 8 by omitting a partial final issue group.');

summary = uilabel(gridLayout,'WordWrap','on');
summary.Layout.Row = 4;
summary.Layout.Column = [1 4];

resourceSpinner.ValueChangedFcn = @(~,~) updatePlots();
demandSpinner.ValueChangedFcn = @(~,~) updatePlots();
frameSpinner.ValueChangedFcn = @(~,~) updatePlots();
faultCheckbox.ValueChangedFcn = @(~,~) updatePlots();
updatePlots();

    function updatePlots
        resourceUnits = round(resourceSpinner.Value);
        offeredFrameInterval = round(demandSpinner.Value);
        selectedFrame = round(frameSpinner.Value);
        if mod(8,resourceUnits) == 0
            faultCheckbox.Value = false;
            faultCheckbox.Enable = 'off';
        else
            faultCheckbox.Enable = 'on';
        end
        brokenFloorSchedule = faultCheckbox.Value;
        out = modelFcn(resourceUnits,offeredFrameInterval,selectedFrame, ...
            brokenFloorSchedule);

        cla(scheduleAxes);
        frameColor = repmat(1:out.frameCount,out.operationCount,1);
        validIssue = out.actualProductValidByFrame;
        scatter(scheduleAxes,out.actualIssueCycle(validIssue), ...
            out.actualLaneIndex(validIssue),50,frameColor(validIssue),'filled', ...
            'DisplayName','Issued product');
        hold(scheduleAxes,'on');
        selectedValid = out.selectedProductValid;
        scatter(scheduleAxes,out.selectedActualIssueCycle(selectedValid), ...
            out.selectedActualLaneIndex(selectedValid),105,'o', ...
            'LineWidth',1.5,'MarkerEdgeColor',[0.85 0.10 0.10], ...
            'DisplayName','Selected frame issue');
        hold(scheduleAxes,'off');
        grid(scheduleAxes,'on');
        xlabel(scheduleAxes,'Product issue edge [cycles]');
        ylabel(scheduleAxes,'Lane [modeled multiplier index]');
        title(scheduleAxes,'Bounded frame schedule across multiplier lanes');
        scheduleAxes.XLim = [1 out.totalCycles];
        scheduleAxes.YLim = [0.5 out.resourceUnits+0.5];
        scheduleAxes.YTick = 1:out.resourceUnits;
        legend(scheduleAxes,'Location','best');

        cla(productAxes);
        stem(productAxes,out.operationIndex,out.selectedReferenceProductCode, ...
            'o','LineWidth',1.2,'DisplayName','Required product code');
        hold(productAxes,'on');
        if out.brokenFloorSchedule
            actualPlot = out.selectedActualProductCode;
            actualPlot(~out.selectedProductValid) = NaN;
            stem(productAxes,out.operationIndex,actualPlot,'--s', ...
                'LineWidth',1.2,'DisplayName','Broken valid product code');
            scatter(productAxes,out.selectedDroppedOperationIndices, ...
                zeros(size(out.selectedDroppedOperationIndices)),85,'x', ...
                'LineWidth',1.6,'MarkerEdgeColor',[0.85 0.10 0.10], ...
                'DisplayName','Missing operation');
        end
        hold(productAxes,'off');
        grid(productAxes,'on');
        xlabel(productAxes,'Product position [operation index]');
        ylabel(productAxes,'Product [signed product code]');
        title(productAxes,'Selected output vector and coverage validity');
        productAxes.XLim = [0.5 out.operationCount+0.5];
        productAxes.XTick = 1:out.operationCount;
        legend(productAxes,'Location','best');

        health = 'healthy: ceiling covers all eight products';
        if out.brokenFloorSchedule
            health = 'BROKEN: floor omits the partial final group';
        end
        summary.Text = sprintf([ ...
            'Frame %d: arrival/start correct/scheduled=%d/%d/%d, ' ...
            'checksum code correct/actual=%d/%d, valid products=%d/%d, ' ...
            'dropped=%s. R=%d lanes, A=%d cycles/frame, issue cycles ' ...
            'correct/scheduled=%d/%d, scheduled interval correct/claimed=' ...
            '%d/%d cycles/frame, max wait correct/claimed=%d/%d cycles, ' ...
            'raw lane work=%d products/cycle (%g frame-equivalents/cycle); ' ...
            'non-preemptive frame capacity=%g frames/cycle; ' ...
            'scheduled rate correct/claimed=%g/%g frames/cycle ' ...
            '(%g/%g Mframes/s at assumed %g MHz), ' ...
            'packing correct/claimed=%g/%g percent, idle slots ' ...
            'correct/claimed=%d/%d per frame, ' ...
            'lane pipeline storage=%d product + %d valid modeled bits. %s. %s'], ...
            out.selectedFrame,out.selectedArrivalCycle, ...
            out.selectedReferenceStartCycle,out.selectedScheduledStartCycle, ...
            out.selectedReferenceChecksumCode,out.selectedActualChecksumCode, ...
            sum(out.selectedProductValid),out.operationCount, ...
            mat2str(out.selectedDroppedOperationIndices.'), ...
            out.resourceUnits,out.offeredFrameInterval, ...
            out.capacityInitiationIntervalCycles, ...
            out.scheduledIssueCyclesPerFrame, ...
            out.referenceScheduledIntervalCycles, ...
            out.scheduledOutputIntervalCycles, ...
            out.maximumReferenceWaitCycles,out.maximumScheduledWaitCycles, ...
            out.resourceUnits,out.resourceUnits/out.operationCount, ...
            out.capacityFramesPerCycle, ...
            out.referenceScheduledFramesPerCycle,out.scheduledFramesPerCycle, ...
            out.referenceScheduledMframesPerSecond, ...
            out.scheduledMframesPerSecond,out.assumedClockFrequencyMHz, ...
            100*out.packingUtilization, ...
            100*out.scheduledPackingUtilization, ...
            out.idleLaneSlotsPerFrame, ...
            out.scheduledSlotCountPerFrame- ...
                out.scheduledOperationCountPerFrame, ...
            out.modeledProductPipelineStorageBits, ...
            out.modeledValidPipelineStorageBits,health,out.equationText);
        drawnow;
    end
end
