function out = model(resourceUnits,offeredFrameInterval,selectedFrame,brokenFloorSchedule)
%MODEL Schedule deterministic product frames across shared multiplier lanes.
%   Each of six frames contains eight independent P06-style fixed-point
%   products. A healthy non-preemptive scheduler reserves
%   ceil(operations/resourceUnits) issue cycles per frame. The broken mode
%   reserves floor(operations/resourceUnits) cycles and therefore drops
%   tail operations whenever the division is not exact.

if nargin < 1
    resourceUnits = 2;
end
if nargin < 2
    offeredFrameInterval = 4;
end
if nargin < 3
    selectedFrame = 3;
end
if nargin < 4
    brokenFloorSchedule = false;
end

validateIntegerScalar(resourceUnits,1,8, ...
    'P07:InvalidResourceUnits','resourceUnits');
validateIntegerScalar(offeredFrameInterval,1,8, ...
    'P07:InvalidOfferedFrameInterval','offeredFrameInterval');
validateIntegerScalar(selectedFrame,1,6, ...
    'P07:InvalidSelectedFrame','selectedFrame');
validateBooleanScalar(brokenFloorSchedule);
resourceUnits = double(resourceUnits);
offeredFrameInterval = double(offeredFrameInterval);
selectedFrame = double(selectedFrame);
brokenFloorSchedule = logical(brokenFloorSchedule);

operationCount = 8;
frameCount = 6;
pipelineLatencyCycles = 2;
laneInitiationIntervalCycles = 1;
operandFractionBits = 2;
productFractionBits = 2*operandFractionBits;
productCodeWordLength = 8;
productLsb = 2.^(-productFractionBits);
assumedClockFrequencyMHz = 100;

baseInputCodeSequence = [3 -2 5 1 -4 6 -1 4].';
coefficientCodeSequence = [2 4 -1 3 2 -2 5 5].';
operationIndex = (1:operationCount).';
frameIndex = (1:frameCount).';
sourceIndexByFrame = zeros(operationCount,frameCount);
inputCodeByFrame = zeros(operationCount,frameCount);
coefficientCodeByFrame = repmat(coefficientCodeSequence,1,frameCount);
for frameNumber = 1:frameCount
    sourceIndexByFrame(:,frameNumber) = ...
        mod(operationIndex-frameNumber,operationCount)+1;
    inputCodeByFrame(:,frameNumber) = ...
        baseInputCodeSequence(sourceIndexByFrame(:,frameNumber));
end
productCodeByFrame = inputCodeByFrame.*coefficientCodeByFrame;
productValueByFrame = productCodeByFrame*productLsb;
referenceDiagnosticChecksumCode = sum(productCodeByFrame,1).';
referenceDiagnosticChecksum = referenceDiagnosticChecksumCode*productLsb;

capacityInitiationIntervalCycles = ceil(operationCount/resourceUnits);
floorIssueCyclesPerFrame = floor(operationCount/resourceUnits);
if brokenFloorSchedule
    scheduledIssueCyclesPerFrame = floorIssueCyclesPerFrame;
    schedulerPolicy = ['broken: floor division allocates too few issue ' ...
        'slots when eight products do not divide evenly'];
else
    scheduledIssueCyclesPerFrame = capacityInitiationIntervalCycles;
    schedulerPolicy = ['healthy: ceiling division covers every product ' ...
        'before the next frame uses the lanes'];
end

arrivalCycle = (1+(0:frameCount-1)*offeredFrameInterval).';
referenceStartCycle = zeros(frameCount,1);
scheduledStartCycle = zeros(frameCount,1);
for frameNumber = 1:frameCount
    if frameNumber == 1
        referenceStartCycle(frameNumber) = arrivalCycle(frameNumber);
        scheduledStartCycle(frameNumber) = arrivalCycle(frameNumber);
    else
        referenceStartCycle(frameNumber) = max(arrivalCycle(frameNumber), ...
            referenceStartCycle(frameNumber-1)+ ...
            capacityInitiationIntervalCycles);
        scheduledStartCycle(frameNumber) = max(arrivalCycle(frameNumber), ...
            scheduledStartCycle(frameNumber-1)+ ...
            scheduledIssueCyclesPerFrame);
    end
end

referenceIssueCycle = zeros(operationCount,frameCount);
referenceResultCycle = zeros(operationCount,frameCount);
referenceLaneIndex = repmat(mod(operationIndex-1,resourceUnits)+1, ...
    1,frameCount);
referenceGroupIndex = floor((operationIndex-1)/resourceUnits);
for frameNumber = 1:frameCount
    referenceIssueCycle(:,frameNumber) = ...
        referenceStartCycle(frameNumber)+referenceGroupIndex;
    referenceResultCycle(:,frameNumber) = ...
        referenceIssueCycle(:,frameNumber)+pipelineLatencyCycles;
end
referenceCompletionCycle = referenceStartCycle+ ...
    capacityInitiationIntervalCycles-1+pipelineLatencyCycles;

scheduledSlotCountPerFrame = ...
    resourceUnits*scheduledIssueCyclesPerFrame;
scheduledOperationCountPerFrame = ...
    min(operationCount,scheduledSlotCountPerFrame);
actualProductValidByFrame = repmat( ...
    operationIndex <= scheduledOperationCountPerFrame,1,frameCount);
actualIssueCycle = zeros(operationCount,frameCount);
actualResultCycle = zeros(operationCount,frameCount);
actualLaneIndex = zeros(operationCount,frameCount);
for frameNumber = 1:frameCount
    validOperations = operationIndex(actualProductValidByFrame(:,frameNumber));
    actualIssueCycle(validOperations,frameNumber) = ...
        scheduledStartCycle(frameNumber)+ ...
        floor((validOperations-1)/resourceUnits);
    actualResultCycle(validOperations,frameNumber) = ...
        actualIssueCycle(validOperations,frameNumber)+pipelineLatencyCycles;
    actualLaneIndex(validOperations,frameNumber) = ...
        mod(validOperations-1,resourceUnits)+1;
end
actualProductCodeByFrame = zeros(operationCount,frameCount);
actualProductCodeByFrame(actualProductValidByFrame) = ...
    productCodeByFrame(actualProductValidByFrame);
actualProductValueByFrame = actualProductCodeByFrame*productLsb;
frameCompleteMask = all(actualProductValidByFrame,1).';
actualDiagnosticChecksumCode = sum(actualProductCodeByFrame,1).';
actualDiagnosticChecksum = actualDiagnosticChecksumCode*productLsb;
diagnosticChecksumErrorCode = actualDiagnosticChecksumCode- ...
    referenceDiagnosticChecksumCode;
diagnosticChecksumError = diagnosticChecksumErrorCode*productLsb;
droppedOperationMask = ~actualProductValidByFrame;
droppedOperationCountPerFrame = sum(droppedOperationMask,1).';
claimedCompletionCycle = scheduledStartCycle+ ...
    scheduledIssueCyclesPerFrame-1+pipelineLatencyCycles;

referenceScheduledIntervalCycles = max(offeredFrameInterval, ...
    capacityInitiationIntervalCycles);
scheduledOutputIntervalCycles = max(offeredFrameInterval, ...
    scheduledIssueCyclesPerFrame);
offeredRateFramesPerCycle = 1/offeredFrameInterval;
capacityFramesPerCycle = 1/capacityInitiationIntervalCycles;
referenceScheduledFramesPerCycle = 1/referenceScheduledIntervalCycles;
scheduledFramesPerCycle = 1/scheduledOutputIntervalCycles;
capacityMframesPerSecond = assumedClockFrequencyMHz*capacityFramesPerCycle;
referenceScheduledMframesPerSecond = ...
    assumedClockFrequencyMHz*referenceScheduledFramesPerCycle;
scheduledMframesPerSecond = ...
    assumedClockFrequencyMHz*scheduledFramesPerCycle;
falseThroughputClaimMframesPerSecond = max(0, ...
    scheduledMframesPerSecond-referenceScheduledMframesPerSecond);

packingUtilization = operationCount/(resourceUnits* ...
    capacityInitiationIntervalCycles);
idleLaneSlotsPerFrame = resourceUnits* ...
    capacityInitiationIntervalCycles-operationCount;
scheduledPackingUtilization = scheduledOperationCountPerFrame/ ...
    scheduledSlotCountPerFrame;
requiredResourceUnitsForOfferedInterval = ...
    ceil(operationCount/offeredFrameInterval);
referenceWaitCycles = referenceStartCycle-arrivalCycle;
scheduledWaitCycles = scheduledStartCycle-arrivalCycle;
referenceLatencyCycles = referenceCompletionCycle-arrivalCycle;
claimedLatencyCycles = claimedCompletionCycle-arrivalCycle;
sustainedOverload = offeredFrameInterval < ...
    capacityInitiationIntervalCycles;

totalCycles = max([referenceCompletionCycle; claimedCompletionCycle]);
maxTimelineCycles = 50;
maxLaneTimelineSlots = maxTimelineCycles*8;
issueFrameByLane = zeros(totalCycles,resourceUnits);
issueOperationByLane = zeros(totalCycles,resourceUnits);
issueProductCodeByLane = zeros(totalCycles,resourceUnits);
resultFrameByLane = zeros(totalCycles,resourceUnits);
resultOperationByLane = zeros(totalCycles,resourceUnits);
referenceIssueFrameByLane = zeros(totalCycles,resourceUnits);
issueCollisionCount = 0;
resultCollisionCount = 0;
referenceIssueCollisionCount = 0;
for frameNumber = 1:frameCount
    for operationNumber = 1:operationCount
        referenceIssue = referenceIssueCycle(operationNumber,frameNumber);
        referenceLane = referenceLaneIndex(operationNumber,frameNumber);
        if referenceIssueFrameByLane(referenceIssue,referenceLane) ~= 0
            referenceIssueCollisionCount = referenceIssueCollisionCount+1;
        end
        referenceIssueFrameByLane(referenceIssue,referenceLane) = frameNumber;
        if actualProductValidByFrame(operationNumber,frameNumber)
            issueCycle = actualIssueCycle(operationNumber,frameNumber);
            resultCycle = actualResultCycle(operationNumber,frameNumber);
            laneIndex = actualLaneIndex(operationNumber,frameNumber);
            if issueFrameByLane(issueCycle,laneIndex) ~= 0
                issueCollisionCount = issueCollisionCount+1;
            end
            if resultFrameByLane(resultCycle,laneIndex) ~= 0
                resultCollisionCount = resultCollisionCount+1;
            end
            issueFrameByLane(issueCycle,laneIndex) = frameNumber;
            issueOperationByLane(issueCycle,laneIndex) = operationNumber;
            issueProductCodeByLane(issueCycle,laneIndex) = ...
                productCodeByFrame(operationNumber,frameNumber);
            resultFrameByLane(resultCycle,laneIndex) = frameNumber;
            resultOperationByLane(resultCycle,laneIndex) = operationNumber;
        end
    end
end

queuedFrameCount = zeros(totalCycles,1);
referenceQueuedFrameCount = zeros(totalCycles,1);
for cycleNumber = 1:totalCycles
    queuedFrameCount(cycleNumber) = sum(arrivalCycle <= cycleNumber & ...
        scheduledStartCycle > cycleNumber);
    referenceQueuedFrameCount(cycleNumber) = ...
        sum(arrivalCycle <= cycleNumber & ...
        referenceStartCycle > cycleNumber);
end

selectedActualProductCode = actualProductCodeByFrame(:,selectedFrame);
selectedActualProductValue = actualProductValueByFrame(:,selectedFrame);
selectedProductValid = actualProductValidByFrame(:,selectedFrame);
selectedDroppedOperationIndices = operationIndex(~selectedProductValid);

out = struct( ...
    'resourceUnits',resourceUnits, ...
    'offeredFrameInterval',offeredFrameInterval, ...
    'selectedFrame',selectedFrame, ...
    'brokenFloorSchedule',brokenFloorSchedule, ...
    'operationCount',operationCount, ...
    'frameCount',frameCount, ...
    'operationIndex',operationIndex, ...
    'frameIndex',frameIndex, ...
    'pipelineLatencyCycles',pipelineLatencyCycles, ...
    'laneInitiationIntervalCycles',laneInitiationIntervalCycles, ...
    'operandFractionBits',operandFractionBits, ...
    'productFractionBits',productFractionBits, ...
    'productCodeWordLength',productCodeWordLength, ...
    'productLsb',productLsb, ...
    'assumedClockFrequencyMHz',assumedClockFrequencyMHz, ...
    'baseInputCodeSequence',baseInputCodeSequence, ...
    'coefficientCodeSequence',coefficientCodeSequence, ...
    'sourceIndexByFrame',sourceIndexByFrame, ...
    'inputCodeByFrame',inputCodeByFrame, ...
    'coefficientCodeByFrame',coefficientCodeByFrame, ...
    'productCodeByFrame',productCodeByFrame, ...
    'productValueByFrame',productValueByFrame, ...
    'referenceDiagnosticChecksumCode',referenceDiagnosticChecksumCode, ...
    'referenceDiagnosticChecksum',referenceDiagnosticChecksum, ...
    'capacityInitiationIntervalCycles', ...
        capacityInitiationIntervalCycles, ...
    'floorIssueCyclesPerFrame',floorIssueCyclesPerFrame, ...
    'scheduledIssueCyclesPerFrame',scheduledIssueCyclesPerFrame, ...
    'schedulerPolicy',schedulerPolicy, ...
    'arrivalCycle',arrivalCycle, ...
    'referenceStartCycle',referenceStartCycle, ...
    'scheduledStartCycle',scheduledStartCycle, ...
    'referenceIssueCycle',referenceIssueCycle, ...
    'referenceResultCycle',referenceResultCycle, ...
    'referenceLaneIndex',referenceLaneIndex, ...
    'referenceCompletionCycle',referenceCompletionCycle, ...
    'scheduledSlotCountPerFrame',scheduledSlotCountPerFrame, ...
    'scheduledOperationCountPerFrame',scheduledOperationCountPerFrame, ...
    'actualProductValidByFrame',actualProductValidByFrame, ...
    'actualIssueCycle',actualIssueCycle, ...
    'actualResultCycle',actualResultCycle, ...
    'actualLaneIndex',actualLaneIndex, ...
    'actualProductCodeByFrame',actualProductCodeByFrame, ...
    'actualProductValueByFrame',actualProductValueByFrame, ...
    'frameCompleteMask',frameCompleteMask, ...
    'completeFrameCount',sum(frameCompleteMask), ...
    'actualDiagnosticChecksumCode',actualDiagnosticChecksumCode, ...
    'actualDiagnosticChecksum',actualDiagnosticChecksum, ...
    'diagnosticChecksumErrorCode',diagnosticChecksumErrorCode, ...
    'diagnosticChecksumError',diagnosticChecksumError, ...
    'droppedOperationMask',droppedOperationMask, ...
    'droppedOperationCountPerFrame',droppedOperationCountPerFrame, ...
    'totalDroppedOperationCount',sum(droppedOperationCountPerFrame), ...
    'claimedCompletionCycle',claimedCompletionCycle, ...
    'referenceScheduledIntervalCycles', ...
        referenceScheduledIntervalCycles, ...
    'scheduledOutputIntervalCycles',scheduledOutputIntervalCycles, ...
    'offeredRateFramesPerCycle',offeredRateFramesPerCycle, ...
    'capacityFramesPerCycle',capacityFramesPerCycle, ...
    'referenceScheduledFramesPerCycle',referenceScheduledFramesPerCycle, ...
    'scheduledFramesPerCycle',scheduledFramesPerCycle, ...
    'capacityMframesPerSecond',capacityMframesPerSecond, ...
    'referenceScheduledMframesPerSecond', ...
        referenceScheduledMframesPerSecond, ...
    'scheduledMframesPerSecond',scheduledMframesPerSecond, ...
    'falseThroughputClaimMframesPerSecond', ...
        falseThroughputClaimMframesPerSecond, ...
    'packingUtilization',packingUtilization, ...
    'idleLaneSlotsPerFrame',idleLaneSlotsPerFrame, ...
    'scheduledPackingUtilization',scheduledPackingUtilization, ...
    'requiredResourceUnitsForOfferedInterval', ...
        requiredResourceUnitsForOfferedInterval, ...
    'referenceWaitCycles',referenceWaitCycles, ...
    'scheduledWaitCycles',scheduledWaitCycles, ...
    'referenceLatencyCycles',referenceLatencyCycles, ...
    'claimedLatencyCycles',claimedLatencyCycles, ...
    'maximumReferenceWaitCycles',max(referenceWaitCycles), ...
    'maximumScheduledWaitCycles',max(scheduledWaitCycles), ...
    'sustainedOverload',sustainedOverload, ...
    'totalCycles',totalCycles, ...
    'maxTimelineCycles',maxTimelineCycles, ...
    'maxLaneTimelineSlots',maxLaneTimelineSlots, ...
    'issueFrameByLane',issueFrameByLane, ...
    'issueOperationByLane',issueOperationByLane, ...
    'issueProductCodeByLane',issueProductCodeByLane, ...
    'resultFrameByLane',resultFrameByLane, ...
    'resultOperationByLane',resultOperationByLane, ...
    'referenceIssueFrameByLane',referenceIssueFrameByLane, ...
    'issueCollisionCount',issueCollisionCount, ...
    'resultCollisionCount',resultCollisionCount, ...
    'referenceIssueCollisionCount',referenceIssueCollisionCount, ...
    'queuedFrameCount',queuedFrameCount, ...
    'referenceQueuedFrameCount',referenceQueuedFrameCount, ...
    'maximumQueueDepth',max(queuedFrameCount), ...
    'maximumReferenceQueueDepth',max(referenceQueuedFrameCount), ...
    'modeledProductPipelineStorageBits', ...
        resourceUnits*pipelineLatencyCycles*productCodeWordLength, ...
    'modeledValidPipelineStorageBits', ...
        resourceUnits*pipelineLatencyCycles, ...
    'selectedArrivalCycle',arrivalCycle(selectedFrame), ...
    'selectedReferenceStartCycle',referenceStartCycle(selectedFrame), ...
    'selectedScheduledStartCycle',scheduledStartCycle(selectedFrame), ...
    'selectedReferenceIssueCycle',referenceIssueCycle(:,selectedFrame), ...
    'selectedActualIssueCycle',actualIssueCycle(:,selectedFrame), ...
    'selectedReferenceResultCycle',referenceResultCycle(:,selectedFrame), ...
    'selectedActualResultCycle',actualResultCycle(:,selectedFrame), ...
    'selectedReferenceLaneIndex',referenceLaneIndex(:,selectedFrame), ...
    'selectedActualLaneIndex',actualLaneIndex(:,selectedFrame), ...
    'selectedReferenceProductCode',productCodeByFrame(:,selectedFrame), ...
    'selectedReferenceProductValue',productValueByFrame(:,selectedFrame), ...
    'selectedActualProductCode',selectedActualProductCode, ...
    'selectedActualProductValue',selectedActualProductValue, ...
    'selectedProductValid',selectedProductValid, ...
    'selectedDroppedOperationIndices',selectedDroppedOperationIndices, ...
    'selectedFrameComplete',frameCompleteMask(selectedFrame), ...
    'selectedReferenceChecksumCode', ...
        referenceDiagnosticChecksumCode(selectedFrame), ...
    'selectedActualChecksumCode', ...
        actualDiagnosticChecksumCode(selectedFrame), ...
    'equationText',['G = ceil(8/R) issue cycles/frame; arrival[j] = ' ...
        '1+(j-1)A; start[j] = max(arrival[j], start[j-1]+G); ' ...
        'issue[j,k] = start[j]+floor((k-1)/R); lane[j,k] = ' ...
        '1+mod(k-1,R); ready[j,k] = issue[j,k]+2.']);
end

function validateIntegerScalar(value,lowerBound,upperBound,errorId,name)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && ~isnan(value) && ~isinf(value) && ...
        value == fix(value) && value >= lowerBound && value <= upperBound)
    error(errorId,'%s must be a finite integer in [%d, %d].', ...
        name,lowerBound,upperBound);
end
end

function validateBooleanScalar(value)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ~isnan(value) && ~isinf(value) && (value == 0 || value == 1);
if ~(validLogical || validNumeric)
    error('P07:InvalidBrokenFloorSchedule', ...
        'brokenFloorSchedule must be logical or numeric 0 or 1.');
end
end
