function run_checks
%RUN_CHECKS Execute independent P07 scheduling, limit, and boundary checks.
clear model;

%% Baseline data, product meaning, exact schedule, and typed compatibility
baseline = model(2,4,3,false);
expectedBaseInputs = [3 -2 5 1 -4 6 -1 4].';
expectedCoefficients = [2 4 -1 3 2 -2 5 5].';
expectedFrameOneProducts = [6 -8 -5 3 -8 -12 -5 20].';
expectedChecksums = [-9 72 23 -16 69 -6].';
expectedArrivals = [1 5 9 13 17 21].';
expectedCompletions = [6 10 14 18 22 26].';
expectedFirstFrameIssues = [1 1 2 2 3 3 4 4].';
expectedFirstFrameLanes = [1 2 1 2 1 2 1 2].';
assert(isequal(baseline.baseInputCodeSequence,expectedBaseInputs) && ...
    isequal(baseline.coefficientCodeSequence,expectedCoefficients) && ...
    isequal(baseline.productCodeByFrame(:,1), ...
        expectedFrameOneProducts), ...
    'P07:BaselineProducts', ...
    'The P06-derived operand or product-code contract changed.');
assert(baseline.operandFractionBits == 2 && ...
    baseline.productFractionBits == 4 && ...
    baseline.productCodeWordLength == 8 && ...
    baseline.productLsb == 1/16 && ...
    isequal(baseline.productValueByFrame, ...
        baseline.productCodeByFrame/16), ...
    'P07:BinaryPoint', ...
    'The product path must preserve P06 code scaling.');
assert(isequal(baseline.referenceDiagnosticChecksumCode, ...
        expectedChecksums) && ...
    isequal(baseline.actualDiagnosticChecksumCode,expectedChecksums) && ...
    all(baseline.diagnosticChecksumErrorCode == 0), ...
    'P07:DiagnosticChecksums', ...
    'The deterministic product-vector diagnostics changed.');
assert(baseline.capacityInitiationIntervalCycles == 4 && ...
    baseline.scheduledIssueCyclesPerFrame == 4 && ...
    isequal(baseline.arrivalCycle,expectedArrivals) && ...
    isequal(baseline.referenceStartCycle,expectedArrivals) && ...
    isequal(baseline.scheduledStartCycle,expectedArrivals) && ...
    isequal(baseline.referenceCompletionCycle,expectedCompletions) && ...
    isequal(baseline.claimedCompletionCycle,expectedCompletions), ...
    'P07:BaselineSchedule', ...
    'The two-lane balanced schedule changed.');
assert(isequal(baseline.referenceIssueCycle(:,1), ...
        expectedFirstFrameIssues) && ...
    isequal(baseline.actualIssueCycle(:,1),expectedFirstFrameIssues) && ...
    isequal(baseline.referenceLaneIndex(:,1), ...
        expectedFirstFrameLanes) && ...
    isequal(baseline.actualLaneIndex(:,1),expectedFirstFrameLanes) && ...
    isequal(baseline.actualResultCycle(:,1), ...
        expectedFirstFrameIssues+2), ...
    'P07:IssueAndReadyEdges', ...
    'Lane issue or two-cycle result timing changed.');
assert(all(baseline.actualProductValidByFrame(:)) && ...
    all(baseline.frameCompleteMask) && ...
    baseline.completeFrameCount == 6 && ...
    baseline.totalDroppedOperationCount == 0 && ...
    baseline.issueCollisionCount == 0 && ...
    baseline.resultCollisionCount == 0 && ...
    baseline.referenceIssueCollisionCount == 0, ...
    'P07:BaselineCoverage', ...
    'Every baseline product must issue exactly once without collision.');
assert(baseline.packingUtilization == 1 && ...
    baseline.idleLaneSlotsPerFrame == 0 && ...
    baseline.scheduledFramesPerCycle == 1/4 && ...
    baseline.capacityMframesPerSecond == 25 && ...
    baseline.referenceScheduledMframesPerSecond == 25 && ...
    baseline.scheduledMframesPerSecond == 25 && ...
    baseline.maximumReferenceWaitCycles == 0 && ...
    baseline.maximumReferenceQueueDepth == 0, ...
    'P07:BaselineMetrics', ...
    'Balanced baseline resource or throughput metrics changed.');
assert(baseline.selectedFrame == 3 && ...
    baseline.selectedArrivalCycle == 9 && ...
    baseline.selectedReferenceStartCycle == 9 && ...
    baseline.selectedFrameComplete && ...
    baseline.selectedReferenceChecksumCode == 23 && ...
    baseline.selectedActualChecksumCode == 23 && ...
    isempty(baseline.selectedDroppedOperationIndices), ...
    'P07:SelectedBaseline', ...
    'The selected baseline frame observation changed.');
typedBaseline = model(uint8(2),int8(4),single(3),uint8(0));
assert(isequaln(typedBaseline,baseline), ...
    'P07:NumericClassNormalization', ...
    'Accepted numeric scalar classes must equal the double-input baseline.');

%% Sweep 1 - resource replication at a fixed one-cycle source interval
resourceCounts = 1:8;
expectedCapacityIntervals = [8 4 3 2 2 2 2 1];
expectedFirstFrameLatencies = [9 5 4 3 3 3 3 2];
expectedMaximumWaits = [35 15 10 5 5 5 5 0];
expectedIdleSlots = [0 0 1 0 2 4 6 0];
expectedUtilization = [1 1 8/9 1 4/5 2/3 4/7 1];
observedCapacityIntervals = zeros(size(resourceCounts));
observedFirstFrameLatencies = zeros(size(resourceCounts));
observedMaximumWaits = zeros(size(resourceCounts));
observedIdleSlots = zeros(size(resourceCounts));
observedUtilization = zeros(size(resourceCounts));
for sweepIndex = 1:numel(resourceCounts)
    current = model(resourceCounts(sweepIndex),1,3,false);
    assert(current.offeredFrameInterval == 1 && ...
        isequal(current.arrivalCycle,(1:6).') && ...
        isequal(current.productCodeByFrame, ...
            baseline.productCodeByFrame), ...
        'P07:ResourceSweepIsolation', ...
        'Resource sweep must preserve arrivals and product vectors.');
    assert(current.completeFrameCount == 6 && ...
        current.totalDroppedOperationCount == 0 && ...
        current.scheduledOutputIntervalCycles == ...
            current.capacityInitiationIntervalCycles && ...
        current.scheduledFramesPerCycle == ...
            1/current.capacityInitiationIntervalCycles, ...
        'P07:ResourceSweep', ...
        'Healthy resource changes must preserve all outputs.');
    observedCapacityIntervals(sweepIndex) = ...
        current.capacityInitiationIntervalCycles;
    observedFirstFrameLatencies(sweepIndex) = ...
        current.referenceLatencyCycles(1);
    observedMaximumWaits(sweepIndex) = ...
        current.maximumReferenceWaitCycles;
    observedIdleSlots(sweepIndex) = current.idleLaneSlotsPerFrame;
    observedUtilization(sweepIndex) = current.packingUtilization;
end
assert(isequal(observedCapacityIntervals,expectedCapacityIntervals) && ...
    isequal(observedFirstFrameLatencies, ...
        expectedFirstFrameLatencies) && ...
    isequal(observedMaximumWaits,expectedMaximumWaits) && ...
    isequal(observedIdleSlots,expectedIdleSlots) && ...
    max(abs(observedUtilization-expectedUtilization)) < 1e-12, ...
    'P07:ResourceSweepLimits', ...
    'Resource-count sweep limits or packing plateaus changed.');

%% Non-preemptive partial-group policy and raw-work distinction
threeLanePolicy = model(3,1,1,false);
expectedThreeLaneStarts = [1 4 7 10 13 16].';
rawLaneFrameEquivalentRate = ...
    threeLanePolicy.resourceUnits/threeLanePolicy.operationCount;
assert(isequal(threeLanePolicy.referenceStartCycle, ...
        expectedThreeLaneStarts) && ...
    isequal(threeLanePolicy.referenceIssueCycle(:,1), ...
        [1 1 1 2 2 2 3 3].') && ...
    threeLanePolicy.referenceIssueFrameByLane(3,3) == 0 && ...
    threeLanePolicy.referenceIssueFrameByLane(4,1) == 2 && ...
    abs(rawLaneFrameEquivalentRate-3/8) < 1e-12 && ...
    abs(threeLanePolicy.capacityFramesPerCycle-1/3) < 1e-12 && ...
    abs(threeLanePolicy.capacityFramesPerCycle- ...
        threeLanePolicy.packingUtilization* ...
        rawLaneFrameEquivalentRate) < 1e-12, ...
    'P07:NonPreemptivePartialGroup', ...
    ['The three-lane policy must leave the last group''s third lane idle ' ...
    'instead of cross-packing the next frame.']);

%% Sweep 2 - source demand at a fixed two-lane datapath
offeredIntervals = 1:8;
expectedScheduledIntervals = [4 4 4 4 5 6 7 8];
expectedDemandWaits = [15 10 5 0 0 0 0 0];
expectedQueueDepths = [4 3 2 0 0 0 0 0];
expectedRequiredResources = [8 4 3 2 2 2 2 1];
expectedOverload = [true true true false false false false false];
observedScheduledIntervals = zeros(size(offeredIntervals));
observedDemandWaits = zeros(size(offeredIntervals));
observedQueueDepths = zeros(size(offeredIntervals));
observedRequiredResources = zeros(size(offeredIntervals));
observedOverload = false(size(offeredIntervals));
for sweepIndex = 1:numel(offeredIntervals)
    current = model(2,offeredIntervals(sweepIndex),3,false);
    assert(current.resourceUnits == 2 && ...
        current.capacityInitiationIntervalCycles == 4 && ...
        current.modeledProductPipelineStorageBits == 32 && ...
        isequal(current.productCodeByFrame, ...
            baseline.productCodeByFrame), ...
        'P07:DemandSweepIsolation', ...
        'Demand sweep must preserve resources and product vectors.');
    assert(current.completeFrameCount == 6 && ...
        current.totalDroppedOperationCount == 0 && ...
        current.referenceScheduledIntervalCycles == ...
            max(current.offeredFrameInterval,4), ...
        'P07:DemandSweep', ...
        'Healthy demand changes must remain lossless and capacity bounded.');
    observedScheduledIntervals(sweepIndex) = ...
        current.referenceScheduledIntervalCycles;
    observedDemandWaits(sweepIndex) = current.maximumReferenceWaitCycles;
    observedQueueDepths(sweepIndex) = current.maximumReferenceQueueDepth;
    expectedQueueTrace = zeros(current.totalCycles,1);
    runningQueueDepth = 0;
    for cycleNumber = 1:current.totalCycles
        runningQueueDepth = runningQueueDepth+ ...
            sum(current.arrivalCycle == cycleNumber)- ...
            sum(current.referenceStartCycle == cycleNumber);
        expectedQueueTrace(cycleNumber) = runningQueueDepth;
    end
    assert(isequal(current.referenceQueuedFrameCount, ...
            expectedQueueTrace), ...
        'P07:DemandQueueRecurrence', ...
        'Queue depth must equal cumulative arrivals minus frame starts.');
    observedRequiredResources(sweepIndex) = ...
        current.requiredResourceUnitsForOfferedInterval;
    observedOverload(sweepIndex) = current.sustainedOverload;
end
assert(isequal(observedScheduledIntervals, ...
        expectedScheduledIntervals) && ...
    isequal(observedDemandWaits,expectedDemandWaits) && ...
    isequal(observedQueueDepths,expectedQueueDepths) && ...
    isequal(observedRequiredResources,expectedRequiredResources) && ...
    isequal(observedOverload,expectedOverload), ...
    'P07:DemandSweepLimits', ...
    'Source-interval capacity, wait, or resource limits changed.');

%% Complete healthy grid, recurrences, identity, and fixed allocations
for resourceUnits = 1:8
    for offeredFrameInterval = 1:8
        current = model(resourceUnits,offeredFrameInterval,6,false);
        expectedGroups = ceil(8/resourceUnits);
        expectedInterval = max(offeredFrameInterval,expectedGroups);
        assert(current.capacityInitiationIntervalCycles == expectedGroups && ...
            current.scheduledIssueCyclesPerFrame == expectedGroups && ...
            current.referenceScheduledIntervalCycles == expectedInterval && ...
            current.scheduledOutputIntervalCycles == expectedInterval, ...
            'P07:CapacityEquation', ...
            'Healthy capacity must use ceiling division.');
        assert(all(current.actualProductValidByFrame(:)) && ...
            isequal(current.actualProductCodeByFrame, ...
                current.productCodeByFrame) && ...
            isequal(current.actualDiagnosticChecksumCode, ...
                expectedChecksums) && ...
            current.completeFrameCount == 6 && ...
            current.totalDroppedOperationCount == 0, ...
            'P07:HealthyGrid', ...
            'A healthy schedule lost, duplicated, or edited a product.');
        assert(current.issueCollisionCount == 0 && ...
            current.resultCollisionCount == 0 && ...
            current.referenceIssueCollisionCount == 0 && ...
            all(current.actualLaneIndex(:) >= 1) && ...
            all(current.actualLaneIndex(:) <= resourceUnits), ...
            'P07:LaneExclusivity', ...
            'A multiplier lane accepted more than one operation per cycle.');
        for frameNumber = 1:current.frameCount
            expectedStart = current.arrivalCycle(frameNumber);
            if frameNumber > 1
                expectedStart = max(expectedStart, ...
                    current.referenceStartCycle(frameNumber-1)+ ...
                    expectedGroups);
            end
            assert(current.referenceStartCycle(frameNumber) == ...
                    expectedStart && ...
                current.scheduledStartCycle(frameNumber) == expectedStart, ...
                'P07:FrameStartRecurrence', ...
                'Frame start recurrence changed.');
            for operationNumber = 1:current.operationCount
                expectedIssue = expectedStart+ ...
                    floor((operationNumber-1)/resourceUnits);
                expectedLane = 1+mod(operationNumber-1,resourceUnits);
                assert(current.actualIssueCycle(operationNumber,frameNumber) == ...
                        expectedIssue && ...
                    current.actualResultCycle(operationNumber,frameNumber) == ...
                        expectedIssue+2 && ...
                    current.actualLaneIndex(operationNumber,frameNumber) == ...
                        expectedLane, ...
                    'P07:OperationRecurrence', ...
                    'Operation issue, result, or lane identity changed.');
            end
            assert(current.referenceCompletionCycle(frameNumber) == ...
                    max(current.referenceResultCycle(:,frameNumber)) && ...
                current.claimedCompletionCycle(frameNumber) == ...
                    max(current.actualResultCycle(:,frameNumber)), ...
                'P07:CompletionEdge', ...
                'Frame completion must follow the final product result.');
        end
        assert(current.totalCycles <= current.maxTimelineCycles && ...
            current.maxTimelineCycles == 50 && ...
            numel(current.issueFrameByLane) <= ...
                current.maxLaneTimelineSlots && ...
            current.maxLaneTimelineSlots == 400 && ...
            numel(current.productCodeByFrame) == 48 && ...
            current.modeledProductPipelineStorageBits <= 128 && ...
            current.modeledValidPipelineStorageBits <= 16, ...
            'P07:ResourceBound', ...
            'The bounded teaching-model allocation changed.');
    end
end

%% Serialization, full replication, divisor, and supply-limited limits
serial = model(1,8,1,false);
assert(serial.capacityInitiationIntervalCycles == 8 && ...
    isequal(serial.actualIssueCycle(:,1),(1:8).') && ...
    all(serial.actualLaneIndex(:,1) == 1) && ...
    serial.referenceCompletionCycle(1) == 10 && ...
    serial.referenceLatencyCycles(1) == 9 && ...
    serial.packingUtilization == 1, ...
    'P07:SerialLimit', ...
    'One lane must serialize all eight products.');
fullyReplicated = model(8,1,1,false);
assert(fullyReplicated.capacityInitiationIntervalCycles == 1 && ...
    all(fullyReplicated.actualIssueCycle(:,1) == 1) && ...
    isequal(fullyReplicated.actualLaneIndex(:,1),(1:8).') && ...
    fullyReplicated.referenceCompletionCycle(1) == 3 && ...
    fullyReplicated.referenceLatencyCycles(1) == 2 && ...
    fullyReplicated.scheduledFramesPerCycle == 1, ...
    'P07:FullReplicationLimit', ...
    'Eight lanes must issue a complete frame together.');
fourLanes = model(4,8,1,false);
assert(fourLanes.capacityInitiationIntervalCycles == 2 && ...
    fourLanes.referenceScheduledIntervalCycles == 8 && ...
    fourLanes.capacityFramesPerCycle == 1/2 && ...
    fourLanes.referenceScheduledFramesPerCycle == 1/8 && ...
    fourLanes.maximumReferenceWaitCycles == 0, ...
    'P07:SupplyLimited', ...
    'A slow source must limit scheduled throughput without queueing.');

%% Deliberately broken floor schedule and exact tail-loss symptom
healthyThree = model(3,2,3,false);
brokenThree = model(3,2,3,true);
expectedReferenceStarts = [1 4 7 10 13 16].';
expectedBrokenStarts = [1 3 5 7 9 11].';
expectedReferenceCompletions = [5 8 11 14 17 20].';
expectedBrokenClaims = [4 6 8 10 12 14].';
expectedBrokenChecksums = [-24 47 13 -1 39 -21].';
expectedChecksumErrors = [-15 -25 -10 15 -30 -15].';
expectedBrokenValid = repmat([true(6,1); false(2,1)],1,6);
assert(brokenThree.capacityInitiationIntervalCycles == 3 && ...
    brokenThree.floorIssueCyclesPerFrame == 2 && ...
    brokenThree.scheduledIssueCyclesPerFrame == 2 && ...
    brokenThree.scheduledSlotCountPerFrame == 6 && ...
    brokenThree.scheduledOperationCountPerFrame == 6, ...
    'P07:BrokenFloorCapacity', ...
    'The floor scheduler must allocate only six slots at R=3.');
assert(isequal(brokenThree.referenceStartCycle, ...
        expectedReferenceStarts) && ...
    isequal(brokenThree.scheduledStartCycle,expectedBrokenStarts) && ...
    isequal(brokenThree.referenceCompletionCycle, ...
        expectedReferenceCompletions) && ...
    isequal(brokenThree.claimedCompletionCycle,expectedBrokenClaims), ...
    'P07:BrokenFalseSchedule', ...
    'The broken controller must claim the optimistic two-cycle cadence.');
assert(isequal(brokenThree.actualProductValidByFrame, ...
        expectedBrokenValid) && ...
    isequal(brokenThree.droppedOperationMask,~expectedBrokenValid) && ...
    all(brokenThree.droppedOperationCountPerFrame == 2) && ...
    brokenThree.totalDroppedOperationCount == 12 && ...
    brokenThree.completeFrameCount == 0 && ...
    isequal(brokenThree.selectedDroppedOperationIndices,[7; 8]), ...
    'P07:BrokenTailLoss', ...
    'Operations seven and eight must be absent from every broken frame.');
assert(isequal(brokenThree.actualDiagnosticChecksumCode, ...
        expectedBrokenChecksums) && ...
    isequal(brokenThree.diagnosticChecksumErrorCode, ...
        expectedChecksumErrors) && ...
    brokenThree.selectedReferenceChecksumCode == 23 && ...
    brokenThree.selectedActualChecksumCode == 13, ...
    'P07:BrokenProductSymptom', ...
    'Tail loss must produce the exact incomplete product-vector diagnostic.');
assert(abs(brokenThree.referenceScheduledMframesPerSecond-100/3) < ...
        1e-12 && ...
    brokenThree.scheduledMframesPerSecond == 50 && ...
    abs(brokenThree.falseThroughputClaimMframesPerSecond-50/3) < ...
        1e-12 && ...
    brokenThree.scheduledPackingUtilization == 1 && ...
    abs(brokenThree.packingUtilization-8/9) < 1e-12, ...
    'P07:BrokenThroughputClaim', ...
    'The broken path must look full while overstating useful throughput.');
assert(isequal(brokenThree.productCodeByFrame, ...
        healthyThree.productCodeByFrame) && ...
    isequal(brokenThree.referenceIssueCycle, ...
        healthyThree.referenceIssueCycle) && ...
    isequal(brokenThree.referenceCompletionCycle, ...
        healthyThree.referenceCompletionCycle) && ...
    brokenThree.issueCollisionCount == 0 && ...
    brokenThree.resultCollisionCount == 0, ...
    'P07:BrokenIsolation', ...
    'The fault must change schedule coverage, not reference products.');

%% Fault grid, inert divisor cases, bounds, and deterministic recovery
for resourceUnits = 1:8
    for offeredFrameInterval = 1:8
        healthy = model(resourceUnits,offeredFrameInterval,2,false);
        broken = model(resourceUnits,offeredFrameInterval,2,true);
        assert(isequal(broken.productCodeByFrame, ...
                healthy.productCodeByFrame) && ...
            isequal(broken.referenceIssueCycle, ...
                healthy.referenceIssueCycle) && ...
            broken.issueCollisionCount == 0 && ...
            broken.resultCollisionCount == 0 && ...
            broken.totalCycles <= 50 && ...
            numel(broken.issueFrameByLane) <= 400, ...
            'P07:BrokenGridBound', ...
            'Broken schedules must preserve inputs and remain bounded.');
        if mod(8,resourceUnits) == 0
            assert(all(broken.actualProductValidByFrame(:)) && ...
                broken.totalDroppedOperationCount == 0 && ...
                broken.completeFrameCount == 6 && ...
                isequal(broken.actualIssueCycle,healthy.actualIssueCycle) && ...
                isequal(broken.actualProductCodeByFrame, ...
                    healthy.actualProductCodeByFrame), ...
                'P07:BrokenInertDivisor', ...
                'Floor and ceiling must agree for exact divisors.');
        else
            covered = resourceUnits*floor(8/resourceUnits);
            expectedDropped = (covered+1:8).';
            assert(broken.scheduledOperationCountPerFrame == covered && ...
                broken.totalDroppedOperationCount == ...
                    6*(8-covered) && ...
                broken.completeFrameCount == 0 && ...
                isequal(broken.selectedDroppedOperationIndices, ...
                    expectedDropped) && ...
                all(broken.droppedOperationCountPerFrame == 8-covered), ...
                'P07:BrokenNonDivisorGrid', ...
                'Every non-divisor must expose its exact uncovered tail.');
        end
    end
end

%% Malformed inputs, selected-view isolation, and call recovery
assertRejects(@() model(0,4,3,false),'P07:InvalidResourceUnits');
assertRejects(@() model(9,4,3,false),'P07:InvalidResourceUnits');
assertRejects(@() model(2.5,4,3,false),'P07:InvalidResourceUnits');
assertRejects(@() model([2 3],4,3,false),'P07:InvalidResourceUnits');
assertRejects(@() model(NaN,4,3,false),'P07:InvalidResourceUnits');
assertRejects(@() model(Inf,4,3,false),'P07:InvalidResourceUnits');
assertRejects(@() model(1+1i,4,3,false),'P07:InvalidResourceUnits');
assertRejects(@() model(true,4,3,false),'P07:InvalidResourceUnits');
assertRejects(@() model(2,0,3,false), ...
    'P07:InvalidOfferedFrameInterval');
assertRejects(@() model(2,9,3,false), ...
    'P07:InvalidOfferedFrameInterval');
assertRejects(@() model(2,1.5,3,false), ...
    'P07:InvalidOfferedFrameInterval');
assertRejects(@() model(2,[4 5],3,false), ...
    'P07:InvalidOfferedFrameInterval');
assertRejects(@() model(2,NaN,3,false), ...
    'P07:InvalidOfferedFrameInterval');
assertRejects(@() model(2,Inf,3,false), ...
    'P07:InvalidOfferedFrameInterval');
assertRejects(@() model(2,1+1i,3,false), ...
    'P07:InvalidOfferedFrameInterval');
assertRejects(@() model(2,true,3,false), ...
    'P07:InvalidOfferedFrameInterval');
assertRejects(@() model(2,4,0,false),'P07:InvalidSelectedFrame');
assertRejects(@() model(2,4,7,false),'P07:InvalidSelectedFrame');
assertRejects(@() model(2,4,2.5,false),'P07:InvalidSelectedFrame');
assertRejects(@() model(2,4,[2 3],false),'P07:InvalidSelectedFrame');
assertRejects(@() model(2,4,NaN,false),'P07:InvalidSelectedFrame');
assertRejects(@() model(2,4,Inf,false),'P07:InvalidSelectedFrame');
assertRejects(@() model(2,4,1+1i,false),'P07:InvalidSelectedFrame');
assertRejects(@() model(2,4,true,false),'P07:InvalidSelectedFrame');
assertRejects(@() model(2,4,3,2), ...
    'P07:InvalidBrokenFloorSchedule');
assertRejects(@() model(2,4,3,0.5), ...
    'P07:InvalidBrokenFloorSchedule');
assertRejects(@() model(2,4,3,[false true]), ...
    'P07:InvalidBrokenFloorSchedule');
assertRejects(@() model(2,4,3,NaN), ...
    'P07:InvalidBrokenFloorSchedule');
assertRejects(@() model(2,4,3,Inf), ...
    'P07:InvalidBrokenFloorSchedule');
assertRejects(@() model(2,4,3,1+1i), ...
    'P07:InvalidBrokenFloorSchedule');

selectedFirst = model(3,2,1,false);
selectedLast = model(3,2,6,false);
assert(isequal(selectedFirst.productCodeByFrame, ...
        selectedLast.productCodeByFrame) && ...
    isequal(selectedFirst.referenceIssueCycle, ...
        selectedLast.referenceIssueCycle) && ...
    isequal(selectedFirst.actualIssueCycle,selectedLast.actualIssueCycle) && ...
    isequal(selectedFirst.actualProductValidByFrame, ...
        selectedLast.actualProductValidByFrame) && ...
    isequal(selectedFirst.referenceQueuedFrameCount, ...
        selectedLast.referenceQueuedFrameCount), ...
    'P07:SelectedViewIsolation', ...
    'Selecting a frame must not alter scheduling or products.');
baselineAfterFailures = model(2,4,3,false);
maximumBroken = model(7,8,6,true); %#ok<NASGU>
baselineAfterOtherCall = model(2,4,3,false);
assert(isequaln(baseline,baselineAfterFailures) && ...
    isequaln(baseline,baselineAfterOtherCall), ...
    'P07:DeterminismRecovery', ...
    'Valid output must recover after failures and unrelated calls.');

disp(['P07 checks passed: products, capacity, demand, tail coverage, ' ...
    'validation, resource bounds, and recovery.']);
end

function assertRejects(thunk,expectedIdentifier)
rejectedAsExpected = false;
try
    thunk();
catch exception
    rejectedAsExpected = strcmp(exception.identifier,expectedIdentifier);
end
assert(rejectedAsExpected,'P07:MalformedInputAccepted', ...
    'Expected malformed input to raise %s.',expectedIdentifier);
end
